// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: user.proto

package userrpc

import (
	"context"

	"damai-go/services/user-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AddTicketUserReq    = pb.AddTicketUserReq
	BoolResp            = pb.BoolResp
	CaptchaResp         = pb.CaptchaResp
	Empty               = pb.Empty
	GetCaptchaReq       = pb.GetCaptchaReq
	GetUserByIdReq      = pb.GetUserByIdReq
	ListTicketUsersReq  = pb.ListTicketUsersReq
	ListTicketUsersResp = pb.ListTicketUsersResp
	LoginReq            = pb.LoginReq
	LoginResp           = pb.LoginResp
	RegisterReq         = pb.RegisterReq
	TicketUserInfo      = pb.TicketUserInfo
	UpdateUserReq       = pb.UpdateUserReq
	UserInfo            = pb.UserInfo
	VerifyCaptchaReq    = pb.VerifyCaptchaReq

	UserRpc interface {
		Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*BoolResp, error)
		Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
		GetUserById(ctx context.Context, in *GetUserByIdReq, opts ...grpc.CallOption) (*UserInfo, error)
		UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*BoolResp, error)
		ListTicketUsers(ctx context.Context, in *ListTicketUsersReq, opts ...grpc.CallOption) (*ListTicketUsersResp, error)
		AddTicketUser(ctx context.Context, in *AddTicketUserReq, opts ...grpc.CallOption) (*BoolResp, error)
		GetCaptcha(ctx context.Context, in *GetCaptchaReq, opts ...grpc.CallOption) (*CaptchaResp, error)
		VerifyCaptcha(ctx context.Context, in *VerifyCaptchaReq, opts ...grpc.CallOption) (*BoolResp, error)
	}

	defaultUserRpc struct {
		cli zrpc.Client
	}
)

func NewUserRpc(cli zrpc.Client) UserRpc {
	return &defaultUserRpc{
		cli: cli,
	}
}

func (m *defaultUserRpc) Register(ctx context.Context, in *RegisterReq, opts ...grpc.CallOption) (*BoolResp, error) {
	client := pb.NewUserRpcClient(m.cli.Conn())
	return client.Register(ctx, in, opts...)
}

func (m *defaultUserRpc) Login(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := pb.NewUserRpcClient(m.cli.Conn())
	return client.Login(ctx, in, opts...)
}

func (m *defaultUserRpc) GetUserById(ctx context.Context, in *GetUserByIdReq, opts ...grpc.CallOption) (*UserInfo, error) {
	client := pb.NewUserRpcClient(m.cli.Conn())
	return client.GetUserById(ctx, in, opts...)
}

func (m *defaultUserRpc) UpdateUser(ctx context.Context, in *UpdateUserReq, opts ...grpc.CallOption) (*BoolResp, error) {
	client := pb.NewUserRpcClient(m.cli.Conn())
	return client.UpdateUser(ctx, in, opts...)
}

func (m *defaultUserRpc) ListTicketUsers(ctx context.Context, in *ListTicketUsersReq, opts ...grpc.CallOption) (*ListTicketUsersResp, error) {
	client := pb.NewUserRpcClient(m.cli.Conn())
	return client.ListTicketUsers(ctx, in, opts...)
}

func (m *defaultUserRpc) AddTicketUser(ctx context.Context, in *AddTicketUserReq, opts ...grpc.CallOption) (*BoolResp, error) {
	client := pb.NewUserRpcClient(m.cli.Conn())
	return client.AddTicketUser(ctx, in, opts...)
}

func (m *defaultUserRpc) GetCaptcha(ctx context.Context, in *GetCaptchaReq, opts ...grpc.CallOption) (*CaptchaResp, error) {
	client := pb.NewUserRpcClient(m.cli.Conn())
	return client.GetCaptcha(ctx, in, opts...)
}

func (m *defaultUserRpc) VerifyCaptcha(ctx context.Context, in *VerifyCaptchaReq, opts ...grpc.CallOption) (*BoolResp, error) {
	client := pb.NewUserRpcClient(m.cli.Conn())
	return client.VerifyCaptcha(ctx, in, opts...)
}
