// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"damai-go/services/user-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/ticket/user/add",
				Handler: AddTicketUserHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/ticket/user/list",
				Handler: ListTicketUsersHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/captcha/get",
				Handler: GetCaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/captcha/verify",
				Handler: VerifyCaptchaHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/user/get/id",
				Handler: GetUserByIDHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/login",
				Handler: LoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/register",
				Handler: RegisterHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/user/update",
				Handler: UpdateUserHandler(serverCtx),
			},
		},
	)
}
