services:
  mysql:
    image: mysql:8.4
    command:
      - mysqld
      - --max_connections=320
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: damai_user
    volumes:
      - ./init:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"
