// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: program.proto

package programrpc

import (
	"context"

	"damai-go/services/program-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AutoAssignAndFreezeSeatsReq       = pb.AutoAssignAndFreezeSeatsReq
	AutoAssignAndFreezeSeatsResp      = pb.AutoAssignAndFreezeSeatsResp
	Empty                             = pb.Empty
	GetProgramDetailReq               = pb.GetProgramDetailReq
	ListHomeProgramsReq               = pb.ListHomeProgramsReq
	ListTicketCategoriesByProgramReq  = pb.ListTicketCategoriesByProgramReq
	PageProgramsReq                   = pb.PageProgramsReq
	ProgramCategoryInfo               = pb.ProgramCategoryInfo
	ProgramCategoryListResp           = pb.ProgramCategoryListResp
	ProgramDetailInfo                 = pb.ProgramDetailInfo
	ProgramGroupInfo                  = pb.ProgramGroupInfo
	ProgramHomeListResp               = pb.ProgramHomeListResp
	ProgramHomeSection                = pb.ProgramHomeSection
	ProgramListInfo                   = pb.ProgramListInfo
	ProgramPageResp                   = pb.ProgramPageResp
	ProgramPreorderInfo               = pb.ProgramPreorderInfo
	ProgramPreorderTicketCategoryInfo = pb.ProgramPreorderTicketCategoryInfo
	ProgramSimpleInfo                 = pb.ProgramSimpleInfo
	ReleaseSeatFreezeReq              = pb.ReleaseSeatFreezeReq
	ReleaseSeatFreezeResp             = pb.ReleaseSeatFreezeResp
	SeatInfo                          = pb.SeatInfo
	TicketCategoryDetailInfo          = pb.TicketCategoryDetailInfo
	TicketCategoryDetailListResp      = pb.TicketCategoryDetailListResp
	TicketCategoryInfo                = pb.TicketCategoryInfo

	ProgramRpc interface {
		ListProgramCategories(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProgramCategoryListResp, error)
		ListHomePrograms(ctx context.Context, in *ListHomeProgramsReq, opts ...grpc.CallOption) (*ProgramHomeListResp, error)
		PagePrograms(ctx context.Context, in *PageProgramsReq, opts ...grpc.CallOption) (*ProgramPageResp, error)
		GetProgramDetail(ctx context.Context, in *GetProgramDetailReq, opts ...grpc.CallOption) (*ProgramDetailInfo, error)
		GetProgramPreorder(ctx context.Context, in *GetProgramDetailReq, opts ...grpc.CallOption) (*ProgramPreorderInfo, error)
		ListTicketCategoriesByProgram(ctx context.Context, in *ListTicketCategoriesByProgramReq, opts ...grpc.CallOption) (*TicketCategoryDetailListResp, error)
		AutoAssignAndFreezeSeats(ctx context.Context, in *AutoAssignAndFreezeSeatsReq, opts ...grpc.CallOption) (*AutoAssignAndFreezeSeatsResp, error)
		ReleaseSeatFreeze(ctx context.Context, in *ReleaseSeatFreezeReq, opts ...grpc.CallOption) (*ReleaseSeatFreezeResp, error)
	}

	defaultProgramRpc struct {
		cli zrpc.Client
	}
)

func NewProgramRpc(cli zrpc.Client) ProgramRpc {
	return &defaultProgramRpc{
		cli: cli,
	}
}

func (m *defaultProgramRpc) ListProgramCategories(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProgramCategoryListResp, error) {
	client := pb.NewProgramRpcClient(m.cli.Conn())
	return client.ListProgramCategories(ctx, in, opts...)
}

func (m *defaultProgramRpc) ListHomePrograms(ctx context.Context, in *ListHomeProgramsReq, opts ...grpc.CallOption) (*ProgramHomeListResp, error) {
	client := pb.NewProgramRpcClient(m.cli.Conn())
	return client.ListHomePrograms(ctx, in, opts...)
}

func (m *defaultProgramRpc) PagePrograms(ctx context.Context, in *PageProgramsReq, opts ...grpc.CallOption) (*ProgramPageResp, error) {
	client := pb.NewProgramRpcClient(m.cli.Conn())
	return client.PagePrograms(ctx, in, opts...)
}

func (m *defaultProgramRpc) GetProgramDetail(ctx context.Context, in *GetProgramDetailReq, opts ...grpc.CallOption) (*ProgramDetailInfo, error) {
	client := pb.NewProgramRpcClient(m.cli.Conn())
	return client.GetProgramDetail(ctx, in, opts...)
}

func (m *defaultProgramRpc) GetProgramPreorder(ctx context.Context, in *GetProgramDetailReq, opts ...grpc.CallOption) (*ProgramPreorderInfo, error) {
	client := pb.NewProgramRpcClient(m.cli.Conn())
	return client.GetProgramPreorder(ctx, in, opts...)
}

func (m *defaultProgramRpc) ListTicketCategoriesByProgram(ctx context.Context, in *ListTicketCategoriesByProgramReq, opts ...grpc.CallOption) (*TicketCategoryDetailListResp, error) {
	client := pb.NewProgramRpcClient(m.cli.Conn())
	return client.ListTicketCategoriesByProgram(ctx, in, opts...)
}

func (m *defaultProgramRpc) AutoAssignAndFreezeSeats(ctx context.Context, in *AutoAssignAndFreezeSeatsReq, opts ...grpc.CallOption) (*AutoAssignAndFreezeSeatsResp, error) {
	client := pb.NewProgramRpcClient(m.cli.Conn())
	return client.AutoAssignAndFreezeSeats(ctx, in, opts...)
}

func (m *defaultProgramRpc) ReleaseSeatFreeze(ctx context.Context, in *ReleaseSeatFreezeReq, opts ...grpc.CallOption) (*ReleaseSeatFreezeResp, error) {
	client := pb.NewProgramRpcClient(m.cli.Conn())
	return client.ReleaseSeatFreeze(ctx, in, opts...)
}
