DROP TABLE IF EXISTS `d_program`;
CREATE TABLE `d_program` (
  `id` bigint NOT NULL COMMENT '主键',
  `program_group_id` bigint NOT NULL COMMENT '节目分组编号',
  `prime` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否为分组主节目：1是 0否',
  `area_id` bigint NOT NULL COMMENT '地区编号',
  `program_category_id` bigint NOT NULL COMMENT '节目分类编号',
  `parent_program_category_id` bigint NOT NULL COMMENT '父级分类编号',
  `title` varchar(512) NOT NULL COMMENT '节目标题',
  `actor` varchar(256) DEFAULT NULL COMMENT '演员或艺人信息',
  `place` varchar(100) DEFAULT NULL COMMENT '演出地点',
  `item_picture` text COMMENT '节目封面图',
  `pre_sell` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否预售：1是 0否',
  `pre_sell_instruction` varchar(256) DEFAULT NULL COMMENT '预售说明',
  `important_notice` varchar(512) DEFAULT NULL COMMENT '重要须知',
  `detail` text NOT NULL COMMENT '节目详情',
  `per_order_limit_purchase_count` int DEFAULT 6 COMMENT '单笔订单限购数量',
  `per_account_limit_purchase_count` int DEFAULT 6 COMMENT '单账号限购数量',
  `refund_ticket_rule` varchar(512) DEFAULT NULL COMMENT '退票规则文案',
  `delivery_instruction` varchar(512) DEFAULT NULL COMMENT '配送说明',
  `entry_rule` varchar(512) DEFAULT NULL COMMENT '入场规则',
  `child_purchase` varchar(512) DEFAULT NULL COMMENT '儿童购票说明',
  `invoice_specification` varchar(512) DEFAULT NULL COMMENT '发票说明',
  `real_ticket_purchase_rule` text COMMENT '实名购票规则',
  `abnormal_order_description` text COMMENT '异常订单说明',
  `kind_reminder` text COMMENT '温馨提示',
  `performance_duration` varchar(100) DEFAULT NULL COMMENT '演出时长',
  `entry_time` varchar(512) DEFAULT NULL COMMENT '入场时间说明',
  `min_performance_count` int DEFAULT NULL COMMENT '最少演出场次',
  `main_actor` varchar(100) DEFAULT NULL COMMENT '主演信息',
  `min_performance_duration` varchar(100) DEFAULT NULL COMMENT '最短演出时长',
  `prohibited_item` text COMMENT '禁带物品说明',
  `deposit_specification` varchar(512) DEFAULT NULL COMMENT '定金说明',
  `total_count` bigint DEFAULT NULL COMMENT '初始可售票数',
  `permit_refund` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否允许退票：0否 1有条件 2允许',
  `refund_explain` varchar(512) DEFAULT NULL COMMENT '退票说明',
  `refund_rule_json` json DEFAULT NULL COMMENT '机器可读退票规则',
  `rel_name_ticket_entrance` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否实名入场：1是 0否',
  `rel_name_ticket_entrance_explain` varchar(512) DEFAULT NULL COMMENT '实名入场说明',
  `permit_choose_seat` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否支持选座：1是 0否',
  `choose_seat_explain` varchar(512) DEFAULT NULL COMMENT '选座说明',
  `electronic_delivery_ticket` tinyint(1) NOT NULL DEFAULT 1 COMMENT '票券交付方式：0无 1电子票 2配送',
  `electronic_delivery_ticket_explain` varchar(512) DEFAULT NULL COMMENT '票券交付说明',
  `electronic_invoice` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否支持电子发票：1是 0否',
  `electronic_invoice_explain` varchar(512) DEFAULT NULL COMMENT '电子发票说明',
  `high_heat` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否热门：1是 0否',
  `program_status` tinyint(1) NOT NULL DEFAULT 1 COMMENT '节目状态：1上架 0下架',
  `issue_time` datetime DEFAULT NULL COMMENT '开票时间',
  `rush_sale_open_time` datetime DEFAULT NULL COMMENT '抢票开始时间',
  `rush_sale_end_time` datetime DEFAULT NULL COMMENT '抢票结束时间',
  `inventory_preheat_status` tinyint(1) NOT NULL DEFAULT 0 COMMENT '库存预热状态：0未预热 1待执行 2已完成',
  `create_time` datetime NOT NULL COMMENT '创建时间',
  `edit_time` datetime NOT NULL COMMENT '更新时间',
  `status` tinyint(1) NOT NULL DEFAULT 1 COMMENT '数据状态：1正常 0删除',
  PRIMARY KEY (`id`),
  KEY `idx_program_group_id` (`program_group_id`),
  KEY `idx_parent_program_category_id` (`parent_program_category_id`),
  KEY `idx_program_category_id` (`program_category_id`),
  KEY `idx_issue_time` (`issue_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='节目表';
