DROP TABLE IF EXISTS `d_program`;
CREATE TABLE `d_program` (
  `id` bigint NOT NULL COMMENT 'primary key',
  `program_group_id` bigint NOT NULL COMMENT 'program group id',
  `prime` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1 primary program in group',
  `area_id` bigint NOT NULL COMMENT 'area id',
  `program_category_id` bigint NOT NULL COMMENT 'category id',
  `parent_program_category_id` bigint NOT NULL COMMENT 'parent category id',
  `title` varchar(512) NOT NULL COMMENT 'title',
  `actor` varchar(256) DEFAULT NULL COMMENT 'actor',
  `place` varchar(100) DEFAULT NULL COMMENT 'place',
  `item_picture` text COMMENT 'cover image',
  `pre_sell` tinyint(1) NOT NULL DEFAULT 0 COMMENT '1 presell, 0 no',
  `pre_sell_instruction` varchar(256) DEFAULT NULL COMMENT 'presell instruction',
  `important_notice` varchar(512) DEFAULT NULL COMMENT 'important notice',
  `detail` text NOT NULL COMMENT 'detail',
  `per_order_limit_purchase_count` int DEFAULT 6 COMMENT 'per order limit',
  `per_account_limit_purchase_count` int DEFAULT 6 COMMENT 'per account limit',
  `refund_ticket_rule` varchar(512) DEFAULT NULL COMMENT 'refund rule',
  `delivery_instruction` varchar(512) DEFAULT NULL COMMENT 'delivery instruction',
  `entry_rule` varchar(512) DEFAULT NULL COMMENT 'entry rule',
  `child_purchase` varchar(512) DEFAULT NULL COMMENT 'child ticket policy',
  `invoice_specification` varchar(512) DEFAULT NULL COMMENT 'invoice instruction',
  `real_ticket_purchase_rule` text COMMENT 'real name purchase rule',
  `abnormal_order_description` text COMMENT 'abnormal order description',
  `kind_reminder` text COMMENT 'kind reminder',
  `performance_duration` varchar(100) DEFAULT NULL COMMENT 'performance duration',
  `entry_time` varchar(512) DEFAULT NULL COMMENT 'entry time',
  `min_performance_count` int DEFAULT NULL COMMENT 'minimum performance count',
  `main_actor` varchar(100) DEFAULT NULL COMMENT 'main actor',
  `min_performance_duration` varchar(100) DEFAULT NULL COMMENT 'minimum performance duration',
  `prohibited_item` text COMMENT 'prohibited items',
  `deposit_specification` varchar(512) DEFAULT NULL COMMENT 'deposit instruction',
  `total_count` bigint DEFAULT NULL COMMENT 'initial sellable ticket count',
  `permit_refund` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0 no,1 conditional,2 all',
  `refund_explain` varchar(512) DEFAULT NULL COMMENT 'refund explanation',
  `refund_rule_json` json DEFAULT NULL COMMENT 'machine readable refund rule',
  `rel_name_ticket_entrance` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'real-name ticket entry',
  `rel_name_ticket_entrance_explain` varchar(512) DEFAULT NULL COMMENT 'real-name ticket entry explanation',
  `permit_choose_seat` tinyint(1) NOT NULL DEFAULT 0 COMMENT '1 allow choose seat',
  `choose_seat_explain` varchar(512) DEFAULT NULL COMMENT 'choose seat explanation',
  `electronic_delivery_ticket` tinyint(1) NOT NULL DEFAULT 1 COMMENT '0 none,1 e-ticket,2 delivery',
  `electronic_delivery_ticket_explain` varchar(512) DEFAULT NULL COMMENT 'electronic delivery ticket explanation',
  `electronic_invoice` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1 yes,0 no',
  `electronic_invoice_explain` varchar(512) DEFAULT NULL COMMENT 'electronic invoice explanation',
  `high_heat` tinyint(1) NOT NULL DEFAULT 0 COMMENT 'hot score switch',
  `program_status` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1 on shelf,0 off shelf',
  `issue_time` datetime DEFAULT NULL COMMENT 'issue time',
  `rush_sale_open_time` datetime DEFAULT NULL COMMENT 'rush sale open time',
  `rush_sale_end_time` datetime DEFAULT NULL COMMENT 'rush sale end time',
  `inventory_preheat_status` tinyint(1) NOT NULL DEFAULT 0 COMMENT '0 not preheated, 1 scheduled, 2 completed',
  `create_time` datetime NOT NULL COMMENT 'created at',
  `edit_time` datetime NOT NULL COMMENT 'updated at',
  `status` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1 active, 0 deleted',
  PRIMARY KEY (`id`),
  KEY `idx_program_group_id` (`program_group_id`),
  KEY `idx_parent_program_category_id` (`parent_program_category_id`),
  KEY `idx_program_category_id` (`program_category_id`),
  KEY `idx_issue_time` (`issue_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='programs';
