// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	dOrderTicketUserFieldNames          = builder.RawFieldNames(&DOrderTicketUser{})
	dOrderTicketUserRows                = strings.Join(dOrderTicketUserFieldNames, ",")
	dOrderTicketUserRowsExpectAutoSet   = strings.Join(stringx.Remove(dOrderTicketUserFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	dOrderTicketUserRowsWithPlaceHolder = strings.Join(stringx.Remove(dOrderTicketUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	dOrderTicketUserModel interface {
		Insert(ctx context.Context, data *DOrderTicketUser) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*DOrderTicketUser, error)
		Update(ctx context.Context, data *DOrderTicketUser) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDOrderTicketUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	DOrderTicketUser struct {
		Id                 int64     `db:"id"`                    // primary key
		OrderNumber        int64     `db:"order_number"`          // order number
		UserId             int64     `db:"user_id"`               // 下单用户ID
		TicketUserId       int64     `db:"ticket_user_id"`        // 观演人ID
		TicketUserName     string    `db:"ticket_user_name"`      // 观演人姓名快照
		TicketUserIdNumber string    `db:"ticket_user_id_number"` // 观演人证件号快照
		TicketCategoryId   int64     `db:"ticket_category_id"`    // ticket category id
		TicketCategoryName string    `db:"ticket_category_name"`  // ticket category name snapshot
		TicketPrice        float64   `db:"ticket_price"`          // ticket category price snapshot
		SeatId             int64     `db:"seat_id"`               // seat id
		SeatRow            int64     `db:"seat_row"`              // seat row
		SeatCol            int64     `db:"seat_col"`              // seat col
		SeatPrice          float64   `db:"seat_price"`            // seat price snapshot
		OrderStatus        int64     `db:"order_status"`          // 1 unpaid, 2 cancelled, 3 paid
		CreateOrderTime    time.Time `db:"create_order_time"`     // order created at
		CreateTime         time.Time `db:"create_time"`           // created at
		EditTime           time.Time `db:"edit_time"`             // updated at
		Status             int64     `db:"status"`                // 1 active, 0 deleted
	}
)

func newDOrderTicketUserModel(conn sqlx.SqlConn) *defaultDOrderTicketUserModel {
	return &defaultDOrderTicketUserModel{
		conn:  conn,
		table: "`d_order_ticket_user_00`",
	}
}

func (m *defaultDOrderTicketUserModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultDOrderTicketUserModel) FindOne(ctx context.Context, id int64) (*DOrderTicketUser, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dOrderTicketUserRows, m.table)
	var resp DOrderTicketUser
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDOrderTicketUserModel) Insert(ctx context.Context, data *DOrderTicketUser) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, dOrderTicketUserRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.OrderNumber, data.UserId, data.TicketUserId, data.TicketUserName, data.TicketUserIdNumber, data.TicketCategoryId, data.TicketCategoryName, data.TicketPrice, data.SeatId, data.SeatRow, data.SeatCol, data.SeatPrice, data.OrderStatus, data.CreateOrderTime, data.EditTime, data.Status)
	return ret, err
}

func (m *defaultDOrderTicketUserModel) Update(ctx context.Context, data *DOrderTicketUser) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, dOrderTicketUserRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.OrderNumber, data.UserId, data.TicketUserId, data.TicketUserName, data.TicketUserIdNumber, data.TicketCategoryId, data.TicketCategoryName, data.TicketPrice, data.SeatId, data.SeatRow, data.SeatCol, data.SeatPrice, data.OrderStatus, data.CreateOrderTime, data.EditTime, data.Status, data.Id)
	return err
}

func (m *defaultDOrderTicketUserModel) tableName() string {
	return m.table
}
