CREATE DATABASE IF NOT EXISTS livepass_user CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS livepass_program CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS livepass_order CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS livepass_pay CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
