// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: services/pay-rpc/pay.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PayRpc_MockPay_FullMethodName    = "/pay.PayRpc/MockPay"
	PayRpc_GetPayBill_FullMethodName = "/pay.PayRpc/GetPayBill"
	PayRpc_Refund_FullMethodName     = "/pay.PayRpc/Refund"
)

// PayRpcClient is the client API for PayRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PayRpcClient interface {
	MockPay(ctx context.Context, in *MockPayReq, opts ...grpc.CallOption) (*MockPayResp, error)
	GetPayBill(ctx context.Context, in *GetPayBillReq, opts ...grpc.CallOption) (*GetPayBillResp, error)
	Refund(ctx context.Context, in *RefundReq, opts ...grpc.CallOption) (*RefundResp, error)
}

type payRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewPayRpcClient(cc grpc.ClientConnInterface) PayRpcClient {
	return &payRpcClient{cc}
}

func (c *payRpcClient) MockPay(ctx context.Context, in *MockPayReq, opts ...grpc.CallOption) (*MockPayResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MockPayResp)
	err := c.cc.Invoke(ctx, PayRpc_MockPay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payRpcClient) GetPayBill(ctx context.Context, in *GetPayBillReq, opts ...grpc.CallOption) (*GetPayBillResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPayBillResp)
	err := c.cc.Invoke(ctx, PayRpc_GetPayBill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payRpcClient) Refund(ctx context.Context, in *RefundReq, opts ...grpc.CallOption) (*RefundResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefundResp)
	err := c.cc.Invoke(ctx, PayRpc_Refund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayRpcServer is the server API for PayRpc service.
// All implementations must embed UnimplementedPayRpcServer
// for forward compatibility.
type PayRpcServer interface {
	MockPay(context.Context, *MockPayReq) (*MockPayResp, error)
	GetPayBill(context.Context, *GetPayBillReq) (*GetPayBillResp, error)
	Refund(context.Context, *RefundReq) (*RefundResp, error)
	mustEmbedUnimplementedPayRpcServer()
}

// UnimplementedPayRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPayRpcServer struct{}

func (UnimplementedPayRpcServer) MockPay(context.Context, *MockPayReq) (*MockPayResp, error) {
	return nil, status.Error(codes.Unimplemented, "method MockPay not implemented")
}
func (UnimplementedPayRpcServer) GetPayBill(context.Context, *GetPayBillReq) (*GetPayBillResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPayBill not implemented")
}
func (UnimplementedPayRpcServer) Refund(context.Context, *RefundReq) (*RefundResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Refund not implemented")
}
func (UnimplementedPayRpcServer) mustEmbedUnimplementedPayRpcServer() {}
func (UnimplementedPayRpcServer) testEmbeddedByValue()                {}

// UnsafePayRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PayRpcServer will
// result in compilation errors.
type UnsafePayRpcServer interface {
	mustEmbedUnimplementedPayRpcServer()
}

func RegisterPayRpcServer(s grpc.ServiceRegistrar, srv PayRpcServer) {
	// If the following call panics, it indicates UnimplementedPayRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PayRpc_ServiceDesc, srv)
}

func _PayRpc_MockPay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MockPayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayRpcServer).MockPay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayRpc_MockPay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayRpcServer).MockPay(ctx, req.(*MockPayReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayRpc_GetPayBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPayBillReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayRpcServer).GetPayBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayRpc_GetPayBill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayRpcServer).GetPayBill(ctx, req.(*GetPayBillReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _PayRpc_Refund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayRpcServer).Refund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PayRpc_Refund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayRpcServer).Refund(ctx, req.(*RefundReq))
	}
	return interceptor(ctx, in, info, handler)
}

// PayRpc_ServiceDesc is the grpc.ServiceDesc for PayRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PayRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pay.PayRpc",
	HandlerType: (*PayRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MockPay",
			Handler:    _PayRpc_MockPay_Handler,
		},
		{
			MethodName: "GetPayBill",
			Handler:    _PayRpc_GetPayBill_Handler,
		},
		{
			MethodName: "Refund",
			Handler:    _PayRpc_Refund_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/pay-rpc/pay.proto",
}
