DROP TABLE IF EXISTS `d_order_ticket_user`;
CREATE TABLE `d_order_ticket_user` (
  `id` bigint NOT NULL COMMENT 'primary key',
  `order_number` bigint NOT NULL COMMENT 'order number',
  `user_id` bigint NOT NULL COMMENT 'owner user id',
  `ticket_user_id` bigint NOT NULL COMMENT 'ticket user id',
  `ticket_user_name` varchar(128) NOT NULL COMMENT 'ticket user name snapshot',
  `ticket_user_id_number` varchar(64) NOT NULL COMMENT 'ticket user id number snapshot',
  `ticket_category_id` bigint NOT NULL COMMENT 'ticket category id',
  `ticket_category_name` varchar(128) NOT NULL COMMENT 'ticket category name snapshot',
  `ticket_price` decimal(10,0) NOT NULL COMMENT 'ticket category price snapshot',
  `seat_id` bigint NOT NULL COMMENT 'seat id',
  `seat_row` int NOT NULL COMMENT 'seat row',
  `seat_col` int NOT NULL COMMENT 'seat col',
  `seat_price` decimal(10,0) NOT NULL COMMENT 'seat price snapshot',
  `order_status` tinyint NOT NULL COMMENT '1 unpaid, 2 cancelled',
  `create_order_time` datetime NOT NULL COMMENT 'order created at',
  `create_time` datetime NOT NULL COMMENT 'created at',
  `edit_time` datetime NOT NULL COMMENT 'updated at',
  `status` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1 active, 0 deleted',
  PRIMARY KEY (`id`),
  KEY `idx_order_number` (`order_number`),
  KEY `idx_user_ticket_user` (`user_id`,`ticket_user_id`),
  KEY `idx_create_order_time` (`create_order_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='order ticket user snapshot table';
