DROP TABLE IF EXISTS `d_order`;
CREATE TABLE `d_order` (
  `id` bigint NOT NULL COMMENT 'primary key',
  `order_number` bigint NOT NULL COMMENT 'order number',
  `program_id` bigint NOT NULL COMMENT 'program id',
  `program_title` varchar(256) NOT NULL COMMENT 'program title snapshot',
  `program_item_picture` varchar(512) NOT NULL DEFAULT '' COMMENT 'program picture snapshot',
  `program_place` varchar(256) NOT NULL COMMENT 'program place snapshot',
  `program_show_time` datetime NOT NULL COMMENT 'program show time snapshot',
  `program_permit_choose_seat` tinyint NOT NULL COMMENT 'program permit choose seat snapshot',
  `user_id` bigint NOT NULL COMMENT 'user id',
  `distribution_mode` varchar(64) NOT NULL DEFAULT '' COMMENT 'distribution mode',
  `take_ticket_mode` varchar(64) NOT NULL DEFAULT '' COMMENT 'take ticket mode',
  `ticket_count` int NOT NULL COMMENT 'ticket count',
  `order_price` decimal(10,0) NOT NULL COMMENT 'order total price',
  `order_status` tinyint NOT NULL COMMENT '1 unpaid, 2 cancelled, 3 paid',
  `freeze_token` varchar(64) NOT NULL COMMENT 'seat freeze token',
  `order_expire_time` datetime NOT NULL COMMENT 'order expire time',
  `create_order_time` datetime NOT NULL COMMENT 'order created at',
  `cancel_order_time` datetime DEFAULT NULL COMMENT 'order cancelled at',
  `pay_order_time` datetime DEFAULT NULL COMMENT 'order paid at',
  `create_time` datetime NOT NULL COMMENT 'created at',
  `edit_time` datetime NOT NULL COMMENT 'updated at',
  `status` tinyint(1) NOT NULL DEFAULT 1 COMMENT '1 active, 0 deleted',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_order_number` (`order_number`),
  KEY `idx_user_status_time` (`user_id`,`order_status`,`create_order_time`),
  KEY `idx_program_user_status` (`program_id`,`user_id`,`order_status`),
  KEY `idx_close_scan` (`order_status`,`order_expire_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='order main table';
