// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: program.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProgramRpc_CreateProgram_FullMethodName                 = "/program.ProgramRpc/CreateProgram"
	ProgramRpc_UpdateProgram_FullMethodName                 = "/program.ProgramRpc/UpdateProgram"
	ProgramRpc_InvalidProgram_FullMethodName                = "/program.ProgramRpc/InvalidProgram"
	ProgramRpc_ResetProgram_FullMethodName                  = "/program.ProgramRpc/ResetProgram"
	ProgramRpc_ListProgramCategories_FullMethodName         = "/program.ProgramRpc/ListProgramCategories"
	ProgramRpc_ListProgramCategoriesByType_FullMethodName   = "/program.ProgramRpc/ListProgramCategoriesByType"
	ProgramRpc_ListProgramCategoriesByParent_FullMethodName = "/program.ProgramRpc/ListProgramCategoriesByParent"
	ProgramRpc_BatchCreateProgramCategories_FullMethodName  = "/program.ProgramRpc/BatchCreateProgramCategories"
	ProgramRpc_ListHomePrograms_FullMethodName              = "/program.ProgramRpc/ListHomePrograms"
	ProgramRpc_PagePrograms_FullMethodName                  = "/program.ProgramRpc/PagePrograms"
	ProgramRpc_GetProgramDetail_FullMethodName              = "/program.ProgramRpc/GetProgramDetail"
	ProgramRpc_GetProgramPreorder_FullMethodName            = "/program.ProgramRpc/GetProgramPreorder"
	ProgramRpc_CreateProgramShowTime_FullMethodName         = "/program.ProgramRpc/CreateProgramShowTime"
	ProgramRpc_UpdateProgramShowTime_FullMethodName         = "/program.ProgramRpc/UpdateProgramShowTime"
	ProgramRpc_CreateTicketCategory_FullMethodName          = "/program.ProgramRpc/CreateTicketCategory"
	ProgramRpc_GetTicketCategoryDetail_FullMethodName       = "/program.ProgramRpc/GetTicketCategoryDetail"
	ProgramRpc_ListTicketCategoriesByProgram_FullMethodName = "/program.ProgramRpc/ListTicketCategoriesByProgram"
	ProgramRpc_CreateSeat_FullMethodName                    = "/program.ProgramRpc/CreateSeat"
	ProgramRpc_BatchCreateSeats_FullMethodName              = "/program.ProgramRpc/BatchCreateSeats"
	ProgramRpc_GetSeatRelateInfo_FullMethodName             = "/program.ProgramRpc/GetSeatRelateInfo"
	ProgramRpc_AutoAssignAndFreezeSeats_FullMethodName      = "/program.ProgramRpc/AutoAssignAndFreezeSeats"
	ProgramRpc_ReleaseSeatFreeze_FullMethodName             = "/program.ProgramRpc/ReleaseSeatFreeze"
	ProgramRpc_ConfirmSeatFreeze_FullMethodName             = "/program.ProgramRpc/ConfirmSeatFreeze"
	ProgramRpc_EvaluateRefundRule_FullMethodName            = "/program.ProgramRpc/EvaluateRefundRule"
	ProgramRpc_ReleaseSoldSeats_FullMethodName              = "/program.ProgramRpc/ReleaseSoldSeats"
	ProgramRpc_PrimeSeatLedger_FullMethodName               = "/program.ProgramRpc/PrimeSeatLedger"
)

// ProgramRpcClient is the client API for ProgramRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProgramRpcClient interface {
	CreateProgram(ctx context.Context, in *CreateProgramReq, opts ...grpc.CallOption) (*CreateProgramResp, error)
	UpdateProgram(ctx context.Context, in *UpdateProgramReq, opts ...grpc.CallOption) (*BoolResp, error)
	InvalidProgram(ctx context.Context, in *ProgramInvalidReq, opts ...grpc.CallOption) (*BoolResp, error)
	ResetProgram(ctx context.Context, in *ProgramResetReq, opts ...grpc.CallOption) (*BoolResp, error)
	ListProgramCategories(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProgramCategoryListResp, error)
	ListProgramCategoriesByType(ctx context.Context, in *ProgramCategoryTypeReq, opts ...grpc.CallOption) (*ProgramCategoryListResp, error)
	ListProgramCategoriesByParent(ctx context.Context, in *ParentProgramCategoryReq, opts ...grpc.CallOption) (*ProgramCategoryListResp, error)
	BatchCreateProgramCategories(ctx context.Context, in *ProgramCategoryBatchSaveReq, opts ...grpc.CallOption) (*BoolResp, error)
	ListHomePrograms(ctx context.Context, in *ListHomeProgramsReq, opts ...grpc.CallOption) (*ProgramHomeListResp, error)
	PagePrograms(ctx context.Context, in *PageProgramsReq, opts ...grpc.CallOption) (*ProgramPageResp, error)
	GetProgramDetail(ctx context.Context, in *GetProgramDetailReq, opts ...grpc.CallOption) (*ProgramDetailInfo, error)
	GetProgramPreorder(ctx context.Context, in *GetProgramPreorderReq, opts ...grpc.CallOption) (*ProgramPreorderInfo, error)
	CreateProgramShowTime(ctx context.Context, in *ProgramShowTimeAddReq, opts ...grpc.CallOption) (*IdResp, error)
	UpdateProgramShowTime(ctx context.Context, in *UpdateProgramShowTimeReq, opts ...grpc.CallOption) (*BoolResp, error)
	CreateTicketCategory(ctx context.Context, in *TicketCategoryAddReq, opts ...grpc.CallOption) (*IdResp, error)
	GetTicketCategoryDetail(ctx context.Context, in *TicketCategoryReq, opts ...grpc.CallOption) (*TicketCategoryDetailInfo, error)
	ListTicketCategoriesByProgram(ctx context.Context, in *ListTicketCategoriesByProgramReq, opts ...grpc.CallOption) (*TicketCategoryDetailListResp, error)
	CreateSeat(ctx context.Context, in *SeatAddReq, opts ...grpc.CallOption) (*IdResp, error)
	BatchCreateSeats(ctx context.Context, in *SeatBatchAddReq, opts ...grpc.CallOption) (*BoolResp, error)
	GetSeatRelateInfo(ctx context.Context, in *SeatListReq, opts ...grpc.CallOption) (*SeatRelateInfo, error)
	AutoAssignAndFreezeSeats(ctx context.Context, in *AutoAssignAndFreezeSeatsReq, opts ...grpc.CallOption) (*AutoAssignAndFreezeSeatsResp, error)
	ReleaseSeatFreeze(ctx context.Context, in *ReleaseSeatFreezeReq, opts ...grpc.CallOption) (*ReleaseSeatFreezeResp, error)
	ConfirmSeatFreeze(ctx context.Context, in *ConfirmSeatFreezeReq, opts ...grpc.CallOption) (*ConfirmSeatFreezeResp, error)
	EvaluateRefundRule(ctx context.Context, in *EvaluateRefundRuleReq, opts ...grpc.CallOption) (*EvaluateRefundRuleResp, error)
	ReleaseSoldSeats(ctx context.Context, in *ReleaseSoldSeatsReq, opts ...grpc.CallOption) (*ReleaseSoldSeatsResp, error)
	PrimeSeatLedger(ctx context.Context, in *PrimeSeatLedgerReq, opts ...grpc.CallOption) (*BoolResp, error)
}

type programRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewProgramRpcClient(cc grpc.ClientConnInterface) ProgramRpcClient {
	return &programRpcClient{cc}
}

func (c *programRpcClient) CreateProgram(ctx context.Context, in *CreateProgramReq, opts ...grpc.CallOption) (*CreateProgramResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateProgramResp)
	err := c.cc.Invoke(ctx, ProgramRpc_CreateProgram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) UpdateProgram(ctx context.Context, in *UpdateProgramReq, opts ...grpc.CallOption) (*BoolResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResp)
	err := c.cc.Invoke(ctx, ProgramRpc_UpdateProgram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) InvalidProgram(ctx context.Context, in *ProgramInvalidReq, opts ...grpc.CallOption) (*BoolResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResp)
	err := c.cc.Invoke(ctx, ProgramRpc_InvalidProgram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) ResetProgram(ctx context.Context, in *ProgramResetReq, opts ...grpc.CallOption) (*BoolResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResp)
	err := c.cc.Invoke(ctx, ProgramRpc_ResetProgram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) ListProgramCategories(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProgramCategoryListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgramCategoryListResp)
	err := c.cc.Invoke(ctx, ProgramRpc_ListProgramCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) ListProgramCategoriesByType(ctx context.Context, in *ProgramCategoryTypeReq, opts ...grpc.CallOption) (*ProgramCategoryListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgramCategoryListResp)
	err := c.cc.Invoke(ctx, ProgramRpc_ListProgramCategoriesByType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) ListProgramCategoriesByParent(ctx context.Context, in *ParentProgramCategoryReq, opts ...grpc.CallOption) (*ProgramCategoryListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgramCategoryListResp)
	err := c.cc.Invoke(ctx, ProgramRpc_ListProgramCategoriesByParent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) BatchCreateProgramCategories(ctx context.Context, in *ProgramCategoryBatchSaveReq, opts ...grpc.CallOption) (*BoolResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResp)
	err := c.cc.Invoke(ctx, ProgramRpc_BatchCreateProgramCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) ListHomePrograms(ctx context.Context, in *ListHomeProgramsReq, opts ...grpc.CallOption) (*ProgramHomeListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgramHomeListResp)
	err := c.cc.Invoke(ctx, ProgramRpc_ListHomePrograms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) PagePrograms(ctx context.Context, in *PageProgramsReq, opts ...grpc.CallOption) (*ProgramPageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgramPageResp)
	err := c.cc.Invoke(ctx, ProgramRpc_PagePrograms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) GetProgramDetail(ctx context.Context, in *GetProgramDetailReq, opts ...grpc.CallOption) (*ProgramDetailInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgramDetailInfo)
	err := c.cc.Invoke(ctx, ProgramRpc_GetProgramDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) GetProgramPreorder(ctx context.Context, in *GetProgramPreorderReq, opts ...grpc.CallOption) (*ProgramPreorderInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgramPreorderInfo)
	err := c.cc.Invoke(ctx, ProgramRpc_GetProgramPreorder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) CreateProgramShowTime(ctx context.Context, in *ProgramShowTimeAddReq, opts ...grpc.CallOption) (*IdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdResp)
	err := c.cc.Invoke(ctx, ProgramRpc_CreateProgramShowTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) UpdateProgramShowTime(ctx context.Context, in *UpdateProgramShowTimeReq, opts ...grpc.CallOption) (*BoolResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResp)
	err := c.cc.Invoke(ctx, ProgramRpc_UpdateProgramShowTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) CreateTicketCategory(ctx context.Context, in *TicketCategoryAddReq, opts ...grpc.CallOption) (*IdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdResp)
	err := c.cc.Invoke(ctx, ProgramRpc_CreateTicketCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) GetTicketCategoryDetail(ctx context.Context, in *TicketCategoryReq, opts ...grpc.CallOption) (*TicketCategoryDetailInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TicketCategoryDetailInfo)
	err := c.cc.Invoke(ctx, ProgramRpc_GetTicketCategoryDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) ListTicketCategoriesByProgram(ctx context.Context, in *ListTicketCategoriesByProgramReq, opts ...grpc.CallOption) (*TicketCategoryDetailListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TicketCategoryDetailListResp)
	err := c.cc.Invoke(ctx, ProgramRpc_ListTicketCategoriesByProgram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) CreateSeat(ctx context.Context, in *SeatAddReq, opts ...grpc.CallOption) (*IdResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IdResp)
	err := c.cc.Invoke(ctx, ProgramRpc_CreateSeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) BatchCreateSeats(ctx context.Context, in *SeatBatchAddReq, opts ...grpc.CallOption) (*BoolResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResp)
	err := c.cc.Invoke(ctx, ProgramRpc_BatchCreateSeats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) GetSeatRelateInfo(ctx context.Context, in *SeatListReq, opts ...grpc.CallOption) (*SeatRelateInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SeatRelateInfo)
	err := c.cc.Invoke(ctx, ProgramRpc_GetSeatRelateInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) AutoAssignAndFreezeSeats(ctx context.Context, in *AutoAssignAndFreezeSeatsReq, opts ...grpc.CallOption) (*AutoAssignAndFreezeSeatsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AutoAssignAndFreezeSeatsResp)
	err := c.cc.Invoke(ctx, ProgramRpc_AutoAssignAndFreezeSeats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) ReleaseSeatFreeze(ctx context.Context, in *ReleaseSeatFreezeReq, opts ...grpc.CallOption) (*ReleaseSeatFreezeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseSeatFreezeResp)
	err := c.cc.Invoke(ctx, ProgramRpc_ReleaseSeatFreeze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) ConfirmSeatFreeze(ctx context.Context, in *ConfirmSeatFreezeReq, opts ...grpc.CallOption) (*ConfirmSeatFreezeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmSeatFreezeResp)
	err := c.cc.Invoke(ctx, ProgramRpc_ConfirmSeatFreeze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) EvaluateRefundRule(ctx context.Context, in *EvaluateRefundRuleReq, opts ...grpc.CallOption) (*EvaluateRefundRuleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateRefundRuleResp)
	err := c.cc.Invoke(ctx, ProgramRpc_EvaluateRefundRule_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) ReleaseSoldSeats(ctx context.Context, in *ReleaseSoldSeatsReq, opts ...grpc.CallOption) (*ReleaseSoldSeatsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseSoldSeatsResp)
	err := c.cc.Invoke(ctx, ProgramRpc_ReleaseSoldSeats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) PrimeSeatLedger(ctx context.Context, in *PrimeSeatLedgerReq, opts ...grpc.CallOption) (*BoolResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BoolResp)
	err := c.cc.Invoke(ctx, ProgramRpc_PrimeSeatLedger_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProgramRpcServer is the server API for ProgramRpc service.
// All implementations must embed UnimplementedProgramRpcServer
// for forward compatibility.
type ProgramRpcServer interface {
	CreateProgram(context.Context, *CreateProgramReq) (*CreateProgramResp, error)
	UpdateProgram(context.Context, *UpdateProgramReq) (*BoolResp, error)
	InvalidProgram(context.Context, *ProgramInvalidReq) (*BoolResp, error)
	ResetProgram(context.Context, *ProgramResetReq) (*BoolResp, error)
	ListProgramCategories(context.Context, *Empty) (*ProgramCategoryListResp, error)
	ListProgramCategoriesByType(context.Context, *ProgramCategoryTypeReq) (*ProgramCategoryListResp, error)
	ListProgramCategoriesByParent(context.Context, *ParentProgramCategoryReq) (*ProgramCategoryListResp, error)
	BatchCreateProgramCategories(context.Context, *ProgramCategoryBatchSaveReq) (*BoolResp, error)
	ListHomePrograms(context.Context, *ListHomeProgramsReq) (*ProgramHomeListResp, error)
	PagePrograms(context.Context, *PageProgramsReq) (*ProgramPageResp, error)
	GetProgramDetail(context.Context, *GetProgramDetailReq) (*ProgramDetailInfo, error)
	GetProgramPreorder(context.Context, *GetProgramPreorderReq) (*ProgramPreorderInfo, error)
	CreateProgramShowTime(context.Context, *ProgramShowTimeAddReq) (*IdResp, error)
	UpdateProgramShowTime(context.Context, *UpdateProgramShowTimeReq) (*BoolResp, error)
	CreateTicketCategory(context.Context, *TicketCategoryAddReq) (*IdResp, error)
	GetTicketCategoryDetail(context.Context, *TicketCategoryReq) (*TicketCategoryDetailInfo, error)
	ListTicketCategoriesByProgram(context.Context, *ListTicketCategoriesByProgramReq) (*TicketCategoryDetailListResp, error)
	CreateSeat(context.Context, *SeatAddReq) (*IdResp, error)
	BatchCreateSeats(context.Context, *SeatBatchAddReq) (*BoolResp, error)
	GetSeatRelateInfo(context.Context, *SeatListReq) (*SeatRelateInfo, error)
	AutoAssignAndFreezeSeats(context.Context, *AutoAssignAndFreezeSeatsReq) (*AutoAssignAndFreezeSeatsResp, error)
	ReleaseSeatFreeze(context.Context, *ReleaseSeatFreezeReq) (*ReleaseSeatFreezeResp, error)
	ConfirmSeatFreeze(context.Context, *ConfirmSeatFreezeReq) (*ConfirmSeatFreezeResp, error)
	EvaluateRefundRule(context.Context, *EvaluateRefundRuleReq) (*EvaluateRefundRuleResp, error)
	ReleaseSoldSeats(context.Context, *ReleaseSoldSeatsReq) (*ReleaseSoldSeatsResp, error)
	PrimeSeatLedger(context.Context, *PrimeSeatLedgerReq) (*BoolResp, error)
	mustEmbedUnimplementedProgramRpcServer()
}

// UnimplementedProgramRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProgramRpcServer struct{}

func (UnimplementedProgramRpcServer) CreateProgram(context.Context, *CreateProgramReq) (*CreateProgramResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProgram not implemented")
}
func (UnimplementedProgramRpcServer) UpdateProgram(context.Context, *UpdateProgramReq) (*BoolResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProgram not implemented")
}
func (UnimplementedProgramRpcServer) InvalidProgram(context.Context, *ProgramInvalidReq) (*BoolResp, error) {
	return nil, status.Error(codes.Unimplemented, "method InvalidProgram not implemented")
}
func (UnimplementedProgramRpcServer) ResetProgram(context.Context, *ProgramResetReq) (*BoolResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetProgram not implemented")
}
func (UnimplementedProgramRpcServer) ListProgramCategories(context.Context, *Empty) (*ProgramCategoryListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProgramCategories not implemented")
}
func (UnimplementedProgramRpcServer) ListProgramCategoriesByType(context.Context, *ProgramCategoryTypeReq) (*ProgramCategoryListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProgramCategoriesByType not implemented")
}
func (UnimplementedProgramRpcServer) ListProgramCategoriesByParent(context.Context, *ParentProgramCategoryReq) (*ProgramCategoryListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProgramCategoriesByParent not implemented")
}
func (UnimplementedProgramRpcServer) BatchCreateProgramCategories(context.Context, *ProgramCategoryBatchSaveReq) (*BoolResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCreateProgramCategories not implemented")
}
func (UnimplementedProgramRpcServer) ListHomePrograms(context.Context, *ListHomeProgramsReq) (*ProgramHomeListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHomePrograms not implemented")
}
func (UnimplementedProgramRpcServer) PagePrograms(context.Context, *PageProgramsReq) (*ProgramPageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PagePrograms not implemented")
}
func (UnimplementedProgramRpcServer) GetProgramDetail(context.Context, *GetProgramDetailReq) (*ProgramDetailInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProgramDetail not implemented")
}
func (UnimplementedProgramRpcServer) GetProgramPreorder(context.Context, *GetProgramPreorderReq) (*ProgramPreorderInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProgramPreorder not implemented")
}
func (UnimplementedProgramRpcServer) CreateProgramShowTime(context.Context, *ProgramShowTimeAddReq) (*IdResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateProgramShowTime not implemented")
}
func (UnimplementedProgramRpcServer) UpdateProgramShowTime(context.Context, *UpdateProgramShowTimeReq) (*BoolResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProgramShowTime not implemented")
}
func (UnimplementedProgramRpcServer) CreateTicketCategory(context.Context, *TicketCategoryAddReq) (*IdResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTicketCategory not implemented")
}
func (UnimplementedProgramRpcServer) GetTicketCategoryDetail(context.Context, *TicketCategoryReq) (*TicketCategoryDetailInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTicketCategoryDetail not implemented")
}
func (UnimplementedProgramRpcServer) ListTicketCategoriesByProgram(context.Context, *ListTicketCategoriesByProgramReq) (*TicketCategoryDetailListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTicketCategoriesByProgram not implemented")
}
func (UnimplementedProgramRpcServer) CreateSeat(context.Context, *SeatAddReq) (*IdResp, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSeat not implemented")
}
func (UnimplementedProgramRpcServer) BatchCreateSeats(context.Context, *SeatBatchAddReq) (*BoolResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCreateSeats not implemented")
}
func (UnimplementedProgramRpcServer) GetSeatRelateInfo(context.Context, *SeatListReq) (*SeatRelateInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSeatRelateInfo not implemented")
}
func (UnimplementedProgramRpcServer) AutoAssignAndFreezeSeats(context.Context, *AutoAssignAndFreezeSeatsReq) (*AutoAssignAndFreezeSeatsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method AutoAssignAndFreezeSeats not implemented")
}
func (UnimplementedProgramRpcServer) ReleaseSeatFreeze(context.Context, *ReleaseSeatFreezeReq) (*ReleaseSeatFreezeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseSeatFreeze not implemented")
}
func (UnimplementedProgramRpcServer) ConfirmSeatFreeze(context.Context, *ConfirmSeatFreezeReq) (*ConfirmSeatFreezeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmSeatFreeze not implemented")
}
func (UnimplementedProgramRpcServer) EvaluateRefundRule(context.Context, *EvaluateRefundRuleReq) (*EvaluateRefundRuleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateRefundRule not implemented")
}
func (UnimplementedProgramRpcServer) ReleaseSoldSeats(context.Context, *ReleaseSoldSeatsReq) (*ReleaseSoldSeatsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseSoldSeats not implemented")
}
func (UnimplementedProgramRpcServer) PrimeSeatLedger(context.Context, *PrimeSeatLedgerReq) (*BoolResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PrimeSeatLedger not implemented")
}
func (UnimplementedProgramRpcServer) mustEmbedUnimplementedProgramRpcServer() {}
func (UnimplementedProgramRpcServer) testEmbeddedByValue()                    {}

// UnsafeProgramRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProgramRpcServer will
// result in compilation errors.
type UnsafeProgramRpcServer interface {
	mustEmbedUnimplementedProgramRpcServer()
}

func RegisterProgramRpcServer(s grpc.ServiceRegistrar, srv ProgramRpcServer) {
	// If the following call panics, it indicates UnimplementedProgramRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProgramRpc_ServiceDesc, srv)
}

func _ProgramRpc_CreateProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProgramReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).CreateProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_CreateProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).CreateProgram(ctx, req.(*CreateProgramReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_UpdateProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProgramReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).UpdateProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_UpdateProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).UpdateProgram(ctx, req.(*UpdateProgramReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_InvalidProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgramInvalidReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).InvalidProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_InvalidProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).InvalidProgram(ctx, req.(*ProgramInvalidReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_ResetProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgramResetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).ResetProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_ResetProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).ResetProgram(ctx, req.(*ProgramResetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_ListProgramCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).ListProgramCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_ListProgramCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).ListProgramCategories(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_ListProgramCategoriesByType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgramCategoryTypeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).ListProgramCategoriesByType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_ListProgramCategoriesByType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).ListProgramCategoriesByType(ctx, req.(*ProgramCategoryTypeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_ListProgramCategoriesByParent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParentProgramCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).ListProgramCategoriesByParent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_ListProgramCategoriesByParent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).ListProgramCategoriesByParent(ctx, req.(*ParentProgramCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_BatchCreateProgramCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgramCategoryBatchSaveReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).BatchCreateProgramCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_BatchCreateProgramCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).BatchCreateProgramCategories(ctx, req.(*ProgramCategoryBatchSaveReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_ListHomePrograms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHomeProgramsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).ListHomePrograms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_ListHomePrograms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).ListHomePrograms(ctx, req.(*ListHomeProgramsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_PagePrograms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageProgramsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).PagePrograms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_PagePrograms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).PagePrograms(ctx, req.(*PageProgramsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_GetProgramDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProgramDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).GetProgramDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_GetProgramDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).GetProgramDetail(ctx, req.(*GetProgramDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_GetProgramPreorder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProgramPreorderReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).GetProgramPreorder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_GetProgramPreorder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).GetProgramPreorder(ctx, req.(*GetProgramPreorderReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_CreateProgramShowTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProgramShowTimeAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).CreateProgramShowTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_CreateProgramShowTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).CreateProgramShowTime(ctx, req.(*ProgramShowTimeAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_UpdateProgramShowTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProgramShowTimeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).UpdateProgramShowTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_UpdateProgramShowTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).UpdateProgramShowTime(ctx, req.(*UpdateProgramShowTimeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_CreateTicketCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TicketCategoryAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).CreateTicketCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_CreateTicketCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).CreateTicketCategory(ctx, req.(*TicketCategoryAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_GetTicketCategoryDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TicketCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).GetTicketCategoryDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_GetTicketCategoryDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).GetTicketCategoryDetail(ctx, req.(*TicketCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_ListTicketCategoriesByProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTicketCategoriesByProgramReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).ListTicketCategoriesByProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_ListTicketCategoriesByProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).ListTicketCategoriesByProgram(ctx, req.(*ListTicketCategoriesByProgramReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_CreateSeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeatAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).CreateSeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_CreateSeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).CreateSeat(ctx, req.(*SeatAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_BatchCreateSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeatBatchAddReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).BatchCreateSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_BatchCreateSeats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).BatchCreateSeats(ctx, req.(*SeatBatchAddReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_GetSeatRelateInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SeatListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).GetSeatRelateInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_GetSeatRelateInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).GetSeatRelateInfo(ctx, req.(*SeatListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_AutoAssignAndFreezeSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AutoAssignAndFreezeSeatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).AutoAssignAndFreezeSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_AutoAssignAndFreezeSeats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).AutoAssignAndFreezeSeats(ctx, req.(*AutoAssignAndFreezeSeatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_ReleaseSeatFreeze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseSeatFreezeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).ReleaseSeatFreeze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_ReleaseSeatFreeze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).ReleaseSeatFreeze(ctx, req.(*ReleaseSeatFreezeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_ConfirmSeatFreeze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmSeatFreezeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).ConfirmSeatFreeze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_ConfirmSeatFreeze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).ConfirmSeatFreeze(ctx, req.(*ConfirmSeatFreezeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_EvaluateRefundRule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateRefundRuleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).EvaluateRefundRule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_EvaluateRefundRule_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).EvaluateRefundRule(ctx, req.(*EvaluateRefundRuleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_ReleaseSoldSeats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseSoldSeatsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).ReleaseSoldSeats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_ReleaseSoldSeats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).ReleaseSoldSeats(ctx, req.(*ReleaseSoldSeatsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_PrimeSeatLedger_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrimeSeatLedgerReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).PrimeSeatLedger(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_PrimeSeatLedger_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).PrimeSeatLedger(ctx, req.(*PrimeSeatLedgerReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ProgramRpc_ServiceDesc is the grpc.ServiceDesc for ProgramRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProgramRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "program.ProgramRpc",
	HandlerType: (*ProgramRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateProgram",
			Handler:    _ProgramRpc_CreateProgram_Handler,
		},
		{
			MethodName: "UpdateProgram",
			Handler:    _ProgramRpc_UpdateProgram_Handler,
		},
		{
			MethodName: "InvalidProgram",
			Handler:    _ProgramRpc_InvalidProgram_Handler,
		},
		{
			MethodName: "ResetProgram",
			Handler:    _ProgramRpc_ResetProgram_Handler,
		},
		{
			MethodName: "ListProgramCategories",
			Handler:    _ProgramRpc_ListProgramCategories_Handler,
		},
		{
			MethodName: "ListProgramCategoriesByType",
			Handler:    _ProgramRpc_ListProgramCategoriesByType_Handler,
		},
		{
			MethodName: "ListProgramCategoriesByParent",
			Handler:    _ProgramRpc_ListProgramCategoriesByParent_Handler,
		},
		{
			MethodName: "BatchCreateProgramCategories",
			Handler:    _ProgramRpc_BatchCreateProgramCategories_Handler,
		},
		{
			MethodName: "ListHomePrograms",
			Handler:    _ProgramRpc_ListHomePrograms_Handler,
		},
		{
			MethodName: "PagePrograms",
			Handler:    _ProgramRpc_PagePrograms_Handler,
		},
		{
			MethodName: "GetProgramDetail",
			Handler:    _ProgramRpc_GetProgramDetail_Handler,
		},
		{
			MethodName: "GetProgramPreorder",
			Handler:    _ProgramRpc_GetProgramPreorder_Handler,
		},
		{
			MethodName: "CreateProgramShowTime",
			Handler:    _ProgramRpc_CreateProgramShowTime_Handler,
		},
		{
			MethodName: "UpdateProgramShowTime",
			Handler:    _ProgramRpc_UpdateProgramShowTime_Handler,
		},
		{
			MethodName: "CreateTicketCategory",
			Handler:    _ProgramRpc_CreateTicketCategory_Handler,
		},
		{
			MethodName: "GetTicketCategoryDetail",
			Handler:    _ProgramRpc_GetTicketCategoryDetail_Handler,
		},
		{
			MethodName: "ListTicketCategoriesByProgram",
			Handler:    _ProgramRpc_ListTicketCategoriesByProgram_Handler,
		},
		{
			MethodName: "CreateSeat",
			Handler:    _ProgramRpc_CreateSeat_Handler,
		},
		{
			MethodName: "BatchCreateSeats",
			Handler:    _ProgramRpc_BatchCreateSeats_Handler,
		},
		{
			MethodName: "GetSeatRelateInfo",
			Handler:    _ProgramRpc_GetSeatRelateInfo_Handler,
		},
		{
			MethodName: "AutoAssignAndFreezeSeats",
			Handler:    _ProgramRpc_AutoAssignAndFreezeSeats_Handler,
		},
		{
			MethodName: "ReleaseSeatFreeze",
			Handler:    _ProgramRpc_ReleaseSeatFreeze_Handler,
		},
		{
			MethodName: "ConfirmSeatFreeze",
			Handler:    _ProgramRpc_ConfirmSeatFreeze_Handler,
		},
		{
			MethodName: "EvaluateRefundRule",
			Handler:    _ProgramRpc_EvaluateRefundRule_Handler,
		},
		{
			MethodName: "ReleaseSoldSeats",
			Handler:    _ProgramRpc_ReleaseSoldSeats_Handler,
		},
		{
			MethodName: "PrimeSeatLedger",
			Handler:    _ProgramRpc_PrimeSeatLedger_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "program.proto",
}
