// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.4
// source: services/program-rpc/program.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProgramRpc_ListProgramCategories_FullMethodName         = "/program.ProgramRpc/ListProgramCategories"
	ProgramRpc_ListHomePrograms_FullMethodName              = "/program.ProgramRpc/ListHomePrograms"
	ProgramRpc_PagePrograms_FullMethodName                  = "/program.ProgramRpc/PagePrograms"
	ProgramRpc_GetProgramDetail_FullMethodName              = "/program.ProgramRpc/GetProgramDetail"
	ProgramRpc_ListTicketCategoriesByProgram_FullMethodName = "/program.ProgramRpc/ListTicketCategoriesByProgram"
)

// ProgramRpcClient is the client API for ProgramRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProgramRpcClient interface {
	ListProgramCategories(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProgramCategoryListResp, error)
	ListHomePrograms(ctx context.Context, in *ListHomeProgramsReq, opts ...grpc.CallOption) (*ProgramHomeListResp, error)
	PagePrograms(ctx context.Context, in *PageProgramsReq, opts ...grpc.CallOption) (*ProgramPageResp, error)
	GetProgramDetail(ctx context.Context, in *GetProgramDetailReq, opts ...grpc.CallOption) (*ProgramDetailInfo, error)
	ListTicketCategoriesByProgram(ctx context.Context, in *ListTicketCategoriesByProgramReq, opts ...grpc.CallOption) (*TicketCategoryDetailListResp, error)
}

type programRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewProgramRpcClient(cc grpc.ClientConnInterface) ProgramRpcClient {
	return &programRpcClient{cc}
}

func (c *programRpcClient) ListProgramCategories(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ProgramCategoryListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgramCategoryListResp)
	err := c.cc.Invoke(ctx, ProgramRpc_ListProgramCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) ListHomePrograms(ctx context.Context, in *ListHomeProgramsReq, opts ...grpc.CallOption) (*ProgramHomeListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgramHomeListResp)
	err := c.cc.Invoke(ctx, ProgramRpc_ListHomePrograms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) PagePrograms(ctx context.Context, in *PageProgramsReq, opts ...grpc.CallOption) (*ProgramPageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgramPageResp)
	err := c.cc.Invoke(ctx, ProgramRpc_PagePrograms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) GetProgramDetail(ctx context.Context, in *GetProgramDetailReq, opts ...grpc.CallOption) (*ProgramDetailInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProgramDetailInfo)
	err := c.cc.Invoke(ctx, ProgramRpc_GetProgramDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *programRpcClient) ListTicketCategoriesByProgram(ctx context.Context, in *ListTicketCategoriesByProgramReq, opts ...grpc.CallOption) (*TicketCategoryDetailListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TicketCategoryDetailListResp)
	err := c.cc.Invoke(ctx, ProgramRpc_ListTicketCategoriesByProgram_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProgramRpcServer is the server API for ProgramRpc service.
// All implementations must embed UnimplementedProgramRpcServer
// for forward compatibility.
type ProgramRpcServer interface {
	ListProgramCategories(context.Context, *Empty) (*ProgramCategoryListResp, error)
	ListHomePrograms(context.Context, *ListHomeProgramsReq) (*ProgramHomeListResp, error)
	PagePrograms(context.Context, *PageProgramsReq) (*ProgramPageResp, error)
	GetProgramDetail(context.Context, *GetProgramDetailReq) (*ProgramDetailInfo, error)
	ListTicketCategoriesByProgram(context.Context, *ListTicketCategoriesByProgramReq) (*TicketCategoryDetailListResp, error)
	mustEmbedUnimplementedProgramRpcServer()
}

// UnimplementedProgramRpcServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProgramRpcServer struct{}

func (UnimplementedProgramRpcServer) ListProgramCategories(context.Context, *Empty) (*ProgramCategoryListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListProgramCategories not implemented")
}
func (UnimplementedProgramRpcServer) ListHomePrograms(context.Context, *ListHomeProgramsReq) (*ProgramHomeListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListHomePrograms not implemented")
}
func (UnimplementedProgramRpcServer) PagePrograms(context.Context, *PageProgramsReq) (*ProgramPageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PagePrograms not implemented")
}
func (UnimplementedProgramRpcServer) GetProgramDetail(context.Context, *GetProgramDetailReq) (*ProgramDetailInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProgramDetail not implemented")
}
func (UnimplementedProgramRpcServer) ListTicketCategoriesByProgram(context.Context, *ListTicketCategoriesByProgramReq) (*TicketCategoryDetailListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTicketCategoriesByProgram not implemented")
}
func (UnimplementedProgramRpcServer) mustEmbedUnimplementedProgramRpcServer() {}
func (UnimplementedProgramRpcServer) testEmbeddedByValue()                    {}

// UnsafeProgramRpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProgramRpcServer will
// result in compilation errors.
type UnsafeProgramRpcServer interface {
	mustEmbedUnimplementedProgramRpcServer()
}

func RegisterProgramRpcServer(s grpc.ServiceRegistrar, srv ProgramRpcServer) {
	// If the following call panics, it indicates UnimplementedProgramRpcServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProgramRpc_ServiceDesc, srv)
}

func _ProgramRpc_ListProgramCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).ListProgramCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_ListProgramCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).ListProgramCategories(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_ListHomePrograms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListHomeProgramsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).ListHomePrograms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_ListHomePrograms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).ListHomePrograms(ctx, req.(*ListHomeProgramsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_PagePrograms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageProgramsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).PagePrograms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_PagePrograms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).PagePrograms(ctx, req.(*PageProgramsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_GetProgramDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProgramDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).GetProgramDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_GetProgramDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).GetProgramDetail(ctx, req.(*GetProgramDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProgramRpc_ListTicketCategoriesByProgram_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTicketCategoriesByProgramReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProgramRpcServer).ListTicketCategoriesByProgram(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProgramRpc_ListTicketCategoriesByProgram_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProgramRpcServer).ListTicketCategoriesByProgram(ctx, req.(*ListTicketCategoriesByProgramReq))
	}
	return interceptor(ctx, in, info, handler)
}

// ProgramRpc_ServiceDesc is the grpc.ServiceDesc for ProgramRpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProgramRpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "program.ProgramRpc",
	HandlerType: (*ProgramRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListProgramCategories",
			Handler:    _ProgramRpc_ListProgramCategories_Handler,
		},
		{
			MethodName: "ListHomePrograms",
			Handler:    _ProgramRpc_ListHomePrograms_Handler,
		},
		{
			MethodName: "PagePrograms",
			Handler:    _ProgramRpc_PagePrograms_Handler,
		},
		{
			MethodName: "GetProgramDetail",
			Handler:    _ProgramRpc_GetProgramDetail_Handler,
		},
		{
			MethodName: "ListTicketCategoriesByProgram",
			Handler:    _ProgramRpc_ListTicketCategoriesByProgram_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/program-rpc/program.proto",
}
