// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: services/program-rpc/program.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_services_program_rpc_program_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{0}
}

type ListHomeProgramsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Channel       string                 `protobuf:"bytes,1,opt,name=channel,proto3" json:"channel,omitempty"`
	CityCode      string                 `protobuf:"bytes,2,opt,name=cityCode,proto3" json:"cityCode,omitempty"`
	PageNo        int64                  `protobuf:"varint,3,opt,name=pageNo,proto3" json:"pageNo,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHomeProgramsReq) Reset() {
	*x = ListHomeProgramsReq{}
	mi := &file_services_program_rpc_program_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHomeProgramsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHomeProgramsReq) ProtoMessage() {}

func (x *ListHomeProgramsReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHomeProgramsReq.ProtoReflect.Descriptor instead.
func (*ListHomeProgramsReq) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{1}
}

func (x *ListHomeProgramsReq) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *ListHomeProgramsReq) GetCityCode() string {
	if x != nil {
		return x.CityCode
	}
	return ""
}

func (x *ListHomeProgramsReq) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *ListHomeProgramsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PageProgramsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    int64                  `protobuf:"varint,1,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	CityCode      string                 `protobuf:"bytes,2,opt,name=cityCode,proto3" json:"cityCode,omitempty"`
	Keyword       string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	PageNo        int64                  `protobuf:"varint,4,opt,name=pageNo,proto3" json:"pageNo,omitempty"`
	PageSize      int64                  `protobuf:"varint,5,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	SortType      string                 `protobuf:"bytes,6,opt,name=sortType,proto3" json:"sortType,omitempty"`
	StartTime     int64                  `protobuf:"varint,7,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       int64                  `protobuf:"varint,8,opt,name=endTime,proto3" json:"endTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageProgramsReq) Reset() {
	*x = PageProgramsReq{}
	mi := &file_services_program_rpc_program_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageProgramsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageProgramsReq) ProtoMessage() {}

func (x *PageProgramsReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageProgramsReq.ProtoReflect.Descriptor instead.
func (*PageProgramsReq) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{2}
}

func (x *PageProgramsReq) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *PageProgramsReq) GetCityCode() string {
	if x != nil {
		return x.CityCode
	}
	return ""
}

func (x *PageProgramsReq) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *PageProgramsReq) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *PageProgramsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageProgramsReq) GetSortType() string {
	if x != nil {
		return x.SortType
	}
	return ""
}

func (x *PageProgramsReq) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *PageProgramsReq) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type GetProgramDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramId     int64                  `protobuf:"varint,1,opt,name=programId,proto3" json:"programId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgramDetailReq) Reset() {
	*x = GetProgramDetailReq{}
	mi := &file_services_program_rpc_program_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgramDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgramDetailReq) ProtoMessage() {}

func (x *GetProgramDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgramDetailReq.ProtoReflect.Descriptor instead.
func (*GetProgramDetailReq) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{3}
}

func (x *GetProgramDetailReq) GetProgramId() int64 {
	if x != nil {
		return x.ProgramId
	}
	return 0
}

type ListTicketCategoriesByProgramReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramId     int64                  `protobuf:"varint,1,opt,name=programId,proto3" json:"programId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketCategoriesByProgramReq) Reset() {
	*x = ListTicketCategoriesByProgramReq{}
	mi := &file_services_program_rpc_program_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketCategoriesByProgramReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketCategoriesByProgramReq) ProtoMessage() {}

func (x *ListTicketCategoriesByProgramReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketCategoriesByProgramReq.ProtoReflect.Descriptor instead.
func (*ListTicketCategoriesByProgramReq) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{4}
}

func (x *ListTicketCategoriesByProgramReq) GetProgramId() int64 {
	if x != nil {
		return x.ProgramId
	}
	return 0
}

type ProgramCategoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Background    string                 `protobuf:"bytes,5,opt,name=background,proto3" json:"background,omitempty"`
	Sort          int64                  `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	ProgramCount  int64                  `protobuf:"varint,7,opt,name=programCount,proto3" json:"programCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramCategoryInfo) Reset() {
	*x = ProgramCategoryInfo{}
	mi := &file_services_program_rpc_program_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramCategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramCategoryInfo) ProtoMessage() {}

func (x *ProgramCategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramCategoryInfo.ProtoReflect.Descriptor instead.
func (*ProgramCategoryInfo) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{5}
}

func (x *ProgramCategoryInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProgramCategoryInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProgramCategoryInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ProgramCategoryInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *ProgramCategoryInfo) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

func (x *ProgramCategoryInfo) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *ProgramCategoryInfo) GetProgramCount() int64 {
	if x != nil {
		return x.ProgramCount
	}
	return 0
}

type ProgramSimpleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle      string                 `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Poster        string                 `protobuf:"bytes,4,opt,name=poster,proto3" json:"poster,omitempty"`
	CityCode      string                 `protobuf:"bytes,5,opt,name=cityCode,proto3" json:"cityCode,omitempty"`
	CityName      string                 `protobuf:"bytes,6,opt,name=cityName,proto3" json:"cityName,omitempty"`
	CategoryId    int64                  `protobuf:"varint,7,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	CategoryName  string                 `protobuf:"bytes,8,opt,name=categoryName,proto3" json:"categoryName,omitempty"`
	VenueId       int64                  `protobuf:"varint,9,opt,name=venueId,proto3" json:"venueId,omitempty"`
	VenueName     string                 `protobuf:"bytes,10,opt,name=venueName,proto3" json:"venueName,omitempty"`
	VenueAddress  string                 `protobuf:"bytes,11,opt,name=venueAddress,proto3" json:"venueAddress,omitempty"`
	MinPrice      int64                  `protobuf:"varint,12,opt,name=minPrice,proto3" json:"minPrice,omitempty"`
	MaxPrice      int64                  `protobuf:"varint,13,opt,name=maxPrice,proto3" json:"maxPrice,omitempty"`
	SaleStatus    int64                  `protobuf:"varint,14,opt,name=saleStatus,proto3" json:"saleStatus,omitempty"`
	SaleStartTime int64                  `protobuf:"varint,15,opt,name=saleStartTime,proto3" json:"saleStartTime,omitempty"`
	SaleEndTime   int64                  `protobuf:"varint,16,opt,name=saleEndTime,proto3" json:"saleEndTime,omitempty"`
	ShowStartTime int64                  `protobuf:"varint,17,opt,name=showStartTime,proto3" json:"showStartTime,omitempty"`
	ShowEndTime   int64                  `protobuf:"varint,18,opt,name=showEndTime,proto3" json:"showEndTime,omitempty"`
	Tags          []string               `protobuf:"bytes,19,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramSimpleInfo) Reset() {
	*x = ProgramSimpleInfo{}
	mi := &file_services_program_rpc_program_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramSimpleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramSimpleInfo) ProtoMessage() {}

func (x *ProgramSimpleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramSimpleInfo.ProtoReflect.Descriptor instead.
func (*ProgramSimpleInfo) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{6}
}

func (x *ProgramSimpleInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProgramSimpleInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProgramSimpleInfo) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *ProgramSimpleInfo) GetPoster() string {
	if x != nil {
		return x.Poster
	}
	return ""
}

func (x *ProgramSimpleInfo) GetCityCode() string {
	if x != nil {
		return x.CityCode
	}
	return ""
}

func (x *ProgramSimpleInfo) GetCityName() string {
	if x != nil {
		return x.CityName
	}
	return ""
}

func (x *ProgramSimpleInfo) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ProgramSimpleInfo) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *ProgramSimpleInfo) GetVenueId() int64 {
	if x != nil {
		return x.VenueId
	}
	return 0
}

func (x *ProgramSimpleInfo) GetVenueName() string {
	if x != nil {
		return x.VenueName
	}
	return ""
}

func (x *ProgramSimpleInfo) GetVenueAddress() string {
	if x != nil {
		return x.VenueAddress
	}
	return ""
}

func (x *ProgramSimpleInfo) GetMinPrice() int64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *ProgramSimpleInfo) GetMaxPrice() int64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *ProgramSimpleInfo) GetSaleStatus() int64 {
	if x != nil {
		return x.SaleStatus
	}
	return 0
}

func (x *ProgramSimpleInfo) GetSaleStartTime() int64 {
	if x != nil {
		return x.SaleStartTime
	}
	return 0
}

func (x *ProgramSimpleInfo) GetSaleEndTime() int64 {
	if x != nil {
		return x.SaleEndTime
	}
	return 0
}

func (x *ProgramSimpleInfo) GetShowStartTime() int64 {
	if x != nil {
		return x.ShowStartTime
	}
	return 0
}

func (x *ProgramSimpleInfo) GetShowEndTime() int64 {
	if x != nil {
		return x.ShowEndTime
	}
	return 0
}

func (x *ProgramSimpleInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type ProgramGroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Subtitle      string                 `protobuf:"bytes,4,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Programs      []*ProgramSimpleInfo   `protobuf:"bytes,5,rep,name=programs,proto3" json:"programs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramGroupInfo) Reset() {
	*x = ProgramGroupInfo{}
	mi := &file_services_program_rpc_program_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramGroupInfo) ProtoMessage() {}

func (x *ProgramGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramGroupInfo.ProtoReflect.Descriptor instead.
func (*ProgramGroupInfo) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{7}
}

func (x *ProgramGroupInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProgramGroupInfo) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ProgramGroupInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProgramGroupInfo) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *ProgramGroupInfo) GetPrograms() []*ProgramSimpleInfo {
	if x != nil {
		return x.Programs
	}
	return nil
}

type ProgramHomeSection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	SectionType   string                 `protobuf:"bytes,2,opt,name=sectionType,proto3" json:"sectionType,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle      string                 `protobuf:"bytes,4,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Cover         string                 `protobuf:"bytes,5,opt,name=cover,proto3" json:"cover,omitempty"`
	Sort          int64                  `protobuf:"varint,6,opt,name=sort,proto3" json:"sort,omitempty"`
	Programs      []*ProgramSimpleInfo   `protobuf:"bytes,7,rep,name=programs,proto3" json:"programs,omitempty"`
	Groups        []*ProgramGroupInfo    `protobuf:"bytes,8,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramHomeSection) Reset() {
	*x = ProgramHomeSection{}
	mi := &file_services_program_rpc_program_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramHomeSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramHomeSection) ProtoMessage() {}

func (x *ProgramHomeSection) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramHomeSection.ProtoReflect.Descriptor instead.
func (*ProgramHomeSection) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{8}
}

func (x *ProgramHomeSection) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProgramHomeSection) GetSectionType() string {
	if x != nil {
		return x.SectionType
	}
	return ""
}

func (x *ProgramHomeSection) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProgramHomeSection) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *ProgramHomeSection) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *ProgramHomeSection) GetSort() int64 {
	if x != nil {
		return x.Sort
	}
	return 0
}

func (x *ProgramHomeSection) GetPrograms() []*ProgramSimpleInfo {
	if x != nil {
		return x.Programs
	}
	return nil
}

func (x *ProgramHomeSection) GetGroups() []*ProgramGroupInfo {
	if x != nil {
		return x.Groups
	}
	return nil
}

type TicketCategoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProgramId     int64                  `protobuf:"varint,2,opt,name=programId,proto3" json:"programId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Inventory     int64                  `protobuf:"varint,5,opt,name=inventory,proto3" json:"inventory,omitempty"`
	Sold          int64                  `protobuf:"varint,6,opt,name=sold,proto3" json:"sold,omitempty"`
	Status        int64                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketCategoryInfo) Reset() {
	*x = TicketCategoryInfo{}
	mi := &file_services_program_rpc_program_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketCategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketCategoryInfo) ProtoMessage() {}

func (x *TicketCategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketCategoryInfo.ProtoReflect.Descriptor instead.
func (*TicketCategoryInfo) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{9}
}

func (x *TicketCategoryInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TicketCategoryInfo) GetProgramId() int64 {
	if x != nil {
		return x.ProgramId
	}
	return 0
}

func (x *TicketCategoryInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TicketCategoryInfo) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TicketCategoryInfo) GetInventory() int64 {
	if x != nil {
		return x.Inventory
	}
	return 0
}

func (x *TicketCategoryInfo) GetSold() int64 {
	if x != nil {
		return x.Sold
	}
	return 0
}

func (x *TicketCategoryInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

type TicketCategoryDetailInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProgramId     int64                  `protobuf:"varint,2,opt,name=programId,proto3" json:"programId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Price         int64                  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	Inventory     int64                  `protobuf:"varint,5,opt,name=inventory,proto3" json:"inventory,omitempty"`
	Sold          int64                  `protobuf:"varint,6,opt,name=sold,proto3" json:"sold,omitempty"`
	Status        int64                  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	SeatDesc      string                 `protobuf:"bytes,8,opt,name=seatDesc,proto3" json:"seatDesc,omitempty"`
	SaleRule      string                 `protobuf:"bytes,9,opt,name=saleRule,proto3" json:"saleRule,omitempty"`
	RefundRule    string                 `protobuf:"bytes,10,opt,name=refundRule,proto3" json:"refundRule,omitempty"`
	SaleStartTime int64                  `protobuf:"varint,11,opt,name=saleStartTime,proto3" json:"saleStartTime,omitempty"`
	SaleEndTime   int64                  `protobuf:"varint,12,opt,name=saleEndTime,proto3" json:"saleEndTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketCategoryDetailInfo) Reset() {
	*x = TicketCategoryDetailInfo{}
	mi := &file_services_program_rpc_program_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketCategoryDetailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketCategoryDetailInfo) ProtoMessage() {}

func (x *TicketCategoryDetailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketCategoryDetailInfo.ProtoReflect.Descriptor instead.
func (*TicketCategoryDetailInfo) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{10}
}

func (x *TicketCategoryDetailInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TicketCategoryDetailInfo) GetProgramId() int64 {
	if x != nil {
		return x.ProgramId
	}
	return 0
}

func (x *TicketCategoryDetailInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TicketCategoryDetailInfo) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TicketCategoryDetailInfo) GetInventory() int64 {
	if x != nil {
		return x.Inventory
	}
	return 0
}

func (x *TicketCategoryDetailInfo) GetSold() int64 {
	if x != nil {
		return x.Sold
	}
	return 0
}

func (x *TicketCategoryDetailInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TicketCategoryDetailInfo) GetSeatDesc() string {
	if x != nil {
		return x.SeatDesc
	}
	return ""
}

func (x *TicketCategoryDetailInfo) GetSaleRule() string {
	if x != nil {
		return x.SaleRule
	}
	return ""
}

func (x *TicketCategoryDetailInfo) GetRefundRule() string {
	if x != nil {
		return x.RefundRule
	}
	return ""
}

func (x *TicketCategoryDetailInfo) GetSaleStartTime() int64 {
	if x != nil {
		return x.SaleStartTime
	}
	return 0
}

func (x *TicketCategoryDetailInfo) GetSaleEndTime() int64 {
	if x != nil {
		return x.SaleEndTime
	}
	return 0
}

type ProgramCategoryListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ProgramCategoryInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramCategoryListResp) Reset() {
	*x = ProgramCategoryListResp{}
	mi := &file_services_program_rpc_program_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramCategoryListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramCategoryListResp) ProtoMessage() {}

func (x *ProgramCategoryListResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramCategoryListResp.ProtoReflect.Descriptor instead.
func (*ProgramCategoryListResp) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{11}
}

func (x *ProgramCategoryListResp) GetList() []*ProgramCategoryInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type ProgramListInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int64                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	PageNo        int64                  `protobuf:"varint,2,opt,name=pageNo,proto3" json:"pageNo,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	HasMore       bool                   `protobuf:"varint,4,opt,name=hasMore,proto3" json:"hasMore,omitempty"`
	List          []*ProgramSimpleInfo   `protobuf:"bytes,5,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramListInfo) Reset() {
	*x = ProgramListInfo{}
	mi := &file_services_program_rpc_program_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramListInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramListInfo) ProtoMessage() {}

func (x *ProgramListInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramListInfo.ProtoReflect.Descriptor instead.
func (*ProgramListInfo) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{12}
}

func (x *ProgramListInfo) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ProgramListInfo) GetPageNo() int64 {
	if x != nil {
		return x.PageNo
	}
	return 0
}

func (x *ProgramListInfo) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ProgramListInfo) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ProgramListInfo) GetList() []*ProgramSimpleInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type ProgramHomeListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sections      []*ProgramHomeSection  `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramHomeListResp) Reset() {
	*x = ProgramHomeListResp{}
	mi := &file_services_program_rpc_program_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramHomeListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramHomeListResp) ProtoMessage() {}

func (x *ProgramHomeListResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramHomeListResp.ProtoReflect.Descriptor instead.
func (*ProgramHomeListResp) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{13}
}

func (x *ProgramHomeListResp) GetSections() []*ProgramHomeSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

type ProgramPageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          *ProgramListInfo       `protobuf:"bytes,1,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramPageResp) Reset() {
	*x = ProgramPageResp{}
	mi := &file_services_program_rpc_program_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramPageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramPageResp) ProtoMessage() {}

func (x *ProgramPageResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramPageResp.ProtoReflect.Descriptor instead.
func (*ProgramPageResp) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{14}
}

func (x *ProgramPageResp) GetPage() *ProgramListInfo {
	if x != nil {
		return x.Page
	}
	return nil
}

type TicketCategoryDetailListResp struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	List          []*TicketCategoryDetailInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketCategoryDetailListResp) Reset() {
	*x = TicketCategoryDetailListResp{}
	mi := &file_services_program_rpc_program_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketCategoryDetailListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketCategoryDetailListResp) ProtoMessage() {}

func (x *TicketCategoryDetailListResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketCategoryDetailListResp.ProtoReflect.Descriptor instead.
func (*TicketCategoryDetailListResp) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{15}
}

func (x *TicketCategoryDetailListResp) GetList() []*TicketCategoryDetailInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type ProgramDetailInfo struct {
	state              protoimpl.MessageState      `protogen:"open.v1"`
	Id                 int64                       `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title              string                      `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Subtitle           string                      `protobuf:"bytes,3,opt,name=subtitle,proto3" json:"subtitle,omitempty"`
	Brief              string                      `protobuf:"bytes,4,opt,name=brief,proto3" json:"brief,omitempty"`
	Description        string                      `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Poster             string                      `protobuf:"bytes,6,opt,name=poster,proto3" json:"poster,omitempty"`
	Cover              string                      `protobuf:"bytes,7,opt,name=cover,proto3" json:"cover,omitempty"`
	Background         string                      `protobuf:"bytes,8,opt,name=background,proto3" json:"background,omitempty"`
	CityCode           string                      `protobuf:"bytes,9,opt,name=cityCode,proto3" json:"cityCode,omitempty"`
	CityName           string                      `protobuf:"bytes,10,opt,name=cityName,proto3" json:"cityName,omitempty"`
	CategoryId         int64                       `protobuf:"varint,11,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	CategoryName       string                      `protobuf:"bytes,12,opt,name=categoryName,proto3" json:"categoryName,omitempty"`
	VenueId            int64                       `protobuf:"varint,13,opt,name=venueId,proto3" json:"venueId,omitempty"`
	VenueName          string                      `protobuf:"bytes,14,opt,name=venueName,proto3" json:"venueName,omitempty"`
	VenueAddress       string                      `protobuf:"bytes,15,opt,name=venueAddress,proto3" json:"venueAddress,omitempty"`
	Longitude          string                      `protobuf:"bytes,16,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Latitude           string                      `protobuf:"bytes,17,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Status             int64                       `protobuf:"varint,18,opt,name=status,proto3" json:"status,omitempty"`
	AuditStatus        int64                       `protobuf:"varint,19,opt,name=auditStatus,proto3" json:"auditStatus,omitempty"`
	SaleStatus         int64                       `protobuf:"varint,20,opt,name=saleStatus,proto3" json:"saleStatus,omitempty"`
	OnlineTime         int64                       `protobuf:"varint,21,opt,name=onlineTime,proto3" json:"onlineTime,omitempty"`
	OfflineTime        int64                       `protobuf:"varint,22,opt,name=offlineTime,proto3" json:"offlineTime,omitempty"`
	ShowStartTime      int64                       `protobuf:"varint,23,opt,name=showStartTime,proto3" json:"showStartTime,omitempty"`
	ShowEndTime        int64                       `protobuf:"varint,24,opt,name=showEndTime,proto3" json:"showEndTime,omitempty"`
	SaleStartTime      int64                       `protobuf:"varint,25,opt,name=saleStartTime,proto3" json:"saleStartTime,omitempty"`
	SaleEndTime        int64                       `protobuf:"varint,26,opt,name=saleEndTime,proto3" json:"saleEndTime,omitempty"`
	MinPrice           int64                       `protobuf:"varint,27,opt,name=minPrice,proto3" json:"minPrice,omitempty"`
	MaxPrice           int64                       `protobuf:"varint,28,opt,name=maxPrice,proto3" json:"maxPrice,omitempty"`
	InventoryTotal     int64                       `protobuf:"varint,29,opt,name=inventoryTotal,proto3" json:"inventoryTotal,omitempty"`
	SoldCount          int64                       `protobuf:"varint,30,opt,name=soldCount,proto3" json:"soldCount,omitempty"`
	WantCount          int64                       `protobuf:"varint,31,opt,name=wantCount,proto3" json:"wantCount,omitempty"`
	ViewCount          int64                       `protobuf:"varint,32,opt,name=viewCount,proto3" json:"viewCount,omitempty"`
	Tags               []string                    `protobuf:"bytes,33,rep,name=tags,proto3" json:"tags,omitempty"`
	ImageUrls          []string                    `protobuf:"bytes,34,rep,name=imageUrls,proto3" json:"imageUrls,omitempty"`
	IntroduceHtml      string                      `protobuf:"bytes,35,opt,name=introduceHtml,proto3" json:"introduceHtml,omitempty"`
	Notice             string                      `protobuf:"bytes,36,opt,name=notice,proto3" json:"notice,omitempty"`
	RefundRule         string                      `protobuf:"bytes,37,opt,name=refundRule,proto3" json:"refundRule,omitempty"`
	RealNameRule       string                      `protobuf:"bytes,38,opt,name=realNameRule,proto3" json:"realNameRule,omitempty"`
	TicketCategoryList []*TicketCategoryDetailInfo `protobuf:"bytes,39,rep,name=ticketCategoryList,proto3" json:"ticketCategoryList,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ProgramDetailInfo) Reset() {
	*x = ProgramDetailInfo{}
	mi := &file_services_program_rpc_program_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramDetailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramDetailInfo) ProtoMessage() {}

func (x *ProgramDetailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramDetailInfo.ProtoReflect.Descriptor instead.
func (*ProgramDetailInfo) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{16}
}

func (x *ProgramDetailInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProgramDetailInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProgramDetailInfo) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *ProgramDetailInfo) GetBrief() string {
	if x != nil {
		return x.Brief
	}
	return ""
}

func (x *ProgramDetailInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ProgramDetailInfo) GetPoster() string {
	if x != nil {
		return x.Poster
	}
	return ""
}

func (x *ProgramDetailInfo) GetCover() string {
	if x != nil {
		return x.Cover
	}
	return ""
}

func (x *ProgramDetailInfo) GetBackground() string {
	if x != nil {
		return x.Background
	}
	return ""
}

func (x *ProgramDetailInfo) GetCityCode() string {
	if x != nil {
		return x.CityCode
	}
	return ""
}

func (x *ProgramDetailInfo) GetCityName() string {
	if x != nil {
		return x.CityName
	}
	return ""
}

func (x *ProgramDetailInfo) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ProgramDetailInfo) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *ProgramDetailInfo) GetVenueId() int64 {
	if x != nil {
		return x.VenueId
	}
	return 0
}

func (x *ProgramDetailInfo) GetVenueName() string {
	if x != nil {
		return x.VenueName
	}
	return ""
}

func (x *ProgramDetailInfo) GetVenueAddress() string {
	if x != nil {
		return x.VenueAddress
	}
	return ""
}

func (x *ProgramDetailInfo) GetLongitude() string {
	if x != nil {
		return x.Longitude
	}
	return ""
}

func (x *ProgramDetailInfo) GetLatitude() string {
	if x != nil {
		return x.Latitude
	}
	return ""
}

func (x *ProgramDetailInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ProgramDetailInfo) GetAuditStatus() int64 {
	if x != nil {
		return x.AuditStatus
	}
	return 0
}

func (x *ProgramDetailInfo) GetSaleStatus() int64 {
	if x != nil {
		return x.SaleStatus
	}
	return 0
}

func (x *ProgramDetailInfo) GetOnlineTime() int64 {
	if x != nil {
		return x.OnlineTime
	}
	return 0
}

func (x *ProgramDetailInfo) GetOfflineTime() int64 {
	if x != nil {
		return x.OfflineTime
	}
	return 0
}

func (x *ProgramDetailInfo) GetShowStartTime() int64 {
	if x != nil {
		return x.ShowStartTime
	}
	return 0
}

func (x *ProgramDetailInfo) GetShowEndTime() int64 {
	if x != nil {
		return x.ShowEndTime
	}
	return 0
}

func (x *ProgramDetailInfo) GetSaleStartTime() int64 {
	if x != nil {
		return x.SaleStartTime
	}
	return 0
}

func (x *ProgramDetailInfo) GetSaleEndTime() int64 {
	if x != nil {
		return x.SaleEndTime
	}
	return 0
}

func (x *ProgramDetailInfo) GetMinPrice() int64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *ProgramDetailInfo) GetMaxPrice() int64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *ProgramDetailInfo) GetInventoryTotal() int64 {
	if x != nil {
		return x.InventoryTotal
	}
	return 0
}

func (x *ProgramDetailInfo) GetSoldCount() int64 {
	if x != nil {
		return x.SoldCount
	}
	return 0
}

func (x *ProgramDetailInfo) GetWantCount() int64 {
	if x != nil {
		return x.WantCount
	}
	return 0
}

func (x *ProgramDetailInfo) GetViewCount() int64 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *ProgramDetailInfo) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ProgramDetailInfo) GetImageUrls() []string {
	if x != nil {
		return x.ImageUrls
	}
	return nil
}

func (x *ProgramDetailInfo) GetIntroduceHtml() string {
	if x != nil {
		return x.IntroduceHtml
	}
	return ""
}

func (x *ProgramDetailInfo) GetNotice() string {
	if x != nil {
		return x.Notice
	}
	return ""
}

func (x *ProgramDetailInfo) GetRefundRule() string {
	if x != nil {
		return x.RefundRule
	}
	return ""
}

func (x *ProgramDetailInfo) GetRealNameRule() string {
	if x != nil {
		return x.RealNameRule
	}
	return ""
}

func (x *ProgramDetailInfo) GetTicketCategoryList() []*TicketCategoryDetailInfo {
	if x != nil {
		return x.TicketCategoryList
	}
	return nil
}

var File_services_program_rpc_program_proto protoreflect.FileDescriptor

const file_services_program_rpc_program_proto_rawDesc = "" +
	"\n" +
	"\"services/program-rpc/program.proto\x12\aprogram\"\a\n" +
	"\x05Empty\"\x7f\n" +
	"\x13ListHomeProgramsReq\x12\x18\n" +
	"\achannel\x18\x01 \x01(\tR\achannel\x12\x1a\n" +
	"\bcityCode\x18\x02 \x01(\tR\bcityCode\x12\x16\n" +
	"\x06pageNo\x18\x03 \x01(\x03R\x06pageNo\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\"\xef\x01\n" +
	"\x0fPageProgramsReq\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x01 \x01(\x03R\n" +
	"categoryId\x12\x1a\n" +
	"\bcityCode\x18\x02 \x01(\tR\bcityCode\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12\x16\n" +
	"\x06pageNo\x18\x04 \x01(\x03R\x06pageNo\x12\x1a\n" +
	"\bpageSize\x18\x05 \x01(\x03R\bpageSize\x12\x1a\n" +
	"\bsortType\x18\x06 \x01(\tR\bsortType\x12\x1c\n" +
	"\tstartTime\x18\a \x01(\x03R\tstartTime\x12\x18\n" +
	"\aendTime\x18\b \x01(\x03R\aendTime\"3\n" +
	"\x13GetProgramDetailReq\x12\x1c\n" +
	"\tprogramId\x18\x01 \x01(\x03R\tprogramId\"@\n" +
	" ListTicketCategoriesByProgramReq\x12\x1c\n" +
	"\tprogramId\x18\x01 \x01(\x03R\tprogramId\"\xb9\x01\n" +
	"\x13ProgramCategoryInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x1e\n" +
	"\n" +
	"background\x18\x05 \x01(\tR\n" +
	"background\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\x03R\x04sort\x12\"\n" +
	"\fprogramCount\x18\a \x01(\x03R\fprogramCount\"\xc1\x04\n" +
	"\x11ProgramSimpleInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bsubtitle\x18\x03 \x01(\tR\bsubtitle\x12\x16\n" +
	"\x06poster\x18\x04 \x01(\tR\x06poster\x12\x1a\n" +
	"\bcityCode\x18\x05 \x01(\tR\bcityCode\x12\x1a\n" +
	"\bcityName\x18\x06 \x01(\tR\bcityName\x12\x1e\n" +
	"\n" +
	"categoryId\x18\a \x01(\x03R\n" +
	"categoryId\x12\"\n" +
	"\fcategoryName\x18\b \x01(\tR\fcategoryName\x12\x18\n" +
	"\avenueId\x18\t \x01(\x03R\avenueId\x12\x1c\n" +
	"\tvenueName\x18\n" +
	" \x01(\tR\tvenueName\x12\"\n" +
	"\fvenueAddress\x18\v \x01(\tR\fvenueAddress\x12\x1a\n" +
	"\bminPrice\x18\f \x01(\x03R\bminPrice\x12\x1a\n" +
	"\bmaxPrice\x18\r \x01(\x03R\bmaxPrice\x12\x1e\n" +
	"\n" +
	"saleStatus\x18\x0e \x01(\x03R\n" +
	"saleStatus\x12$\n" +
	"\rsaleStartTime\x18\x0f \x01(\x03R\rsaleStartTime\x12 \n" +
	"\vsaleEndTime\x18\x10 \x01(\x03R\vsaleEndTime\x12$\n" +
	"\rshowStartTime\x18\x11 \x01(\x03R\rshowStartTime\x12 \n" +
	"\vshowEndTime\x18\x12 \x01(\x03R\vshowEndTime\x12\x12\n" +
	"\x04tags\x18\x13 \x03(\tR\x04tags\"\x9e\x01\n" +
	"\x10ProgramGroupInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bsubtitle\x18\x04 \x01(\tR\bsubtitle\x126\n" +
	"\bprograms\x18\x05 \x03(\v2\x1a.program.ProgramSimpleInfoR\bprograms\"\x8d\x02\n" +
	"\x12ProgramHomeSection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12 \n" +
	"\vsectionType\x18\x02 \x01(\tR\vsectionType\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x1a\n" +
	"\bsubtitle\x18\x04 \x01(\tR\bsubtitle\x12\x14\n" +
	"\x05cover\x18\x05 \x01(\tR\x05cover\x12\x12\n" +
	"\x04sort\x18\x06 \x01(\x03R\x04sort\x126\n" +
	"\bprograms\x18\a \x03(\v2\x1a.program.ProgramSimpleInfoR\bprograms\x121\n" +
	"\x06groups\x18\b \x03(\v2\x19.program.ProgramGroupInfoR\x06groups\"\xb6\x01\n" +
	"\x12TicketCategoryInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tprogramId\x18\x02 \x01(\x03R\tprogramId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x1c\n" +
	"\tinventory\x18\x05 \x01(\x03R\tinventory\x12\x12\n" +
	"\x04sold\x18\x06 \x01(\x03R\x04sold\x12\x16\n" +
	"\x06status\x18\a \x01(\x03R\x06status\"\xdc\x02\n" +
	"\x18TicketCategoryDetailInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tprogramId\x18\x02 \x01(\x03R\tprogramId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x03R\x05price\x12\x1c\n" +
	"\tinventory\x18\x05 \x01(\x03R\tinventory\x12\x12\n" +
	"\x04sold\x18\x06 \x01(\x03R\x04sold\x12\x16\n" +
	"\x06status\x18\a \x01(\x03R\x06status\x12\x1a\n" +
	"\bseatDesc\x18\b \x01(\tR\bseatDesc\x12\x1a\n" +
	"\bsaleRule\x18\t \x01(\tR\bsaleRule\x12\x1e\n" +
	"\n" +
	"refundRule\x18\n" +
	" \x01(\tR\n" +
	"refundRule\x12$\n" +
	"\rsaleStartTime\x18\v \x01(\x03R\rsaleStartTime\x12 \n" +
	"\vsaleEndTime\x18\f \x01(\x03R\vsaleEndTime\"K\n" +
	"\x17ProgramCategoryListResp\x120\n" +
	"\x04list\x18\x01 \x03(\v2\x1c.program.ProgramCategoryInfoR\x04list\"\xa5\x01\n" +
	"\x0fProgramListInfo\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x03R\x05total\x12\x16\n" +
	"\x06pageNo\x18\x02 \x01(\x03R\x06pageNo\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\x12\x18\n" +
	"\ahasMore\x18\x04 \x01(\bR\ahasMore\x12.\n" +
	"\x04list\x18\x05 \x03(\v2\x1a.program.ProgramSimpleInfoR\x04list\"N\n" +
	"\x13ProgramHomeListResp\x127\n" +
	"\bsections\x18\x01 \x03(\v2\x1b.program.ProgramHomeSectionR\bsections\"?\n" +
	"\x0fProgramPageResp\x12,\n" +
	"\x04page\x18\x01 \x01(\v2\x18.program.ProgramListInfoR\x04page\"U\n" +
	"\x1cTicketCategoryDetailListResp\x125\n" +
	"\x04list\x18\x01 \x03(\v2!.program.TicketCategoryDetailInfoR\x04list\"\xda\t\n" +
	"\x11ProgramDetailInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1a\n" +
	"\bsubtitle\x18\x03 \x01(\tR\bsubtitle\x12\x14\n" +
	"\x05brief\x18\x04 \x01(\tR\x05brief\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x16\n" +
	"\x06poster\x18\x06 \x01(\tR\x06poster\x12\x14\n" +
	"\x05cover\x18\a \x01(\tR\x05cover\x12\x1e\n" +
	"\n" +
	"background\x18\b \x01(\tR\n" +
	"background\x12\x1a\n" +
	"\bcityCode\x18\t \x01(\tR\bcityCode\x12\x1a\n" +
	"\bcityName\x18\n" +
	" \x01(\tR\bcityName\x12\x1e\n" +
	"\n" +
	"categoryId\x18\v \x01(\x03R\n" +
	"categoryId\x12\"\n" +
	"\fcategoryName\x18\f \x01(\tR\fcategoryName\x12\x18\n" +
	"\avenueId\x18\r \x01(\x03R\avenueId\x12\x1c\n" +
	"\tvenueName\x18\x0e \x01(\tR\tvenueName\x12\"\n" +
	"\fvenueAddress\x18\x0f \x01(\tR\fvenueAddress\x12\x1c\n" +
	"\tlongitude\x18\x10 \x01(\tR\tlongitude\x12\x1a\n" +
	"\blatitude\x18\x11 \x01(\tR\blatitude\x12\x16\n" +
	"\x06status\x18\x12 \x01(\x03R\x06status\x12 \n" +
	"\vauditStatus\x18\x13 \x01(\x03R\vauditStatus\x12\x1e\n" +
	"\n" +
	"saleStatus\x18\x14 \x01(\x03R\n" +
	"saleStatus\x12\x1e\n" +
	"\n" +
	"onlineTime\x18\x15 \x01(\x03R\n" +
	"onlineTime\x12 \n" +
	"\vofflineTime\x18\x16 \x01(\x03R\vofflineTime\x12$\n" +
	"\rshowStartTime\x18\x17 \x01(\x03R\rshowStartTime\x12 \n" +
	"\vshowEndTime\x18\x18 \x01(\x03R\vshowEndTime\x12$\n" +
	"\rsaleStartTime\x18\x19 \x01(\x03R\rsaleStartTime\x12 \n" +
	"\vsaleEndTime\x18\x1a \x01(\x03R\vsaleEndTime\x12\x1a\n" +
	"\bminPrice\x18\x1b \x01(\x03R\bminPrice\x12\x1a\n" +
	"\bmaxPrice\x18\x1c \x01(\x03R\bmaxPrice\x12&\n" +
	"\x0einventoryTotal\x18\x1d \x01(\x03R\x0einventoryTotal\x12\x1c\n" +
	"\tsoldCount\x18\x1e \x01(\x03R\tsoldCount\x12\x1c\n" +
	"\twantCount\x18\x1f \x01(\x03R\twantCount\x12\x1c\n" +
	"\tviewCount\x18  \x01(\x03R\tviewCount\x12\x12\n" +
	"\x04tags\x18! \x03(\tR\x04tags\x12\x1c\n" +
	"\timageUrls\x18\" \x03(\tR\timageUrls\x12$\n" +
	"\rintroduceHtml\x18# \x01(\tR\rintroduceHtml\x12\x16\n" +
	"\x06notice\x18$ \x01(\tR\x06notice\x12\x1e\n" +
	"\n" +
	"refundRule\x18% \x01(\tR\n" +
	"refundRule\x12\"\n" +
	"\frealNameRule\x18& \x01(\tR\frealNameRule\x12Q\n" +
	"\x12ticketCategoryList\x18' \x03(\v2!.program.TicketCategoryDetailInfoR\x12ticketCategoryList2\xac\x03\n" +
	"\n" +
	"ProgramRpc\x12I\n" +
	"\x15ListProgramCategories\x12\x0e.program.Empty\x1a .program.ProgramCategoryListResp\x12N\n" +
	"\x10ListHomePrograms\x12\x1c.program.ListHomeProgramsReq\x1a\x1c.program.ProgramHomeListResp\x12B\n" +
	"\fPagePrograms\x12\x18.program.PageProgramsReq\x1a\x18.program.ProgramPageResp\x12L\n" +
	"\x10GetProgramDetail\x12\x1c.program.GetProgramDetailReq\x1a\x1a.program.ProgramDetailInfo\x12q\n" +
	"\x1dListTicketCategoriesByProgram\x12).program.ListTicketCategoriesByProgramReq\x1a%.program.TicketCategoryDetailListRespB\x06Z\x04./pbb\x06proto3"

var (
	file_services_program_rpc_program_proto_rawDescOnce sync.Once
	file_services_program_rpc_program_proto_rawDescData []byte
)

func file_services_program_rpc_program_proto_rawDescGZIP() []byte {
	file_services_program_rpc_program_proto_rawDescOnce.Do(func() {
		file_services_program_rpc_program_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_program_rpc_program_proto_rawDesc), len(file_services_program_rpc_program_proto_rawDesc)))
	})
	return file_services_program_rpc_program_proto_rawDescData
}

var file_services_program_rpc_program_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_services_program_rpc_program_proto_goTypes = []any{
	(*Empty)(nil),                            // 0: program.Empty
	(*ListHomeProgramsReq)(nil),              // 1: program.ListHomeProgramsReq
	(*PageProgramsReq)(nil),                  // 2: program.PageProgramsReq
	(*GetProgramDetailReq)(nil),              // 3: program.GetProgramDetailReq
	(*ListTicketCategoriesByProgramReq)(nil), // 4: program.ListTicketCategoriesByProgramReq
	(*ProgramCategoryInfo)(nil),              // 5: program.ProgramCategoryInfo
	(*ProgramSimpleInfo)(nil),                // 6: program.ProgramSimpleInfo
	(*ProgramGroupInfo)(nil),                 // 7: program.ProgramGroupInfo
	(*ProgramHomeSection)(nil),               // 8: program.ProgramHomeSection
	(*TicketCategoryInfo)(nil),               // 9: program.TicketCategoryInfo
	(*TicketCategoryDetailInfo)(nil),         // 10: program.TicketCategoryDetailInfo
	(*ProgramCategoryListResp)(nil),          // 11: program.ProgramCategoryListResp
	(*ProgramListInfo)(nil),                  // 12: program.ProgramListInfo
	(*ProgramHomeListResp)(nil),              // 13: program.ProgramHomeListResp
	(*ProgramPageResp)(nil),                  // 14: program.ProgramPageResp
	(*TicketCategoryDetailListResp)(nil),     // 15: program.TicketCategoryDetailListResp
	(*ProgramDetailInfo)(nil),                // 16: program.ProgramDetailInfo
}
var file_services_program_rpc_program_proto_depIdxs = []int32{
	6,  // 0: program.ProgramGroupInfo.programs:type_name -> program.ProgramSimpleInfo
	6,  // 1: program.ProgramHomeSection.programs:type_name -> program.ProgramSimpleInfo
	7,  // 2: program.ProgramHomeSection.groups:type_name -> program.ProgramGroupInfo
	5,  // 3: program.ProgramCategoryListResp.list:type_name -> program.ProgramCategoryInfo
	6,  // 4: program.ProgramListInfo.list:type_name -> program.ProgramSimpleInfo
	8,  // 5: program.ProgramHomeListResp.sections:type_name -> program.ProgramHomeSection
	12, // 6: program.ProgramPageResp.page:type_name -> program.ProgramListInfo
	10, // 7: program.TicketCategoryDetailListResp.list:type_name -> program.TicketCategoryDetailInfo
	10, // 8: program.ProgramDetailInfo.ticketCategoryList:type_name -> program.TicketCategoryDetailInfo
	0,  // 9: program.ProgramRpc.ListProgramCategories:input_type -> program.Empty
	1,  // 10: program.ProgramRpc.ListHomePrograms:input_type -> program.ListHomeProgramsReq
	2,  // 11: program.ProgramRpc.PagePrograms:input_type -> program.PageProgramsReq
	3,  // 12: program.ProgramRpc.GetProgramDetail:input_type -> program.GetProgramDetailReq
	4,  // 13: program.ProgramRpc.ListTicketCategoriesByProgram:input_type -> program.ListTicketCategoriesByProgramReq
	11, // 14: program.ProgramRpc.ListProgramCategories:output_type -> program.ProgramCategoryListResp
	13, // 15: program.ProgramRpc.ListHomePrograms:output_type -> program.ProgramHomeListResp
	14, // 16: program.ProgramRpc.PagePrograms:output_type -> program.ProgramPageResp
	16, // 17: program.ProgramRpc.GetProgramDetail:output_type -> program.ProgramDetailInfo
	15, // 18: program.ProgramRpc.ListTicketCategoriesByProgram:output_type -> program.TicketCategoryDetailListResp
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_services_program_rpc_program_proto_init() }
func file_services_program_rpc_program_proto_init() {
	if File_services_program_rpc_program_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_program_rpc_program_proto_rawDesc), len(file_services_program_rpc_program_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_program_rpc_program_proto_goTypes,
		DependencyIndexes: file_services_program_rpc_program_proto_depIdxs,
		MessageInfos:      file_services_program_rpc_program_proto_msgTypes,
	}.Build()
	File_services_program_rpc_program_proto = out.File
	file_services_program_rpc_program_proto_goTypes = nil
	file_services_program_rpc_program_proto_depIdxs = nil
}
