// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: services/program-rpc/program.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_services_program_rpc_program_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{0}
}

type ListHomeProgramsReq struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	AreaId                   int64                  `protobuf:"varint,1,opt,name=areaId,proto3" json:"areaId,omitempty"`
	ParentProgramCategoryIds []int64                `protobuf:"varint,2,rep,packed,name=parentProgramCategoryIds,proto3" json:"parentProgramCategoryIds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ListHomeProgramsReq) Reset() {
	*x = ListHomeProgramsReq{}
	mi := &file_services_program_rpc_program_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHomeProgramsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHomeProgramsReq) ProtoMessage() {}

func (x *ListHomeProgramsReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHomeProgramsReq.ProtoReflect.Descriptor instead.
func (*ListHomeProgramsReq) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{1}
}

func (x *ListHomeProgramsReq) GetAreaId() int64 {
	if x != nil {
		return x.AreaId
	}
	return 0
}

func (x *ListHomeProgramsReq) GetParentProgramCategoryIds() []int64 {
	if x != nil {
		return x.ParentProgramCategoryIds
	}
	return nil
}

type PageProgramsReq struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	PageNumber              int64                  `protobuf:"varint,1,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	PageSize                int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	AreaId                  int64                  `protobuf:"varint,3,opt,name=areaId,proto3" json:"areaId,omitempty"`
	ParentProgramCategoryId int64                  `protobuf:"varint,4,opt,name=parentProgramCategoryId,proto3" json:"parentProgramCategoryId,omitempty"`
	ProgramCategoryId       int64                  `protobuf:"varint,5,opt,name=programCategoryId,proto3" json:"programCategoryId,omitempty"`
	TimeType                int64                  `protobuf:"varint,6,opt,name=timeType,proto3" json:"timeType,omitempty"`
	StartDateTime           string                 `protobuf:"bytes,7,opt,name=startDateTime,proto3" json:"startDateTime,omitempty"`
	EndDateTime             string                 `protobuf:"bytes,8,opt,name=endDateTime,proto3" json:"endDateTime,omitempty"`
	Type                    int64                  `protobuf:"varint,9,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *PageProgramsReq) Reset() {
	*x = PageProgramsReq{}
	mi := &file_services_program_rpc_program_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageProgramsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageProgramsReq) ProtoMessage() {}

func (x *PageProgramsReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageProgramsReq.ProtoReflect.Descriptor instead.
func (*PageProgramsReq) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{2}
}

func (x *PageProgramsReq) GetPageNumber() int64 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *PageProgramsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *PageProgramsReq) GetAreaId() int64 {
	if x != nil {
		return x.AreaId
	}
	return 0
}

func (x *PageProgramsReq) GetParentProgramCategoryId() int64 {
	if x != nil {
		return x.ParentProgramCategoryId
	}
	return 0
}

func (x *PageProgramsReq) GetProgramCategoryId() int64 {
	if x != nil {
		return x.ProgramCategoryId
	}
	return 0
}

func (x *PageProgramsReq) GetTimeType() int64 {
	if x != nil {
		return x.TimeType
	}
	return 0
}

func (x *PageProgramsReq) GetStartDateTime() string {
	if x != nil {
		return x.StartDateTime
	}
	return ""
}

func (x *PageProgramsReq) GetEndDateTime() string {
	if x != nil {
		return x.EndDateTime
	}
	return ""
}

func (x *PageProgramsReq) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type GetProgramDetailReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProgramDetailReq) Reset() {
	*x = GetProgramDetailReq{}
	mi := &file_services_program_rpc_program_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProgramDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProgramDetailReq) ProtoMessage() {}

func (x *GetProgramDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProgramDetailReq.ProtoReflect.Descriptor instead.
func (*GetProgramDetailReq) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{3}
}

func (x *GetProgramDetailReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListTicketCategoriesByProgramReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramId     int64                  `protobuf:"varint,1,opt,name=programId,proto3" json:"programId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTicketCategoriesByProgramReq) Reset() {
	*x = ListTicketCategoriesByProgramReq{}
	mi := &file_services_program_rpc_program_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTicketCategoriesByProgramReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTicketCategoriesByProgramReq) ProtoMessage() {}

func (x *ListTicketCategoriesByProgramReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTicketCategoriesByProgramReq.ProtoReflect.Descriptor instead.
func (*ListTicketCategoriesByProgramReq) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{4}
}

func (x *ListTicketCategoriesByProgramReq) GetProgramId() int64 {
	if x != nil {
		return x.ProgramId
	}
	return 0
}

type ProgramCategoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ParentId      int64                  `protobuf:"varint,2,opt,name=parentId,proto3" json:"parentId,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          int64                  `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramCategoryInfo) Reset() {
	*x = ProgramCategoryInfo{}
	mi := &file_services_program_rpc_program_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramCategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramCategoryInfo) ProtoMessage() {}

func (x *ProgramCategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramCategoryInfo.ProtoReflect.Descriptor instead.
func (*ProgramCategoryInfo) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{5}
}

func (x *ProgramCategoryInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProgramCategoryInfo) GetParentId() int64 {
	if x != nil {
		return x.ParentId
	}
	return 0
}

func (x *ProgramCategoryInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ProgramCategoryInfo) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

type ProgramSimpleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramId     int64                  `protobuf:"varint,1,opt,name=programId,proto3" json:"programId,omitempty"`
	AreaId        int64                  `protobuf:"varint,2,opt,name=areaId,proto3" json:"areaId,omitempty"`
	AreaIdName    string                 `protobuf:"bytes,3,opt,name=areaIdName,proto3" json:"areaIdName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramSimpleInfo) Reset() {
	*x = ProgramSimpleInfo{}
	mi := &file_services_program_rpc_program_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramSimpleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramSimpleInfo) ProtoMessage() {}

func (x *ProgramSimpleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramSimpleInfo.ProtoReflect.Descriptor instead.
func (*ProgramSimpleInfo) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{6}
}

func (x *ProgramSimpleInfo) GetProgramId() int64 {
	if x != nil {
		return x.ProgramId
	}
	return 0
}

func (x *ProgramSimpleInfo) GetAreaId() int64 {
	if x != nil {
		return x.AreaId
	}
	return 0
}

func (x *ProgramSimpleInfo) GetAreaIdName() string {
	if x != nil {
		return x.AreaIdName
	}
	return ""
}

type ProgramGroupInfo struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Id                      int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProgramSimpleInfoVoList []*ProgramSimpleInfo   `protobuf:"bytes,2,rep,name=programSimpleInfoVoList,proto3" json:"programSimpleInfoVoList,omitempty"`
	RecentShowTime          string                 `protobuf:"bytes,3,opt,name=recentShowTime,proto3" json:"recentShowTime,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ProgramGroupInfo) Reset() {
	*x = ProgramGroupInfo{}
	mi := &file_services_program_rpc_program_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramGroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramGroupInfo) ProtoMessage() {}

func (x *ProgramGroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramGroupInfo.ProtoReflect.Descriptor instead.
func (*ProgramGroupInfo) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{7}
}

func (x *ProgramGroupInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProgramGroupInfo) GetProgramSimpleInfoVoList() []*ProgramSimpleInfo {
	if x != nil {
		return x.ProgramSimpleInfoVoList
	}
	return nil
}

func (x *ProgramGroupInfo) GetRecentShowTime() string {
	if x != nil {
		return x.RecentShowTime
	}
	return ""
}

type ProgramHomeSection struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	CategoryName      string                 `protobuf:"bytes,1,opt,name=categoryName,proto3" json:"categoryName,omitempty"`
	CategoryId        int64                  `protobuf:"varint,2,opt,name=categoryId,proto3" json:"categoryId,omitempty"`
	ProgramListVoList []*ProgramListInfo     `protobuf:"bytes,3,rep,name=programListVoList,proto3" json:"programListVoList,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ProgramHomeSection) Reset() {
	*x = ProgramHomeSection{}
	mi := &file_services_program_rpc_program_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramHomeSection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramHomeSection) ProtoMessage() {}

func (x *ProgramHomeSection) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramHomeSection.ProtoReflect.Descriptor instead.
func (*ProgramHomeSection) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{8}
}

func (x *ProgramHomeSection) GetCategoryName() string {
	if x != nil {
		return x.CategoryName
	}
	return ""
}

func (x *ProgramHomeSection) GetCategoryId() int64 {
	if x != nil {
		return x.CategoryId
	}
	return 0
}

func (x *ProgramHomeSection) GetProgramListVoList() []*ProgramListInfo {
	if x != nil {
		return x.ProgramListVoList
	}
	return nil
}

type TicketCategoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Introduce     string                 `protobuf:"bytes,2,opt,name=introduce,proto3" json:"introduce,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketCategoryInfo) Reset() {
	*x = TicketCategoryInfo{}
	mi := &file_services_program_rpc_program_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketCategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketCategoryInfo) ProtoMessage() {}

func (x *TicketCategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketCategoryInfo.ProtoReflect.Descriptor instead.
func (*TicketCategoryInfo) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{9}
}

func (x *TicketCategoryInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TicketCategoryInfo) GetIntroduce() string {
	if x != nil {
		return x.Introduce
	}
	return ""
}

func (x *TicketCategoryInfo) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type SeatInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SeatId           int64                  `protobuf:"varint,1,opt,name=seatId,proto3" json:"seatId,omitempty"`
	TicketCategoryId int64                  `protobuf:"varint,2,opt,name=ticketCategoryId,proto3" json:"ticketCategoryId,omitempty"`
	RowCode          int64                  `protobuf:"varint,3,opt,name=rowCode,proto3" json:"rowCode,omitempty"`
	ColCode          int64                  `protobuf:"varint,4,opt,name=colCode,proto3" json:"colCode,omitempty"`
	Price            int64                  `protobuf:"varint,5,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SeatInfo) Reset() {
	*x = SeatInfo{}
	mi := &file_services_program_rpc_program_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SeatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatInfo) ProtoMessage() {}

func (x *SeatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatInfo.ProtoReflect.Descriptor instead.
func (*SeatInfo) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{10}
}

func (x *SeatInfo) GetSeatId() int64 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *SeatInfo) GetTicketCategoryId() int64 {
	if x != nil {
		return x.TicketCategoryId
	}
	return 0
}

func (x *SeatInfo) GetRowCode() int64 {
	if x != nil {
		return x.RowCode
	}
	return 0
}

func (x *SeatInfo) GetColCode() int64 {
	if x != nil {
		return x.ColCode
	}
	return 0
}

func (x *SeatInfo) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type TicketCategoryDetailInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProgramId     int64                  `protobuf:"varint,1,opt,name=programId,proto3" json:"programId,omitempty"`
	Introduce     string                 `protobuf:"bytes,2,opt,name=introduce,proto3" json:"introduce,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	TotalNumber   int64                  `protobuf:"varint,4,opt,name=totalNumber,proto3" json:"totalNumber,omitempty"`
	RemainNumber  int64                  `protobuf:"varint,5,opt,name=remainNumber,proto3" json:"remainNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketCategoryDetailInfo) Reset() {
	*x = TicketCategoryDetailInfo{}
	mi := &file_services_program_rpc_program_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketCategoryDetailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketCategoryDetailInfo) ProtoMessage() {}

func (x *TicketCategoryDetailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketCategoryDetailInfo.ProtoReflect.Descriptor instead.
func (*TicketCategoryDetailInfo) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{11}
}

func (x *TicketCategoryDetailInfo) GetProgramId() int64 {
	if x != nil {
		return x.ProgramId
	}
	return 0
}

func (x *TicketCategoryDetailInfo) GetIntroduce() string {
	if x != nil {
		return x.Introduce
	}
	return ""
}

func (x *TicketCategoryDetailInfo) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TicketCategoryDetailInfo) GetTotalNumber() int64 {
	if x != nil {
		return x.TotalNumber
	}
	return 0
}

func (x *TicketCategoryDetailInfo) GetRemainNumber() int64 {
	if x != nil {
		return x.RemainNumber
	}
	return 0
}

type ProgramPreorderTicketCategoryInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Introduce     string                 `protobuf:"bytes,2,opt,name=introduce,proto3" json:"introduce,omitempty"`
	Price         int64                  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	TotalNumber   int64                  `protobuf:"varint,4,opt,name=totalNumber,proto3" json:"totalNumber,omitempty"`
	RemainNumber  int64                  `protobuf:"varint,5,opt,name=remainNumber,proto3" json:"remainNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramPreorderTicketCategoryInfo) Reset() {
	*x = ProgramPreorderTicketCategoryInfo{}
	mi := &file_services_program_rpc_program_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramPreorderTicketCategoryInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramPreorderTicketCategoryInfo) ProtoMessage() {}

func (x *ProgramPreorderTicketCategoryInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramPreorderTicketCategoryInfo.ProtoReflect.Descriptor instead.
func (*ProgramPreorderTicketCategoryInfo) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{12}
}

func (x *ProgramPreorderTicketCategoryInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProgramPreorderTicketCategoryInfo) GetIntroduce() string {
	if x != nil {
		return x.Introduce
	}
	return ""
}

func (x *ProgramPreorderTicketCategoryInfo) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *ProgramPreorderTicketCategoryInfo) GetTotalNumber() int64 {
	if x != nil {
		return x.TotalNumber
	}
	return 0
}

func (x *ProgramPreorderTicketCategoryInfo) GetRemainNumber() int64 {
	if x != nil {
		return x.RemainNumber
	}
	return 0
}

type ProgramCategoryListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*ProgramCategoryInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramCategoryListResp) Reset() {
	*x = ProgramCategoryListResp{}
	mi := &file_services_program_rpc_program_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramCategoryListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramCategoryListResp) ProtoMessage() {}

func (x *ProgramCategoryListResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramCategoryListResp.ProtoReflect.Descriptor instead.
func (*ProgramCategoryListResp) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{13}
}

func (x *ProgramCategoryListResp) GetList() []*ProgramCategoryInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type ProgramListInfo struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Id                        int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                     string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Actor                     string                 `protobuf:"bytes,3,opt,name=actor,proto3" json:"actor,omitempty"`
	Place                     string                 `protobuf:"bytes,4,opt,name=place,proto3" json:"place,omitempty"`
	ItemPicture               string                 `protobuf:"bytes,5,opt,name=itemPicture,proto3" json:"itemPicture,omitempty"`
	AreaId                    int64                  `protobuf:"varint,6,opt,name=areaId,proto3" json:"areaId,omitempty"`
	AreaName                  string                 `protobuf:"bytes,7,opt,name=areaName,proto3" json:"areaName,omitempty"`
	ProgramCategoryId         int64                  `protobuf:"varint,8,opt,name=programCategoryId,proto3" json:"programCategoryId,omitempty"`
	ProgramCategoryName       string                 `protobuf:"bytes,9,opt,name=programCategoryName,proto3" json:"programCategoryName,omitempty"`
	ParentProgramCategoryId   int64                  `protobuf:"varint,10,opt,name=parentProgramCategoryId,proto3" json:"parentProgramCategoryId,omitempty"`
	ParentProgramCategoryName string                 `protobuf:"bytes,11,opt,name=parentProgramCategoryName,proto3" json:"parentProgramCategoryName,omitempty"`
	ShowTime                  string                 `protobuf:"bytes,12,opt,name=showTime,proto3" json:"showTime,omitempty"`
	ShowDayTime               string                 `protobuf:"bytes,13,opt,name=showDayTime,proto3" json:"showDayTime,omitempty"`
	ShowWeekTime              string                 `protobuf:"bytes,14,opt,name=showWeekTime,proto3" json:"showWeekTime,omitempty"`
	MinPrice                  int64                  `protobuf:"varint,15,opt,name=minPrice,proto3" json:"minPrice,omitempty"`
	MaxPrice                  int64                  `protobuf:"varint,16,opt,name=maxPrice,proto3" json:"maxPrice,omitempty"`
	EsId                      int64                  `protobuf:"varint,17,opt,name=esId,proto3" json:"esId,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ProgramListInfo) Reset() {
	*x = ProgramListInfo{}
	mi := &file_services_program_rpc_program_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramListInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramListInfo) ProtoMessage() {}

func (x *ProgramListInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramListInfo.ProtoReflect.Descriptor instead.
func (*ProgramListInfo) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{14}
}

func (x *ProgramListInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProgramListInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProgramListInfo) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *ProgramListInfo) GetPlace() string {
	if x != nil {
		return x.Place
	}
	return ""
}

func (x *ProgramListInfo) GetItemPicture() string {
	if x != nil {
		return x.ItemPicture
	}
	return ""
}

func (x *ProgramListInfo) GetAreaId() int64 {
	if x != nil {
		return x.AreaId
	}
	return 0
}

func (x *ProgramListInfo) GetAreaName() string {
	if x != nil {
		return x.AreaName
	}
	return ""
}

func (x *ProgramListInfo) GetProgramCategoryId() int64 {
	if x != nil {
		return x.ProgramCategoryId
	}
	return 0
}

func (x *ProgramListInfo) GetProgramCategoryName() string {
	if x != nil {
		return x.ProgramCategoryName
	}
	return ""
}

func (x *ProgramListInfo) GetParentProgramCategoryId() int64 {
	if x != nil {
		return x.ParentProgramCategoryId
	}
	return 0
}

func (x *ProgramListInfo) GetParentProgramCategoryName() string {
	if x != nil {
		return x.ParentProgramCategoryName
	}
	return ""
}

func (x *ProgramListInfo) GetShowTime() string {
	if x != nil {
		return x.ShowTime
	}
	return ""
}

func (x *ProgramListInfo) GetShowDayTime() string {
	if x != nil {
		return x.ShowDayTime
	}
	return ""
}

func (x *ProgramListInfo) GetShowWeekTime() string {
	if x != nil {
		return x.ShowWeekTime
	}
	return ""
}

func (x *ProgramListInfo) GetMinPrice() int64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *ProgramListInfo) GetMaxPrice() int64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *ProgramListInfo) GetEsId() int64 {
	if x != nil {
		return x.EsId
	}
	return 0
}

type ProgramHomeListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sections      []*ProgramHomeSection  `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramHomeListResp) Reset() {
	*x = ProgramHomeListResp{}
	mi := &file_services_program_rpc_program_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramHomeListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramHomeListResp) ProtoMessage() {}

func (x *ProgramHomeListResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramHomeListResp.ProtoReflect.Descriptor instead.
func (*ProgramHomeListResp) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{15}
}

func (x *ProgramHomeListResp) GetSections() []*ProgramHomeSection {
	if x != nil {
		return x.Sections
	}
	return nil
}

type ProgramPageResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNum       int64                  `protobuf:"varint,1,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	TotalSize     int64                  `protobuf:"varint,3,opt,name=totalSize,proto3" json:"totalSize,omitempty"`
	List          []*ProgramListInfo     `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProgramPageResp) Reset() {
	*x = ProgramPageResp{}
	mi := &file_services_program_rpc_program_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramPageResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramPageResp) ProtoMessage() {}

func (x *ProgramPageResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramPageResp.ProtoReflect.Descriptor instead.
func (*ProgramPageResp) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{16}
}

func (x *ProgramPageResp) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ProgramPageResp) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ProgramPageResp) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ProgramPageResp) GetList() []*ProgramListInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type TicketCategoryDetailListResp struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	List          []*TicketCategoryDetailInfo `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TicketCategoryDetailListResp) Reset() {
	*x = TicketCategoryDetailListResp{}
	mi := &file_services_program_rpc_program_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TicketCategoryDetailListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TicketCategoryDetailListResp) ProtoMessage() {}

func (x *TicketCategoryDetailListResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TicketCategoryDetailListResp.ProtoReflect.Descriptor instead.
func (*TicketCategoryDetailListResp) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{17}
}

func (x *TicketCategoryDetailListResp) GetList() []*TicketCategoryDetailInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type ProgramPreorderInfo struct {
	state                        protoimpl.MessageState               `protogen:"open.v1"`
	Id                           int64                                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProgramGroupId               int64                                `protobuf:"varint,2,opt,name=programGroupId,proto3" json:"programGroupId,omitempty"`
	Title                        string                               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Actor                        string                               `protobuf:"bytes,4,opt,name=actor,proto3" json:"actor,omitempty"`
	Place                        string                               `protobuf:"bytes,5,opt,name=place,proto3" json:"place,omitempty"`
	ItemPicture                  string                               `protobuf:"bytes,6,opt,name=itemPicture,proto3" json:"itemPicture,omitempty"`
	ShowTime                     string                               `protobuf:"bytes,7,opt,name=showTime,proto3" json:"showTime,omitempty"`
	ShowDayTime                  string                               `protobuf:"bytes,8,opt,name=showDayTime,proto3" json:"showDayTime,omitempty"`
	ShowWeekTime                 string                               `protobuf:"bytes,9,opt,name=showWeekTime,proto3" json:"showWeekTime,omitempty"`
	PerOrderLimitPurchaseCount   int64                                `protobuf:"varint,10,opt,name=perOrderLimitPurchaseCount,proto3" json:"perOrderLimitPurchaseCount,omitempty"`
	PerAccountLimitPurchaseCount int64                                `protobuf:"varint,11,opt,name=perAccountLimitPurchaseCount,proto3" json:"perAccountLimitPurchaseCount,omitempty"`
	PermitChooseSeat             int64                                `protobuf:"varint,12,opt,name=permitChooseSeat,proto3" json:"permitChooseSeat,omitempty"`
	ChooseSeatExplain            string                               `protobuf:"bytes,13,opt,name=chooseSeatExplain,proto3" json:"chooseSeatExplain,omitempty"`
	TicketCategoryVoList         []*ProgramPreorderTicketCategoryInfo `protobuf:"bytes,14,rep,name=ticketCategoryVoList,proto3" json:"ticketCategoryVoList,omitempty"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *ProgramPreorderInfo) Reset() {
	*x = ProgramPreorderInfo{}
	mi := &file_services_program_rpc_program_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramPreorderInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramPreorderInfo) ProtoMessage() {}

func (x *ProgramPreorderInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramPreorderInfo.ProtoReflect.Descriptor instead.
func (*ProgramPreorderInfo) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{18}
}

func (x *ProgramPreorderInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProgramPreorderInfo) GetProgramGroupId() int64 {
	if x != nil {
		return x.ProgramGroupId
	}
	return 0
}

func (x *ProgramPreorderInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProgramPreorderInfo) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *ProgramPreorderInfo) GetPlace() string {
	if x != nil {
		return x.Place
	}
	return ""
}

func (x *ProgramPreorderInfo) GetItemPicture() string {
	if x != nil {
		return x.ItemPicture
	}
	return ""
}

func (x *ProgramPreorderInfo) GetShowTime() string {
	if x != nil {
		return x.ShowTime
	}
	return ""
}

func (x *ProgramPreorderInfo) GetShowDayTime() string {
	if x != nil {
		return x.ShowDayTime
	}
	return ""
}

func (x *ProgramPreorderInfo) GetShowWeekTime() string {
	if x != nil {
		return x.ShowWeekTime
	}
	return ""
}

func (x *ProgramPreorderInfo) GetPerOrderLimitPurchaseCount() int64 {
	if x != nil {
		return x.PerOrderLimitPurchaseCount
	}
	return 0
}

func (x *ProgramPreorderInfo) GetPerAccountLimitPurchaseCount() int64 {
	if x != nil {
		return x.PerAccountLimitPurchaseCount
	}
	return 0
}

func (x *ProgramPreorderInfo) GetPermitChooseSeat() int64 {
	if x != nil {
		return x.PermitChooseSeat
	}
	return 0
}

func (x *ProgramPreorderInfo) GetChooseSeatExplain() string {
	if x != nil {
		return x.ChooseSeatExplain
	}
	return ""
}

func (x *ProgramPreorderInfo) GetTicketCategoryVoList() []*ProgramPreorderTicketCategoryInfo {
	if x != nil {
		return x.TicketCategoryVoList
	}
	return nil
}

type AutoAssignAndFreezeSeatsReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ProgramId        int64                  `protobuf:"varint,1,opt,name=programId,proto3" json:"programId,omitempty"`
	TicketCategoryId int64                  `protobuf:"varint,2,opt,name=ticketCategoryId,proto3" json:"ticketCategoryId,omitempty"`
	Count            int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	RequestNo        string                 `protobuf:"bytes,4,opt,name=requestNo,proto3" json:"requestNo,omitempty"`
	FreezeSeconds    int64                  `protobuf:"varint,5,opt,name=freezeSeconds,proto3" json:"freezeSeconds,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AutoAssignAndFreezeSeatsReq) Reset() {
	*x = AutoAssignAndFreezeSeatsReq{}
	mi := &file_services_program_rpc_program_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoAssignAndFreezeSeatsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoAssignAndFreezeSeatsReq) ProtoMessage() {}

func (x *AutoAssignAndFreezeSeatsReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoAssignAndFreezeSeatsReq.ProtoReflect.Descriptor instead.
func (*AutoAssignAndFreezeSeatsReq) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{19}
}

func (x *AutoAssignAndFreezeSeatsReq) GetProgramId() int64 {
	if x != nil {
		return x.ProgramId
	}
	return 0
}

func (x *AutoAssignAndFreezeSeatsReq) GetTicketCategoryId() int64 {
	if x != nil {
		return x.TicketCategoryId
	}
	return 0
}

func (x *AutoAssignAndFreezeSeatsReq) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *AutoAssignAndFreezeSeatsReq) GetRequestNo() string {
	if x != nil {
		return x.RequestNo
	}
	return ""
}

func (x *AutoAssignAndFreezeSeatsReq) GetFreezeSeconds() int64 {
	if x != nil {
		return x.FreezeSeconds
	}
	return 0
}

type AutoAssignAndFreezeSeatsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FreezeToken   string                 `protobuf:"bytes,1,opt,name=freezeToken,proto3" json:"freezeToken,omitempty"`
	ExpireTime    string                 `protobuf:"bytes,2,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	Seats         []*SeatInfo            `protobuf:"bytes,3,rep,name=seats,proto3" json:"seats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoAssignAndFreezeSeatsResp) Reset() {
	*x = AutoAssignAndFreezeSeatsResp{}
	mi := &file_services_program_rpc_program_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoAssignAndFreezeSeatsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoAssignAndFreezeSeatsResp) ProtoMessage() {}

func (x *AutoAssignAndFreezeSeatsResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoAssignAndFreezeSeatsResp.ProtoReflect.Descriptor instead.
func (*AutoAssignAndFreezeSeatsResp) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{20}
}

func (x *AutoAssignAndFreezeSeatsResp) GetFreezeToken() string {
	if x != nil {
		return x.FreezeToken
	}
	return ""
}

func (x *AutoAssignAndFreezeSeatsResp) GetExpireTime() string {
	if x != nil {
		return x.ExpireTime
	}
	return ""
}

func (x *AutoAssignAndFreezeSeatsResp) GetSeats() []*SeatInfo {
	if x != nil {
		return x.Seats
	}
	return nil
}

type ReleaseSeatFreezeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FreezeToken   string                 `protobuf:"bytes,1,opt,name=freezeToken,proto3" json:"freezeToken,omitempty"`
	ReleaseReason string                 `protobuf:"bytes,2,opt,name=releaseReason,proto3" json:"releaseReason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSeatFreezeReq) Reset() {
	*x = ReleaseSeatFreezeReq{}
	mi := &file_services_program_rpc_program_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSeatFreezeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSeatFreezeReq) ProtoMessage() {}

func (x *ReleaseSeatFreezeReq) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSeatFreezeReq.ProtoReflect.Descriptor instead.
func (*ReleaseSeatFreezeReq) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{21}
}

func (x *ReleaseSeatFreezeReq) GetFreezeToken() string {
	if x != nil {
		return x.FreezeToken
	}
	return ""
}

func (x *ReleaseSeatFreezeReq) GetReleaseReason() string {
	if x != nil {
		return x.ReleaseReason
	}
	return ""
}

type ReleaseSeatFreezeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseSeatFreezeResp) Reset() {
	*x = ReleaseSeatFreezeResp{}
	mi := &file_services_program_rpc_program_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseSeatFreezeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseSeatFreezeResp) ProtoMessage() {}

func (x *ReleaseSeatFreezeResp) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseSeatFreezeResp.ProtoReflect.Descriptor instead.
func (*ReleaseSeatFreezeResp) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{22}
}

func (x *ReleaseSeatFreezeResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ProgramDetailInfo struct {
	state                           protoimpl.MessageState `protogen:"open.v1"`
	Id                              int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ProgramGroupId                  int64                  `protobuf:"varint,2,opt,name=programGroupId,proto3" json:"programGroupId,omitempty"`
	Prime                           int64                  `protobuf:"varint,3,opt,name=prime,proto3" json:"prime,omitempty"`
	ProgramGroupVo                  *ProgramGroupInfo      `protobuf:"bytes,4,opt,name=programGroupVo,proto3" json:"programGroupVo,omitempty"`
	Title                           string                 `protobuf:"bytes,5,opt,name=title,proto3" json:"title,omitempty"`
	Actor                           string                 `protobuf:"bytes,6,opt,name=actor,proto3" json:"actor,omitempty"`
	Place                           string                 `protobuf:"bytes,7,opt,name=place,proto3" json:"place,omitempty"`
	ItemPicture                     string                 `protobuf:"bytes,8,opt,name=itemPicture,proto3" json:"itemPicture,omitempty"`
	PreSell                         int64                  `protobuf:"varint,9,opt,name=preSell,proto3" json:"preSell,omitempty"`
	PreSellInstruction              string                 `protobuf:"bytes,10,opt,name=preSellInstruction,proto3" json:"preSellInstruction,omitempty"`
	ImportantNotice                 string                 `protobuf:"bytes,11,opt,name=importantNotice,proto3" json:"importantNotice,omitempty"`
	AreaId                          int64                  `protobuf:"varint,12,opt,name=areaId,proto3" json:"areaId,omitempty"`
	AreaName                        string                 `protobuf:"bytes,13,opt,name=areaName,proto3" json:"areaName,omitempty"`
	ProgramCategoryId               int64                  `protobuf:"varint,14,opt,name=programCategoryId,proto3" json:"programCategoryId,omitempty"`
	ProgramCategoryName             string                 `protobuf:"bytes,15,opt,name=programCategoryName,proto3" json:"programCategoryName,omitempty"`
	ParentProgramCategoryId         int64                  `protobuf:"varint,16,opt,name=parentProgramCategoryId,proto3" json:"parentProgramCategoryId,omitempty"`
	ParentProgramCategoryName       string                 `protobuf:"bytes,17,opt,name=parentProgramCategoryName,proto3" json:"parentProgramCategoryName,omitempty"`
	Detail                          string                 `protobuf:"bytes,18,opt,name=detail,proto3" json:"detail,omitempty"`
	PerOrderLimitPurchaseCount      int64                  `protobuf:"varint,19,opt,name=perOrderLimitPurchaseCount,proto3" json:"perOrderLimitPurchaseCount,omitempty"`
	PerAccountLimitPurchaseCount    int64                  `protobuf:"varint,20,opt,name=perAccountLimitPurchaseCount,proto3" json:"perAccountLimitPurchaseCount,omitempty"`
	RefundTicketRule                string                 `protobuf:"bytes,21,opt,name=refundTicketRule,proto3" json:"refundTicketRule,omitempty"`
	DeliveryInstruction             string                 `protobuf:"bytes,22,opt,name=deliveryInstruction,proto3" json:"deliveryInstruction,omitempty"`
	EntryRule                       string                 `protobuf:"bytes,23,opt,name=entryRule,proto3" json:"entryRule,omitempty"`
	ChildPurchase                   string                 `protobuf:"bytes,24,opt,name=childPurchase,proto3" json:"childPurchase,omitempty"`
	InvoiceSpecification            string                 `protobuf:"bytes,25,opt,name=invoiceSpecification,proto3" json:"invoiceSpecification,omitempty"`
	RealTicketPurchaseRule          string                 `protobuf:"bytes,26,opt,name=realTicketPurchaseRule,proto3" json:"realTicketPurchaseRule,omitempty"`
	AbnormalOrderDescription        string                 `protobuf:"bytes,27,opt,name=abnormalOrderDescription,proto3" json:"abnormalOrderDescription,omitempty"`
	KindReminder                    string                 `protobuf:"bytes,28,opt,name=kindReminder,proto3" json:"kindReminder,omitempty"`
	PerformanceDuration             string                 `protobuf:"bytes,29,opt,name=performanceDuration,proto3" json:"performanceDuration,omitempty"`
	EntryTime                       string                 `protobuf:"bytes,30,opt,name=entryTime,proto3" json:"entryTime,omitempty"`
	MinPerformanceCount             int64                  `protobuf:"varint,31,opt,name=minPerformanceCount,proto3" json:"minPerformanceCount,omitempty"`
	MainActor                       string                 `protobuf:"bytes,32,opt,name=mainActor,proto3" json:"mainActor,omitempty"`
	MinPerformanceDuration          string                 `protobuf:"bytes,33,opt,name=minPerformanceDuration,proto3" json:"minPerformanceDuration,omitempty"`
	ProhibitedItem                  string                 `protobuf:"bytes,34,opt,name=prohibitedItem,proto3" json:"prohibitedItem,omitempty"`
	DepositSpecification            string                 `protobuf:"bytes,35,opt,name=depositSpecification,proto3" json:"depositSpecification,omitempty"`
	TotalCount                      int64                  `protobuf:"varint,36,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	PermitRefund                    int64                  `protobuf:"varint,37,opt,name=permitRefund,proto3" json:"permitRefund,omitempty"`
	RefundExplain                   string                 `protobuf:"bytes,38,opt,name=refundExplain,proto3" json:"refundExplain,omitempty"`
	RelNameTicketEntrance           int64                  `protobuf:"varint,39,opt,name=relNameTicketEntrance,proto3" json:"relNameTicketEntrance,omitempty"`
	RelNameTicketEntranceExplain    string                 `protobuf:"bytes,40,opt,name=relNameTicketEntranceExplain,proto3" json:"relNameTicketEntranceExplain,omitempty"`
	PermitChooseSeat                int64                  `protobuf:"varint,41,opt,name=permitChooseSeat,proto3" json:"permitChooseSeat,omitempty"`
	ChooseSeatExplain               string                 `protobuf:"bytes,42,opt,name=chooseSeatExplain,proto3" json:"chooseSeatExplain,omitempty"`
	ElectronicDeliveryTicket        int64                  `protobuf:"varint,43,opt,name=electronicDeliveryTicket,proto3" json:"electronicDeliveryTicket,omitempty"`
	ElectronicDeliveryTicketExplain string                 `protobuf:"bytes,44,opt,name=electronicDeliveryTicketExplain,proto3" json:"electronicDeliveryTicketExplain,omitempty"`
	ElectronicInvoice               int64                  `protobuf:"varint,45,opt,name=electronicInvoice,proto3" json:"electronicInvoice,omitempty"`
	ElectronicInvoiceExplain        string                 `protobuf:"bytes,46,opt,name=electronicInvoiceExplain,proto3" json:"electronicInvoiceExplain,omitempty"`
	HighHeat                        int64                  `protobuf:"varint,47,opt,name=highHeat,proto3" json:"highHeat,omitempty"`
	ProgramStatus                   int64                  `protobuf:"varint,48,opt,name=programStatus,proto3" json:"programStatus,omitempty"`
	IssueTime                       string                 `protobuf:"bytes,49,opt,name=issueTime,proto3" json:"issueTime,omitempty"`
	ShowTime                        string                 `protobuf:"bytes,50,opt,name=showTime,proto3" json:"showTime,omitempty"`
	ShowDayTime                     string                 `protobuf:"bytes,51,opt,name=showDayTime,proto3" json:"showDayTime,omitempty"`
	ShowWeekTime                    string                 `protobuf:"bytes,52,opt,name=showWeekTime,proto3" json:"showWeekTime,omitempty"`
	TicketCategoryVoList            []*TicketCategoryInfo  `protobuf:"bytes,53,rep,name=ticketCategoryVoList,proto3" json:"ticketCategoryVoList,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *ProgramDetailInfo) Reset() {
	*x = ProgramDetailInfo{}
	mi := &file_services_program_rpc_program_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProgramDetailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProgramDetailInfo) ProtoMessage() {}

func (x *ProgramDetailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_services_program_rpc_program_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProgramDetailInfo.ProtoReflect.Descriptor instead.
func (*ProgramDetailInfo) Descriptor() ([]byte, []int) {
	return file_services_program_rpc_program_proto_rawDescGZIP(), []int{23}
}

func (x *ProgramDetailInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ProgramDetailInfo) GetProgramGroupId() int64 {
	if x != nil {
		return x.ProgramGroupId
	}
	return 0
}

func (x *ProgramDetailInfo) GetPrime() int64 {
	if x != nil {
		return x.Prime
	}
	return 0
}

func (x *ProgramDetailInfo) GetProgramGroupVo() *ProgramGroupInfo {
	if x != nil {
		return x.ProgramGroupVo
	}
	return nil
}

func (x *ProgramDetailInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ProgramDetailInfo) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *ProgramDetailInfo) GetPlace() string {
	if x != nil {
		return x.Place
	}
	return ""
}

func (x *ProgramDetailInfo) GetItemPicture() string {
	if x != nil {
		return x.ItemPicture
	}
	return ""
}

func (x *ProgramDetailInfo) GetPreSell() int64 {
	if x != nil {
		return x.PreSell
	}
	return 0
}

func (x *ProgramDetailInfo) GetPreSellInstruction() string {
	if x != nil {
		return x.PreSellInstruction
	}
	return ""
}

func (x *ProgramDetailInfo) GetImportantNotice() string {
	if x != nil {
		return x.ImportantNotice
	}
	return ""
}

func (x *ProgramDetailInfo) GetAreaId() int64 {
	if x != nil {
		return x.AreaId
	}
	return 0
}

func (x *ProgramDetailInfo) GetAreaName() string {
	if x != nil {
		return x.AreaName
	}
	return ""
}

func (x *ProgramDetailInfo) GetProgramCategoryId() int64 {
	if x != nil {
		return x.ProgramCategoryId
	}
	return 0
}

func (x *ProgramDetailInfo) GetProgramCategoryName() string {
	if x != nil {
		return x.ProgramCategoryName
	}
	return ""
}

func (x *ProgramDetailInfo) GetParentProgramCategoryId() int64 {
	if x != nil {
		return x.ParentProgramCategoryId
	}
	return 0
}

func (x *ProgramDetailInfo) GetParentProgramCategoryName() string {
	if x != nil {
		return x.ParentProgramCategoryName
	}
	return ""
}

func (x *ProgramDetailInfo) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ProgramDetailInfo) GetPerOrderLimitPurchaseCount() int64 {
	if x != nil {
		return x.PerOrderLimitPurchaseCount
	}
	return 0
}

func (x *ProgramDetailInfo) GetPerAccountLimitPurchaseCount() int64 {
	if x != nil {
		return x.PerAccountLimitPurchaseCount
	}
	return 0
}

func (x *ProgramDetailInfo) GetRefundTicketRule() string {
	if x != nil {
		return x.RefundTicketRule
	}
	return ""
}

func (x *ProgramDetailInfo) GetDeliveryInstruction() string {
	if x != nil {
		return x.DeliveryInstruction
	}
	return ""
}

func (x *ProgramDetailInfo) GetEntryRule() string {
	if x != nil {
		return x.EntryRule
	}
	return ""
}

func (x *ProgramDetailInfo) GetChildPurchase() string {
	if x != nil {
		return x.ChildPurchase
	}
	return ""
}

func (x *ProgramDetailInfo) GetInvoiceSpecification() string {
	if x != nil {
		return x.InvoiceSpecification
	}
	return ""
}

func (x *ProgramDetailInfo) GetRealTicketPurchaseRule() string {
	if x != nil {
		return x.RealTicketPurchaseRule
	}
	return ""
}

func (x *ProgramDetailInfo) GetAbnormalOrderDescription() string {
	if x != nil {
		return x.AbnormalOrderDescription
	}
	return ""
}

func (x *ProgramDetailInfo) GetKindReminder() string {
	if x != nil {
		return x.KindReminder
	}
	return ""
}

func (x *ProgramDetailInfo) GetPerformanceDuration() string {
	if x != nil {
		return x.PerformanceDuration
	}
	return ""
}

func (x *ProgramDetailInfo) GetEntryTime() string {
	if x != nil {
		return x.EntryTime
	}
	return ""
}

func (x *ProgramDetailInfo) GetMinPerformanceCount() int64 {
	if x != nil {
		return x.MinPerformanceCount
	}
	return 0
}

func (x *ProgramDetailInfo) GetMainActor() string {
	if x != nil {
		return x.MainActor
	}
	return ""
}

func (x *ProgramDetailInfo) GetMinPerformanceDuration() string {
	if x != nil {
		return x.MinPerformanceDuration
	}
	return ""
}

func (x *ProgramDetailInfo) GetProhibitedItem() string {
	if x != nil {
		return x.ProhibitedItem
	}
	return ""
}

func (x *ProgramDetailInfo) GetDepositSpecification() string {
	if x != nil {
		return x.DepositSpecification
	}
	return ""
}

func (x *ProgramDetailInfo) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *ProgramDetailInfo) GetPermitRefund() int64 {
	if x != nil {
		return x.PermitRefund
	}
	return 0
}

func (x *ProgramDetailInfo) GetRefundExplain() string {
	if x != nil {
		return x.RefundExplain
	}
	return ""
}

func (x *ProgramDetailInfo) GetRelNameTicketEntrance() int64 {
	if x != nil {
		return x.RelNameTicketEntrance
	}
	return 0
}

func (x *ProgramDetailInfo) GetRelNameTicketEntranceExplain() string {
	if x != nil {
		return x.RelNameTicketEntranceExplain
	}
	return ""
}

func (x *ProgramDetailInfo) GetPermitChooseSeat() int64 {
	if x != nil {
		return x.PermitChooseSeat
	}
	return 0
}

func (x *ProgramDetailInfo) GetChooseSeatExplain() string {
	if x != nil {
		return x.ChooseSeatExplain
	}
	return ""
}

func (x *ProgramDetailInfo) GetElectronicDeliveryTicket() int64 {
	if x != nil {
		return x.ElectronicDeliveryTicket
	}
	return 0
}

func (x *ProgramDetailInfo) GetElectronicDeliveryTicketExplain() string {
	if x != nil {
		return x.ElectronicDeliveryTicketExplain
	}
	return ""
}

func (x *ProgramDetailInfo) GetElectronicInvoice() int64 {
	if x != nil {
		return x.ElectronicInvoice
	}
	return 0
}

func (x *ProgramDetailInfo) GetElectronicInvoiceExplain() string {
	if x != nil {
		return x.ElectronicInvoiceExplain
	}
	return ""
}

func (x *ProgramDetailInfo) GetHighHeat() int64 {
	if x != nil {
		return x.HighHeat
	}
	return 0
}

func (x *ProgramDetailInfo) GetProgramStatus() int64 {
	if x != nil {
		return x.ProgramStatus
	}
	return 0
}

func (x *ProgramDetailInfo) GetIssueTime() string {
	if x != nil {
		return x.IssueTime
	}
	return ""
}

func (x *ProgramDetailInfo) GetShowTime() string {
	if x != nil {
		return x.ShowTime
	}
	return ""
}

func (x *ProgramDetailInfo) GetShowDayTime() string {
	if x != nil {
		return x.ShowDayTime
	}
	return ""
}

func (x *ProgramDetailInfo) GetShowWeekTime() string {
	if x != nil {
		return x.ShowWeekTime
	}
	return ""
}

func (x *ProgramDetailInfo) GetTicketCategoryVoList() []*TicketCategoryInfo {
	if x != nil {
		return x.TicketCategoryVoList
	}
	return nil
}

var File_services_program_rpc_program_proto protoreflect.FileDescriptor

const file_services_program_rpc_program_proto_rawDesc = "" +
	"\n" +
	"\"services/program-rpc/program.proto\x12\aprogram\"\a\n" +
	"\x05Empty\"i\n" +
	"\x13ListHomeProgramsReq\x12\x16\n" +
	"\x06areaId\x18\x01 \x01(\x03R\x06areaId\x12:\n" +
	"\x18parentProgramCategoryIds\x18\x02 \x03(\x03R\x18parentProgramCategoryIds\"\xc5\x02\n" +
	"\x0fPageProgramsReq\x12\x1e\n" +
	"\n" +
	"pageNumber\x18\x01 \x01(\x03R\n" +
	"pageNumber\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\x16\n" +
	"\x06areaId\x18\x03 \x01(\x03R\x06areaId\x128\n" +
	"\x17parentProgramCategoryId\x18\x04 \x01(\x03R\x17parentProgramCategoryId\x12,\n" +
	"\x11programCategoryId\x18\x05 \x01(\x03R\x11programCategoryId\x12\x1a\n" +
	"\btimeType\x18\x06 \x01(\x03R\btimeType\x12$\n" +
	"\rstartDateTime\x18\a \x01(\tR\rstartDateTime\x12 \n" +
	"\vendDateTime\x18\b \x01(\tR\vendDateTime\x12\x12\n" +
	"\x04type\x18\t \x01(\x03R\x04type\"%\n" +
	"\x13GetProgramDetailReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"@\n" +
	" ListTicketCategoriesByProgramReq\x12\x1c\n" +
	"\tprogramId\x18\x01 \x01(\x03R\tprogramId\"i\n" +
	"\x13ProgramCategoryInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bparentId\x18\x02 \x01(\x03R\bparentId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x04 \x01(\x03R\x04type\"i\n" +
	"\x11ProgramSimpleInfo\x12\x1c\n" +
	"\tprogramId\x18\x01 \x01(\x03R\tprogramId\x12\x16\n" +
	"\x06areaId\x18\x02 \x01(\x03R\x06areaId\x12\x1e\n" +
	"\n" +
	"areaIdName\x18\x03 \x01(\tR\n" +
	"areaIdName\"\xa0\x01\n" +
	"\x10ProgramGroupInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12T\n" +
	"\x17programSimpleInfoVoList\x18\x02 \x03(\v2\x1a.program.ProgramSimpleInfoR\x17programSimpleInfoVoList\x12&\n" +
	"\x0erecentShowTime\x18\x03 \x01(\tR\x0erecentShowTime\"\xa0\x01\n" +
	"\x12ProgramHomeSection\x12\"\n" +
	"\fcategoryName\x18\x01 \x01(\tR\fcategoryName\x12\x1e\n" +
	"\n" +
	"categoryId\x18\x02 \x01(\x03R\n" +
	"categoryId\x12F\n" +
	"\x11programListVoList\x18\x03 \x03(\v2\x18.program.ProgramListInfoR\x11programListVoList\"X\n" +
	"\x12TicketCategoryInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tintroduce\x18\x02 \x01(\tR\tintroduce\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\"\x98\x01\n" +
	"\bSeatInfo\x12\x16\n" +
	"\x06seatId\x18\x01 \x01(\x03R\x06seatId\x12*\n" +
	"\x10ticketCategoryId\x18\x02 \x01(\x03R\x10ticketCategoryId\x12\x18\n" +
	"\arowCode\x18\x03 \x01(\x03R\arowCode\x12\x18\n" +
	"\acolCode\x18\x04 \x01(\x03R\acolCode\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x03R\x05price\"\xb2\x01\n" +
	"\x18TicketCategoryDetailInfo\x12\x1c\n" +
	"\tprogramId\x18\x01 \x01(\x03R\tprogramId\x12\x1c\n" +
	"\tintroduce\x18\x02 \x01(\tR\tintroduce\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12 \n" +
	"\vtotalNumber\x18\x04 \x01(\x03R\vtotalNumber\x12\"\n" +
	"\fremainNumber\x18\x05 \x01(\x03R\fremainNumber\"\xad\x01\n" +
	"!ProgramPreorderTicketCategoryInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tintroduce\x18\x02 \x01(\tR\tintroduce\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x12 \n" +
	"\vtotalNumber\x18\x04 \x01(\x03R\vtotalNumber\x12\"\n" +
	"\fremainNumber\x18\x05 \x01(\x03R\fremainNumber\"K\n" +
	"\x17ProgramCategoryListResp\x120\n" +
	"\x04list\x18\x01 \x03(\v2\x1c.program.ProgramCategoryInfoR\x04list\"\xbf\x04\n" +
	"\x0fProgramListInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05actor\x18\x03 \x01(\tR\x05actor\x12\x14\n" +
	"\x05place\x18\x04 \x01(\tR\x05place\x12 \n" +
	"\vitemPicture\x18\x05 \x01(\tR\vitemPicture\x12\x16\n" +
	"\x06areaId\x18\x06 \x01(\x03R\x06areaId\x12\x1a\n" +
	"\bareaName\x18\a \x01(\tR\bareaName\x12,\n" +
	"\x11programCategoryId\x18\b \x01(\x03R\x11programCategoryId\x120\n" +
	"\x13programCategoryName\x18\t \x01(\tR\x13programCategoryName\x128\n" +
	"\x17parentProgramCategoryId\x18\n" +
	" \x01(\x03R\x17parentProgramCategoryId\x12<\n" +
	"\x19parentProgramCategoryName\x18\v \x01(\tR\x19parentProgramCategoryName\x12\x1a\n" +
	"\bshowTime\x18\f \x01(\tR\bshowTime\x12 \n" +
	"\vshowDayTime\x18\r \x01(\tR\vshowDayTime\x12\"\n" +
	"\fshowWeekTime\x18\x0e \x01(\tR\fshowWeekTime\x12\x1a\n" +
	"\bminPrice\x18\x0f \x01(\x03R\bminPrice\x12\x1a\n" +
	"\bmaxPrice\x18\x10 \x01(\x03R\bmaxPrice\x12\x12\n" +
	"\x04esId\x18\x11 \x01(\x03R\x04esId\"N\n" +
	"\x13ProgramHomeListResp\x127\n" +
	"\bsections\x18\x01 \x03(\v2\x1b.program.ProgramHomeSectionR\bsections\"\x93\x01\n" +
	"\x0fProgramPageResp\x12\x18\n" +
	"\apageNum\x18\x01 \x01(\x03R\apageNum\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\x1c\n" +
	"\ttotalSize\x18\x03 \x01(\x03R\ttotalSize\x12,\n" +
	"\x04list\x18\x04 \x03(\v2\x18.program.ProgramListInfoR\x04list\"U\n" +
	"\x1cTicketCategoryDetailListResp\x125\n" +
	"\x04list\x18\x01 \x03(\v2!.program.TicketCategoryDetailInfoR\x04list\"\xd1\x04\n" +
	"\x13ProgramPreorderInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12&\n" +
	"\x0eprogramGroupId\x18\x02 \x01(\x03R\x0eprogramGroupId\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05actor\x18\x04 \x01(\tR\x05actor\x12\x14\n" +
	"\x05place\x18\x05 \x01(\tR\x05place\x12 \n" +
	"\vitemPicture\x18\x06 \x01(\tR\vitemPicture\x12\x1a\n" +
	"\bshowTime\x18\a \x01(\tR\bshowTime\x12 \n" +
	"\vshowDayTime\x18\b \x01(\tR\vshowDayTime\x12\"\n" +
	"\fshowWeekTime\x18\t \x01(\tR\fshowWeekTime\x12>\n" +
	"\x1aperOrderLimitPurchaseCount\x18\n" +
	" \x01(\x03R\x1aperOrderLimitPurchaseCount\x12B\n" +
	"\x1cperAccountLimitPurchaseCount\x18\v \x01(\x03R\x1cperAccountLimitPurchaseCount\x12*\n" +
	"\x10permitChooseSeat\x18\f \x01(\x03R\x10permitChooseSeat\x12,\n" +
	"\x11chooseSeatExplain\x18\r \x01(\tR\x11chooseSeatExplain\x12^\n" +
	"\x14ticketCategoryVoList\x18\x0e \x03(\v2*.program.ProgramPreorderTicketCategoryInfoR\x14ticketCategoryVoList\"\xc1\x01\n" +
	"\x1bAutoAssignAndFreezeSeatsReq\x12\x1c\n" +
	"\tprogramId\x18\x01 \x01(\x03R\tprogramId\x12*\n" +
	"\x10ticketCategoryId\x18\x02 \x01(\x03R\x10ticketCategoryId\x12\x14\n" +
	"\x05count\x18\x03 \x01(\x03R\x05count\x12\x1c\n" +
	"\trequestNo\x18\x04 \x01(\tR\trequestNo\x12$\n" +
	"\rfreezeSeconds\x18\x05 \x01(\x03R\rfreezeSeconds\"\x89\x01\n" +
	"\x1cAutoAssignAndFreezeSeatsResp\x12 \n" +
	"\vfreezeToken\x18\x01 \x01(\tR\vfreezeToken\x12\x1e\n" +
	"\n" +
	"expireTime\x18\x02 \x01(\tR\n" +
	"expireTime\x12'\n" +
	"\x05seats\x18\x03 \x03(\v2\x11.program.SeatInfoR\x05seats\"^\n" +
	"\x14ReleaseSeatFreezeReq\x12 \n" +
	"\vfreezeToken\x18\x01 \x01(\tR\vfreezeToken\x12$\n" +
	"\rreleaseReason\x18\x02 \x01(\tR\rreleaseReason\"1\n" +
	"\x15ReleaseSeatFreezeResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x87\x12\n" +
	"\x11ProgramDetailInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12&\n" +
	"\x0eprogramGroupId\x18\x02 \x01(\x03R\x0eprogramGroupId\x12\x14\n" +
	"\x05prime\x18\x03 \x01(\x03R\x05prime\x12A\n" +
	"\x0eprogramGroupVo\x18\x04 \x01(\v2\x19.program.ProgramGroupInfoR\x0eprogramGroupVo\x12\x14\n" +
	"\x05title\x18\x05 \x01(\tR\x05title\x12\x14\n" +
	"\x05actor\x18\x06 \x01(\tR\x05actor\x12\x14\n" +
	"\x05place\x18\a \x01(\tR\x05place\x12 \n" +
	"\vitemPicture\x18\b \x01(\tR\vitemPicture\x12\x18\n" +
	"\apreSell\x18\t \x01(\x03R\apreSell\x12.\n" +
	"\x12preSellInstruction\x18\n" +
	" \x01(\tR\x12preSellInstruction\x12(\n" +
	"\x0fimportantNotice\x18\v \x01(\tR\x0fimportantNotice\x12\x16\n" +
	"\x06areaId\x18\f \x01(\x03R\x06areaId\x12\x1a\n" +
	"\bareaName\x18\r \x01(\tR\bareaName\x12,\n" +
	"\x11programCategoryId\x18\x0e \x01(\x03R\x11programCategoryId\x120\n" +
	"\x13programCategoryName\x18\x0f \x01(\tR\x13programCategoryName\x128\n" +
	"\x17parentProgramCategoryId\x18\x10 \x01(\x03R\x17parentProgramCategoryId\x12<\n" +
	"\x19parentProgramCategoryName\x18\x11 \x01(\tR\x19parentProgramCategoryName\x12\x16\n" +
	"\x06detail\x18\x12 \x01(\tR\x06detail\x12>\n" +
	"\x1aperOrderLimitPurchaseCount\x18\x13 \x01(\x03R\x1aperOrderLimitPurchaseCount\x12B\n" +
	"\x1cperAccountLimitPurchaseCount\x18\x14 \x01(\x03R\x1cperAccountLimitPurchaseCount\x12*\n" +
	"\x10refundTicketRule\x18\x15 \x01(\tR\x10refundTicketRule\x120\n" +
	"\x13deliveryInstruction\x18\x16 \x01(\tR\x13deliveryInstruction\x12\x1c\n" +
	"\tentryRule\x18\x17 \x01(\tR\tentryRule\x12$\n" +
	"\rchildPurchase\x18\x18 \x01(\tR\rchildPurchase\x122\n" +
	"\x14invoiceSpecification\x18\x19 \x01(\tR\x14invoiceSpecification\x126\n" +
	"\x16realTicketPurchaseRule\x18\x1a \x01(\tR\x16realTicketPurchaseRule\x12:\n" +
	"\x18abnormalOrderDescription\x18\x1b \x01(\tR\x18abnormalOrderDescription\x12\"\n" +
	"\fkindReminder\x18\x1c \x01(\tR\fkindReminder\x120\n" +
	"\x13performanceDuration\x18\x1d \x01(\tR\x13performanceDuration\x12\x1c\n" +
	"\tentryTime\x18\x1e \x01(\tR\tentryTime\x120\n" +
	"\x13minPerformanceCount\x18\x1f \x01(\x03R\x13minPerformanceCount\x12\x1c\n" +
	"\tmainActor\x18  \x01(\tR\tmainActor\x126\n" +
	"\x16minPerformanceDuration\x18! \x01(\tR\x16minPerformanceDuration\x12&\n" +
	"\x0eprohibitedItem\x18\" \x01(\tR\x0eprohibitedItem\x122\n" +
	"\x14depositSpecification\x18# \x01(\tR\x14depositSpecification\x12\x1e\n" +
	"\n" +
	"totalCount\x18$ \x01(\x03R\n" +
	"totalCount\x12\"\n" +
	"\fpermitRefund\x18% \x01(\x03R\fpermitRefund\x12$\n" +
	"\rrefundExplain\x18& \x01(\tR\rrefundExplain\x124\n" +
	"\x15relNameTicketEntrance\x18' \x01(\x03R\x15relNameTicketEntrance\x12B\n" +
	"\x1crelNameTicketEntranceExplain\x18( \x01(\tR\x1crelNameTicketEntranceExplain\x12*\n" +
	"\x10permitChooseSeat\x18) \x01(\x03R\x10permitChooseSeat\x12,\n" +
	"\x11chooseSeatExplain\x18* \x01(\tR\x11chooseSeatExplain\x12:\n" +
	"\x18electronicDeliveryTicket\x18+ \x01(\x03R\x18electronicDeliveryTicket\x12H\n" +
	"\x1felectronicDeliveryTicketExplain\x18, \x01(\tR\x1felectronicDeliveryTicketExplain\x12,\n" +
	"\x11electronicInvoice\x18- \x01(\x03R\x11electronicInvoice\x12:\n" +
	"\x18electronicInvoiceExplain\x18. \x01(\tR\x18electronicInvoiceExplain\x12\x1a\n" +
	"\bhighHeat\x18/ \x01(\x03R\bhighHeat\x12$\n" +
	"\rprogramStatus\x180 \x01(\x03R\rprogramStatus\x12\x1c\n" +
	"\tissueTime\x181 \x01(\tR\tissueTime\x12\x1a\n" +
	"\bshowTime\x182 \x01(\tR\bshowTime\x12 \n" +
	"\vshowDayTime\x183 \x01(\tR\vshowDayTime\x12\"\n" +
	"\fshowWeekTime\x184 \x01(\tR\fshowWeekTime\x12O\n" +
	"\x14ticketCategoryVoList\x185 \x03(\v2\x1b.program.TicketCategoryInfoR\x14ticketCategoryVoList2\xbb\x05\n" +
	"\n" +
	"ProgramRpc\x12I\n" +
	"\x15ListProgramCategories\x12\x0e.program.Empty\x1a .program.ProgramCategoryListResp\x12N\n" +
	"\x10ListHomePrograms\x12\x1c.program.ListHomeProgramsReq\x1a\x1c.program.ProgramHomeListResp\x12B\n" +
	"\fPagePrograms\x12\x18.program.PageProgramsReq\x1a\x18.program.ProgramPageResp\x12L\n" +
	"\x10GetProgramDetail\x12\x1c.program.GetProgramDetailReq\x1a\x1a.program.ProgramDetailInfo\x12P\n" +
	"\x12GetProgramPreorder\x12\x1c.program.GetProgramDetailReq\x1a\x1c.program.ProgramPreorderInfo\x12q\n" +
	"\x1dListTicketCategoriesByProgram\x12).program.ListTicketCategoriesByProgramReq\x1a%.program.TicketCategoryDetailListResp\x12g\n" +
	"\x18AutoAssignAndFreezeSeats\x12$.program.AutoAssignAndFreezeSeatsReq\x1a%.program.AutoAssignAndFreezeSeatsResp\x12R\n" +
	"\x11ReleaseSeatFreeze\x12\x1d.program.ReleaseSeatFreezeReq\x1a\x1e.program.ReleaseSeatFreezeRespB\x06Z\x04./pbb\x06proto3"

var (
	file_services_program_rpc_program_proto_rawDescOnce sync.Once
	file_services_program_rpc_program_proto_rawDescData []byte
)

func file_services_program_rpc_program_proto_rawDescGZIP() []byte {
	file_services_program_rpc_program_proto_rawDescOnce.Do(func() {
		file_services_program_rpc_program_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_services_program_rpc_program_proto_rawDesc), len(file_services_program_rpc_program_proto_rawDesc)))
	})
	return file_services_program_rpc_program_proto_rawDescData
}

var file_services_program_rpc_program_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_services_program_rpc_program_proto_goTypes = []any{
	(*Empty)(nil),                             // 0: program.Empty
	(*ListHomeProgramsReq)(nil),               // 1: program.ListHomeProgramsReq
	(*PageProgramsReq)(nil),                   // 2: program.PageProgramsReq
	(*GetProgramDetailReq)(nil),               // 3: program.GetProgramDetailReq
	(*ListTicketCategoriesByProgramReq)(nil),  // 4: program.ListTicketCategoriesByProgramReq
	(*ProgramCategoryInfo)(nil),               // 5: program.ProgramCategoryInfo
	(*ProgramSimpleInfo)(nil),                 // 6: program.ProgramSimpleInfo
	(*ProgramGroupInfo)(nil),                  // 7: program.ProgramGroupInfo
	(*ProgramHomeSection)(nil),                // 8: program.ProgramHomeSection
	(*TicketCategoryInfo)(nil),                // 9: program.TicketCategoryInfo
	(*SeatInfo)(nil),                          // 10: program.SeatInfo
	(*TicketCategoryDetailInfo)(nil),          // 11: program.TicketCategoryDetailInfo
	(*ProgramPreorderTicketCategoryInfo)(nil), // 12: program.ProgramPreorderTicketCategoryInfo
	(*ProgramCategoryListResp)(nil),           // 13: program.ProgramCategoryListResp
	(*ProgramListInfo)(nil),                   // 14: program.ProgramListInfo
	(*ProgramHomeListResp)(nil),               // 15: program.ProgramHomeListResp
	(*ProgramPageResp)(nil),                   // 16: program.ProgramPageResp
	(*TicketCategoryDetailListResp)(nil),      // 17: program.TicketCategoryDetailListResp
	(*ProgramPreorderInfo)(nil),               // 18: program.ProgramPreorderInfo
	(*AutoAssignAndFreezeSeatsReq)(nil),       // 19: program.AutoAssignAndFreezeSeatsReq
	(*AutoAssignAndFreezeSeatsResp)(nil),      // 20: program.AutoAssignAndFreezeSeatsResp
	(*ReleaseSeatFreezeReq)(nil),              // 21: program.ReleaseSeatFreezeReq
	(*ReleaseSeatFreezeResp)(nil),             // 22: program.ReleaseSeatFreezeResp
	(*ProgramDetailInfo)(nil),                 // 23: program.ProgramDetailInfo
}
var file_services_program_rpc_program_proto_depIdxs = []int32{
	6,  // 0: program.ProgramGroupInfo.programSimpleInfoVoList:type_name -> program.ProgramSimpleInfo
	14, // 1: program.ProgramHomeSection.programListVoList:type_name -> program.ProgramListInfo
	5,  // 2: program.ProgramCategoryListResp.list:type_name -> program.ProgramCategoryInfo
	8,  // 3: program.ProgramHomeListResp.sections:type_name -> program.ProgramHomeSection
	14, // 4: program.ProgramPageResp.list:type_name -> program.ProgramListInfo
	11, // 5: program.TicketCategoryDetailListResp.list:type_name -> program.TicketCategoryDetailInfo
	12, // 6: program.ProgramPreorderInfo.ticketCategoryVoList:type_name -> program.ProgramPreorderTicketCategoryInfo
	10, // 7: program.AutoAssignAndFreezeSeatsResp.seats:type_name -> program.SeatInfo
	7,  // 8: program.ProgramDetailInfo.programGroupVo:type_name -> program.ProgramGroupInfo
	9,  // 9: program.ProgramDetailInfo.ticketCategoryVoList:type_name -> program.TicketCategoryInfo
	0,  // 10: program.ProgramRpc.ListProgramCategories:input_type -> program.Empty
	1,  // 11: program.ProgramRpc.ListHomePrograms:input_type -> program.ListHomeProgramsReq
	2,  // 12: program.ProgramRpc.PagePrograms:input_type -> program.PageProgramsReq
	3,  // 13: program.ProgramRpc.GetProgramDetail:input_type -> program.GetProgramDetailReq
	3,  // 14: program.ProgramRpc.GetProgramPreorder:input_type -> program.GetProgramDetailReq
	4,  // 15: program.ProgramRpc.ListTicketCategoriesByProgram:input_type -> program.ListTicketCategoriesByProgramReq
	19, // 16: program.ProgramRpc.AutoAssignAndFreezeSeats:input_type -> program.AutoAssignAndFreezeSeatsReq
	21, // 17: program.ProgramRpc.ReleaseSeatFreeze:input_type -> program.ReleaseSeatFreezeReq
	13, // 18: program.ProgramRpc.ListProgramCategories:output_type -> program.ProgramCategoryListResp
	15, // 19: program.ProgramRpc.ListHomePrograms:output_type -> program.ProgramHomeListResp
	16, // 20: program.ProgramRpc.PagePrograms:output_type -> program.ProgramPageResp
	23, // 21: program.ProgramRpc.GetProgramDetail:output_type -> program.ProgramDetailInfo
	18, // 22: program.ProgramRpc.GetProgramPreorder:output_type -> program.ProgramPreorderInfo
	17, // 23: program.ProgramRpc.ListTicketCategoriesByProgram:output_type -> program.TicketCategoryDetailListResp
	20, // 24: program.ProgramRpc.AutoAssignAndFreezeSeats:output_type -> program.AutoAssignAndFreezeSeatsResp
	22, // 25: program.ProgramRpc.ReleaseSeatFreeze:output_type -> program.ReleaseSeatFreezeResp
	18, // [18:26] is the sub-list for method output_type
	10, // [10:18] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_services_program_rpc_program_proto_init() }
func file_services_program_rpc_program_proto_init() {
	if File_services_program_rpc_program_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_services_program_rpc_program_proto_rawDesc), len(file_services_program_rpc_program_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_program_rpc_program_proto_goTypes,
		DependencyIndexes: file_services_program_rpc_program_proto_depIdxs,
		MessageInfos:      file_services_program_rpc_program_proto_msgTypes,
	}.Build()
	File_services_program_rpc_program_proto = out.File
	file_services_program_rpc_program_proto_goTypes = nil
	file_services_program_rpc_program_proto_depIdxs = nil
}
