// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type AddTicketUserReq struct {
	UserID   int64  `json:"userId"`
	RelName  string `json:"relName"`
	IdType   int64  `json:"idType"`
	IdNumber string `json:"idNumber"`
}

type AuthenticationReq struct {
	ID       int64  `json:"id"`
	RelName  string `json:"relName"`
	IdNumber string `json:"idNumber"`
}

type BoolResp struct {
	Success bool `json:"success"`
}

type DeleteTicketUserReq struct {
	ID int64 `json:"id"`
}

type GetUserAndTicketUserListReq struct {
	UserID int64 `json:"userId"`
}

type GetUserAndTicketUserListResp struct {
	UserVo           UserVo         `json:"userVo"`
	TicketUserVoList []TicketUserVo `json:"ticketUserVoList"`
}

type GetUserByIDReq struct {
	ID int64 `json:"id"`
}

type GetUserByMobileReq struct {
	Mobile string `json:"mobile"`
}

type ListTicketUsersReq struct {
	UserID int64 `json:"userId"`
}

type TicketUserListResp struct {
	List []TicketUserVo `json:"list"`
}

type TicketUserVo struct {
	ID       int64  `json:"id"`
	UserID   int64  `json:"userId"`
	RelName  string `json:"relName,optional"`
	IdType   int64  `json:"idType,optional"`
	IdNumber string `json:"idNumber,optional"`
}

type UpdateEmailReq struct {
	ID          int64  `json:"id"`
	Email       string `json:"email"`
	EmailStatus int64  `json:"emailStatus,optional"`
}

type UpdateMobileReq struct {
	ID     int64  `json:"id"`
	Mobile string `json:"mobile"`
}

type UpdatePasswordReq struct {
	ID       int64  `json:"id"`
	Password string `json:"password"`
}

type UpdateUserReq struct {
	ID      int64  `json:"id"`
	Name    string `json:"name,optional"`
	Gender  int64  `json:"gender,optional"`
	Mobile  string `json:"mobile,optional"`
	Address string `json:"address,optional"`
}

type UserExistReq struct {
	Mobile string `json:"mobile"`
}

type UserLoginReq struct {
	Code     string `json:"code"`
	Mobile   string `json:"mobile,optional"`
	Email    string `json:"email,optional"`
	Password string `json:"password"`
}

type UserLoginResp struct {
	UserID int64  `json:"userId"`
	Token  string `json:"token"`
}

type UserLogoutReq struct {
	Code  string `json:"code"`
	Token string `json:"token"`
}

type UserRegisterReq struct {
	Mobile          string `json:"mobile"`
	Password        string `json:"password"`
	ConfirmPassword string `json:"confirmPassword"`
	Mail            string `json:"mail,optional"`
	MailStatus      int64  `json:"mailStatus,optional"`
}

type UserVo struct {
	ID                      int64  `json:"id"`
	Name                    string `json:"name,optional"`
	RelName                 string `json:"relName,optional"`
	Gender                  int64  `json:"gender,optional"`
	Mobile                  string `json:"mobile,optional"`
	EmailStatus             int64  `json:"emailStatus,optional"`
	Email                   string `json:"email,optional"`
	RelAuthenticationStatus int64  `json:"relAuthenticationStatus,optional"`
	IdNumber                string `json:"idNumber,optional"`
	Address                 string `json:"address,optional"`
}
