// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.4
// source: order.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BoolResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoolResp) Reset() {
	*x = BoolResp{}
	mi := &file_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoolResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoolResp) ProtoMessage() {}

func (x *BoolResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoolResp.ProtoReflect.Descriptor instead.
func (*BoolResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{0}
}

func (x *BoolResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateOrderReq struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ProgramId        int64                  `protobuf:"varint,2,opt,name=programId,proto3" json:"programId,omitempty"`
	TicketCategoryId int64                  `protobuf:"varint,3,opt,name=ticketCategoryId,proto3" json:"ticketCategoryId,omitempty"`
	TicketUserIds    []int64                `protobuf:"varint,4,rep,packed,name=ticketUserIds,proto3" json:"ticketUserIds,omitempty"`
	DistributionMode string                 `protobuf:"bytes,5,opt,name=distributionMode,proto3" json:"distributionMode,omitempty"`
	TakeTicketMode   string                 `protobuf:"bytes,6,opt,name=takeTicketMode,proto3" json:"takeTicketMode,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateOrderReq) Reset() {
	*x = CreateOrderReq{}
	mi := &file_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderReq) ProtoMessage() {}

func (x *CreateOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderReq.ProtoReflect.Descriptor instead.
func (*CreateOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateOrderReq) GetProgramId() int64 {
	if x != nil {
		return x.ProgramId
	}
	return 0
}

func (x *CreateOrderReq) GetTicketCategoryId() int64 {
	if x != nil {
		return x.TicketCategoryId
	}
	return 0
}

func (x *CreateOrderReq) GetTicketUserIds() []int64 {
	if x != nil {
		return x.TicketUserIds
	}
	return nil
}

func (x *CreateOrderReq) GetDistributionMode() string {
	if x != nil {
		return x.DistributionMode
	}
	return ""
}

func (x *CreateOrderReq) GetTakeTicketMode() string {
	if x != nil {
		return x.TakeTicketMode
	}
	return ""
}

type CreateOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNumber   int64                  `protobuf:"varint,1,opt,name=orderNumber,proto3" json:"orderNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderResp) Reset() {
	*x = CreateOrderResp{}
	mi := &file_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResp) ProtoMessage() {}

func (x *CreateOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResp.ProtoReflect.Descriptor instead.
func (*CreateOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrderResp) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

type ListOrdersReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	PageNumber    int64                  `protobuf:"varint,2,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	PageSize      int64                  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	OrderStatus   int64                  `protobuf:"varint,4,opt,name=orderStatus,proto3" json:"orderStatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersReq) Reset() {
	*x = ListOrdersReq{}
	mi := &file_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersReq) ProtoMessage() {}

func (x *ListOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersReq.ProtoReflect.Descriptor instead.
func (*ListOrdersReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{3}
}

func (x *ListOrdersReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListOrdersReq) GetPageNumber() int64 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *ListOrdersReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrdersReq) GetOrderStatus() int64 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

type OrderListInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	OrderNumber        int64                  `protobuf:"varint,1,opt,name=orderNumber,proto3" json:"orderNumber,omitempty"`
	ProgramId          int64                  `protobuf:"varint,2,opt,name=programId,proto3" json:"programId,omitempty"`
	ProgramTitle       string                 `protobuf:"bytes,3,opt,name=programTitle,proto3" json:"programTitle,omitempty"`
	ProgramItemPicture string                 `protobuf:"bytes,4,opt,name=programItemPicture,proto3" json:"programItemPicture,omitempty"`
	ProgramPlace       string                 `protobuf:"bytes,5,opt,name=programPlace,proto3" json:"programPlace,omitempty"`
	ProgramShowTime    string                 `protobuf:"bytes,6,opt,name=programShowTime,proto3" json:"programShowTime,omitempty"`
	TicketCount        int64                  `protobuf:"varint,7,opt,name=ticketCount,proto3" json:"ticketCount,omitempty"`
	OrderPrice         int64                  `protobuf:"varint,8,opt,name=orderPrice,proto3" json:"orderPrice,omitempty"`
	OrderStatus        int64                  `protobuf:"varint,9,opt,name=orderStatus,proto3" json:"orderStatus,omitempty"`
	OrderExpireTime    string                 `protobuf:"bytes,10,opt,name=orderExpireTime,proto3" json:"orderExpireTime,omitempty"`
	CreateOrderTime    string                 `protobuf:"bytes,11,opt,name=createOrderTime,proto3" json:"createOrderTime,omitempty"`
	CancelOrderTime    string                 `protobuf:"bytes,12,opt,name=cancelOrderTime,proto3" json:"cancelOrderTime,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OrderListInfo) Reset() {
	*x = OrderListInfo{}
	mi := &file_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListInfo) ProtoMessage() {}

func (x *OrderListInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListInfo.ProtoReflect.Descriptor instead.
func (*OrderListInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{4}
}

func (x *OrderListInfo) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

func (x *OrderListInfo) GetProgramId() int64 {
	if x != nil {
		return x.ProgramId
	}
	return 0
}

func (x *OrderListInfo) GetProgramTitle() string {
	if x != nil {
		return x.ProgramTitle
	}
	return ""
}

func (x *OrderListInfo) GetProgramItemPicture() string {
	if x != nil {
		return x.ProgramItemPicture
	}
	return ""
}

func (x *OrderListInfo) GetProgramPlace() string {
	if x != nil {
		return x.ProgramPlace
	}
	return ""
}

func (x *OrderListInfo) GetProgramShowTime() string {
	if x != nil {
		return x.ProgramShowTime
	}
	return ""
}

func (x *OrderListInfo) GetTicketCount() int64 {
	if x != nil {
		return x.TicketCount
	}
	return 0
}

func (x *OrderListInfo) GetOrderPrice() int64 {
	if x != nil {
		return x.OrderPrice
	}
	return 0
}

func (x *OrderListInfo) GetOrderStatus() int64 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *OrderListInfo) GetOrderExpireTime() string {
	if x != nil {
		return x.OrderExpireTime
	}
	return ""
}

func (x *OrderListInfo) GetCreateOrderTime() string {
	if x != nil {
		return x.CreateOrderTime
	}
	return ""
}

func (x *OrderListInfo) GetCancelOrderTime() string {
	if x != nil {
		return x.CancelOrderTime
	}
	return ""
}

type ListOrdersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageNum       int64                  `protobuf:"varint,1,opt,name=pageNum,proto3" json:"pageNum,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	TotalSize     int64                  `protobuf:"varint,3,opt,name=totalSize,proto3" json:"totalSize,omitempty"`
	List          []*OrderListInfo       `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResp) Reset() {
	*x = ListOrdersResp{}
	mi := &file_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResp) ProtoMessage() {}

func (x *ListOrdersResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResp.ProtoReflect.Descriptor instead.
func (*ListOrdersResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{5}
}

func (x *ListOrdersResp) GetPageNum() int64 {
	if x != nil {
		return x.PageNum
	}
	return 0
}

func (x *ListOrdersResp) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrdersResp) GetTotalSize() int64 {
	if x != nil {
		return x.TotalSize
	}
	return 0
}

func (x *ListOrdersResp) GetList() []*OrderListInfo {
	if x != nil {
		return x.List
	}
	return nil
}

type GetOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OrderNumber   int64                  `protobuf:"varint,2,opt,name=orderNumber,proto3" json:"orderNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderReq) Reset() {
	*x = GetOrderReq{}
	mi := &file_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderReq) ProtoMessage() {}

func (x *GetOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderReq.ProtoReflect.Descriptor instead.
func (*GetOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{6}
}

func (x *GetOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOrderReq) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

type GetOrderServiceViewReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OrderNumber   int64                  `protobuf:"varint,2,opt,name=orderNumber,proto3" json:"orderNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderServiceViewReq) Reset() {
	*x = GetOrderServiceViewReq{}
	mi := &file_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderServiceViewReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderServiceViewReq) ProtoMessage() {}

func (x *GetOrderServiceViewReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderServiceViewReq.ProtoReflect.Descriptor instead.
func (*GetOrderServiceViewReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{7}
}

func (x *GetOrderServiceViewReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetOrderServiceViewReq) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

type GetOrderCacheReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNumber   int64                  `protobuf:"varint,1,opt,name=orderNumber,proto3" json:"orderNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderCacheReq) Reset() {
	*x = GetOrderCacheReq{}
	mi := &file_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderCacheReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderCacheReq) ProtoMessage() {}

func (x *GetOrderCacheReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderCacheReq.ProtoReflect.Descriptor instead.
func (*GetOrderCacheReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrderCacheReq) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

type GetOrderCacheResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cache         string                 `protobuf:"bytes,1,opt,name=cache,proto3" json:"cache,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderCacheResp) Reset() {
	*x = GetOrderCacheResp{}
	mi := &file_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderCacheResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderCacheResp) ProtoMessage() {}

func (x *GetOrderCacheResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderCacheResp.ProtoReflect.Descriptor instead.
func (*GetOrderCacheResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrderCacheResp) GetCache() string {
	if x != nil {
		return x.Cache
	}
	return ""
}

type OrderServiceViewResp struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OrderNumber         int64                  `protobuf:"varint,1,opt,name=orderNumber,proto3" json:"orderNumber,omitempty"`
	OrderStatus         int64                  `protobuf:"varint,2,opt,name=orderStatus,proto3" json:"orderStatus,omitempty"`
	PayStatus           int64                  `protobuf:"varint,3,opt,name=payStatus,proto3" json:"payStatus,omitempty"`
	TicketStatus        int64                  `protobuf:"varint,4,opt,name=ticketStatus,proto3" json:"ticketStatus,omitempty"`
	ProgramTitle        string                 `protobuf:"bytes,5,opt,name=programTitle,proto3" json:"programTitle,omitempty"`
	ProgramShowTime     string                 `protobuf:"bytes,6,opt,name=programShowTime,proto3" json:"programShowTime,omitempty"`
	TicketCount         int64                  `protobuf:"varint,7,opt,name=ticketCount,proto3" json:"ticketCount,omitempty"`
	OrderPrice          int64                  `protobuf:"varint,8,opt,name=orderPrice,proto3" json:"orderPrice,omitempty"`
	CanRefund           bool                   `protobuf:"varint,9,opt,name=canRefund,proto3" json:"canRefund,omitempty"`
	RefundBlockedReason string                 `protobuf:"bytes,10,opt,name=refundBlockedReason,proto3" json:"refundBlockedReason,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OrderServiceViewResp) Reset() {
	*x = OrderServiceViewResp{}
	mi := &file_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderServiceViewResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderServiceViewResp) ProtoMessage() {}

func (x *OrderServiceViewResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderServiceViewResp.ProtoReflect.Descriptor instead.
func (*OrderServiceViewResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{10}
}

func (x *OrderServiceViewResp) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

func (x *OrderServiceViewResp) GetOrderStatus() int64 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *OrderServiceViewResp) GetPayStatus() int64 {
	if x != nil {
		return x.PayStatus
	}
	return 0
}

func (x *OrderServiceViewResp) GetTicketStatus() int64 {
	if x != nil {
		return x.TicketStatus
	}
	return 0
}

func (x *OrderServiceViewResp) GetProgramTitle() string {
	if x != nil {
		return x.ProgramTitle
	}
	return ""
}

func (x *OrderServiceViewResp) GetProgramShowTime() string {
	if x != nil {
		return x.ProgramShowTime
	}
	return ""
}

func (x *OrderServiceViewResp) GetTicketCount() int64 {
	if x != nil {
		return x.TicketCount
	}
	return 0
}

func (x *OrderServiceViewResp) GetOrderPrice() int64 {
	if x != nil {
		return x.OrderPrice
	}
	return 0
}

func (x *OrderServiceViewResp) GetCanRefund() bool {
	if x != nil {
		return x.CanRefund
	}
	return false
}

func (x *OrderServiceViewResp) GetRefundBlockedReason() string {
	if x != nil {
		return x.RefundBlockedReason
	}
	return ""
}

type OrderTicketInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TicketUserId       int64                  `protobuf:"varint,1,opt,name=ticketUserId,proto3" json:"ticketUserId,omitempty"`
	TicketUserName     string                 `protobuf:"bytes,2,opt,name=ticketUserName,proto3" json:"ticketUserName,omitempty"`
	TicketUserIdNumber string                 `protobuf:"bytes,3,opt,name=ticketUserIdNumber,proto3" json:"ticketUserIdNumber,omitempty"`
	TicketCategoryId   int64                  `protobuf:"varint,4,opt,name=ticketCategoryId,proto3" json:"ticketCategoryId,omitempty"`
	TicketCategoryName string                 `protobuf:"bytes,5,opt,name=ticketCategoryName,proto3" json:"ticketCategoryName,omitempty"`
	TicketPrice        int64                  `protobuf:"varint,6,opt,name=ticketPrice,proto3" json:"ticketPrice,omitempty"`
	SeatId             int64                  `protobuf:"varint,7,opt,name=seatId,proto3" json:"seatId,omitempty"`
	SeatRow            int64                  `protobuf:"varint,8,opt,name=seatRow,proto3" json:"seatRow,omitempty"`
	SeatCol            int64                  `protobuf:"varint,9,opt,name=seatCol,proto3" json:"seatCol,omitempty"`
	SeatPrice          int64                  `protobuf:"varint,10,opt,name=seatPrice,proto3" json:"seatPrice,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OrderTicketInfo) Reset() {
	*x = OrderTicketInfo{}
	mi := &file_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderTicketInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderTicketInfo) ProtoMessage() {}

func (x *OrderTicketInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderTicketInfo.ProtoReflect.Descriptor instead.
func (*OrderTicketInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{11}
}

func (x *OrderTicketInfo) GetTicketUserId() int64 {
	if x != nil {
		return x.TicketUserId
	}
	return 0
}

func (x *OrderTicketInfo) GetTicketUserName() string {
	if x != nil {
		return x.TicketUserName
	}
	return ""
}

func (x *OrderTicketInfo) GetTicketUserIdNumber() string {
	if x != nil {
		return x.TicketUserIdNumber
	}
	return ""
}

func (x *OrderTicketInfo) GetTicketCategoryId() int64 {
	if x != nil {
		return x.TicketCategoryId
	}
	return 0
}

func (x *OrderTicketInfo) GetTicketCategoryName() string {
	if x != nil {
		return x.TicketCategoryName
	}
	return ""
}

func (x *OrderTicketInfo) GetTicketPrice() int64 {
	if x != nil {
		return x.TicketPrice
	}
	return 0
}

func (x *OrderTicketInfo) GetSeatId() int64 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *OrderTicketInfo) GetSeatRow() int64 {
	if x != nil {
		return x.SeatRow
	}
	return 0
}

func (x *OrderTicketInfo) GetSeatCol() int64 {
	if x != nil {
		return x.SeatCol
	}
	return 0
}

func (x *OrderTicketInfo) GetSeatPrice() int64 {
	if x != nil {
		return x.SeatPrice
	}
	return 0
}

type OrderDetailInfo struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	OrderNumber             int64                  `protobuf:"varint,1,opt,name=orderNumber,proto3" json:"orderNumber,omitempty"`
	ProgramId               int64                  `protobuf:"varint,2,opt,name=programId,proto3" json:"programId,omitempty"`
	ProgramTitle            string                 `protobuf:"bytes,3,opt,name=programTitle,proto3" json:"programTitle,omitempty"`
	ProgramItemPicture      string                 `protobuf:"bytes,4,opt,name=programItemPicture,proto3" json:"programItemPicture,omitempty"`
	ProgramPlace            string                 `protobuf:"bytes,5,opt,name=programPlace,proto3" json:"programPlace,omitempty"`
	ProgramShowTime         string                 `protobuf:"bytes,6,opt,name=programShowTime,proto3" json:"programShowTime,omitempty"`
	ProgramPermitChooseSeat int64                  `protobuf:"varint,7,opt,name=programPermitChooseSeat,proto3" json:"programPermitChooseSeat,omitempty"`
	UserId                  int64                  `protobuf:"varint,8,opt,name=userId,proto3" json:"userId,omitempty"`
	DistributionMode        string                 `protobuf:"bytes,9,opt,name=distributionMode,proto3" json:"distributionMode,omitempty"`
	TakeTicketMode          string                 `protobuf:"bytes,10,opt,name=takeTicketMode,proto3" json:"takeTicketMode,omitempty"`
	TicketCount             int64                  `protobuf:"varint,11,opt,name=ticketCount,proto3" json:"ticketCount,omitempty"`
	OrderPrice              int64                  `protobuf:"varint,12,opt,name=orderPrice,proto3" json:"orderPrice,omitempty"`
	OrderStatus             int64                  `protobuf:"varint,13,opt,name=orderStatus,proto3" json:"orderStatus,omitempty"`
	FreezeToken             string                 `protobuf:"bytes,14,opt,name=freezeToken,proto3" json:"freezeToken,omitempty"`
	OrderExpireTime         string                 `protobuf:"bytes,15,opt,name=orderExpireTime,proto3" json:"orderExpireTime,omitempty"`
	CreateOrderTime         string                 `protobuf:"bytes,16,opt,name=createOrderTime,proto3" json:"createOrderTime,omitempty"`
	CancelOrderTime         string                 `protobuf:"bytes,17,opt,name=cancelOrderTime,proto3" json:"cancelOrderTime,omitempty"`
	OrderTicketInfoVoList   []*OrderTicketInfo     `protobuf:"bytes,18,rep,name=orderTicketInfoVoList,proto3" json:"orderTicketInfoVoList,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OrderDetailInfo) Reset() {
	*x = OrderDetailInfo{}
	mi := &file_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderDetailInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderDetailInfo) ProtoMessage() {}

func (x *OrderDetailInfo) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderDetailInfo.ProtoReflect.Descriptor instead.
func (*OrderDetailInfo) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{12}
}

func (x *OrderDetailInfo) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

func (x *OrderDetailInfo) GetProgramId() int64 {
	if x != nil {
		return x.ProgramId
	}
	return 0
}

func (x *OrderDetailInfo) GetProgramTitle() string {
	if x != nil {
		return x.ProgramTitle
	}
	return ""
}

func (x *OrderDetailInfo) GetProgramItemPicture() string {
	if x != nil {
		return x.ProgramItemPicture
	}
	return ""
}

func (x *OrderDetailInfo) GetProgramPlace() string {
	if x != nil {
		return x.ProgramPlace
	}
	return ""
}

func (x *OrderDetailInfo) GetProgramShowTime() string {
	if x != nil {
		return x.ProgramShowTime
	}
	return ""
}

func (x *OrderDetailInfo) GetProgramPermitChooseSeat() int64 {
	if x != nil {
		return x.ProgramPermitChooseSeat
	}
	return 0
}

func (x *OrderDetailInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *OrderDetailInfo) GetDistributionMode() string {
	if x != nil {
		return x.DistributionMode
	}
	return ""
}

func (x *OrderDetailInfo) GetTakeTicketMode() string {
	if x != nil {
		return x.TakeTicketMode
	}
	return ""
}

func (x *OrderDetailInfo) GetTicketCount() int64 {
	if x != nil {
		return x.TicketCount
	}
	return 0
}

func (x *OrderDetailInfo) GetOrderPrice() int64 {
	if x != nil {
		return x.OrderPrice
	}
	return 0
}

func (x *OrderDetailInfo) GetOrderStatus() int64 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *OrderDetailInfo) GetFreezeToken() string {
	if x != nil {
		return x.FreezeToken
	}
	return ""
}

func (x *OrderDetailInfo) GetOrderExpireTime() string {
	if x != nil {
		return x.OrderExpireTime
	}
	return ""
}

func (x *OrderDetailInfo) GetCreateOrderTime() string {
	if x != nil {
		return x.CreateOrderTime
	}
	return ""
}

func (x *OrderDetailInfo) GetCancelOrderTime() string {
	if x != nil {
		return x.CancelOrderTime
	}
	return ""
}

func (x *OrderDetailInfo) GetOrderTicketInfoVoList() []*OrderTicketInfo {
	if x != nil {
		return x.OrderTicketInfoVoList
	}
	return nil
}

type CancelOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OrderNumber   int64                  `protobuf:"varint,2,opt,name=orderNumber,proto3" json:"orderNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOrderReq) Reset() {
	*x = CancelOrderReq{}
	mi := &file_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOrderReq) ProtoMessage() {}

func (x *CancelOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOrderReq.ProtoReflect.Descriptor instead.
func (*CancelOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{13}
}

func (x *CancelOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CancelOrderReq) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

type PayOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OrderNumber   int64                  `protobuf:"varint,2,opt,name=orderNumber,proto3" json:"orderNumber,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderReq) Reset() {
	*x = PayOrderReq{}
	mi := &file_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderReq) ProtoMessage() {}

func (x *PayOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderReq.ProtoReflect.Descriptor instead.
func (*PayOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{14}
}

func (x *PayOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PayOrderReq) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

func (x *PayOrderReq) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PayOrderReq) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type PayOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNumber   int64                  `protobuf:"varint,1,opt,name=orderNumber,proto3" json:"orderNumber,omitempty"`
	OrderStatus   int64                  `protobuf:"varint,2,opt,name=orderStatus,proto3" json:"orderStatus,omitempty"`
	PayBillNo     int64                  `protobuf:"varint,3,opt,name=payBillNo,proto3" json:"payBillNo,omitempty"`
	PayStatus     int64                  `protobuf:"varint,4,opt,name=payStatus,proto3" json:"payStatus,omitempty"`
	PayTime       string                 `protobuf:"bytes,5,opt,name=payTime,proto3" json:"payTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayOrderResp) Reset() {
	*x = PayOrderResp{}
	mi := &file_order_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayOrderResp) ProtoMessage() {}

func (x *PayOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayOrderResp.ProtoReflect.Descriptor instead.
func (*PayOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{15}
}

func (x *PayOrderResp) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

func (x *PayOrderResp) GetOrderStatus() int64 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *PayOrderResp) GetPayBillNo() int64 {
	if x != nil {
		return x.PayBillNo
	}
	return 0
}

func (x *PayOrderResp) GetPayStatus() int64 {
	if x != nil {
		return x.PayStatus
	}
	return 0
}

func (x *PayOrderResp) GetPayTime() string {
	if x != nil {
		return x.PayTime
	}
	return ""
}

type PayCheckReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OrderNumber   int64                  `protobuf:"varint,2,opt,name=orderNumber,proto3" json:"orderNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayCheckReq) Reset() {
	*x = PayCheckReq{}
	mi := &file_order_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayCheckReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayCheckReq) ProtoMessage() {}

func (x *PayCheckReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayCheckReq.ProtoReflect.Descriptor instead.
func (*PayCheckReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{16}
}

func (x *PayCheckReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PayCheckReq) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

type PayCheckResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNumber   int64                  `protobuf:"varint,1,opt,name=orderNumber,proto3" json:"orderNumber,omitempty"`
	OrderStatus   int64                  `protobuf:"varint,2,opt,name=orderStatus,proto3" json:"orderStatus,omitempty"`
	PayBillNo     int64                  `protobuf:"varint,3,opt,name=payBillNo,proto3" json:"payBillNo,omitempty"`
	PayStatus     int64                  `protobuf:"varint,4,opt,name=payStatus,proto3" json:"payStatus,omitempty"`
	PayTime       string                 `protobuf:"bytes,5,opt,name=payTime,proto3" json:"payTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayCheckResp) Reset() {
	*x = PayCheckResp{}
	mi := &file_order_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayCheckResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayCheckResp) ProtoMessage() {}

func (x *PayCheckResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayCheckResp.ProtoReflect.Descriptor instead.
func (*PayCheckResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{17}
}

func (x *PayCheckResp) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

func (x *PayCheckResp) GetOrderStatus() int64 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *PayCheckResp) GetPayBillNo() int64 {
	if x != nil {
		return x.PayBillNo
	}
	return 0
}

func (x *PayCheckResp) GetPayStatus() int64 {
	if x != nil {
		return x.PayStatus
	}
	return 0
}

func (x *PayCheckResp) GetPayTime() string {
	if x != nil {
		return x.PayTime
	}
	return ""
}

type RefundOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OrderNumber   int64                  `protobuf:"varint,2,opt,name=orderNumber,proto3" json:"orderNumber,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundOrderReq) Reset() {
	*x = RefundOrderReq{}
	mi := &file_order_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundOrderReq) ProtoMessage() {}

func (x *RefundOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundOrderReq.ProtoReflect.Descriptor instead.
func (*RefundOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{18}
}

func (x *RefundOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RefundOrderReq) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

func (x *RefundOrderReq) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type PreviewRefundOrderReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	OrderNumber   int64                  `protobuf:"varint,2,opt,name=orderNumber,proto3" json:"orderNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewRefundOrderReq) Reset() {
	*x = PreviewRefundOrderReq{}
	mi := &file_order_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewRefundOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewRefundOrderReq) ProtoMessage() {}

func (x *PreviewRefundOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewRefundOrderReq.ProtoReflect.Descriptor instead.
func (*PreviewRefundOrderReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{19}
}

func (x *PreviewRefundOrderReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PreviewRefundOrderReq) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

type PreviewRefundOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNumber   int64                  `protobuf:"varint,1,opt,name=orderNumber,proto3" json:"orderNumber,omitempty"`
	AllowRefund   bool                   `protobuf:"varint,2,opt,name=allowRefund,proto3" json:"allowRefund,omitempty"`
	RefundAmount  int64                  `protobuf:"varint,3,opt,name=refundAmount,proto3" json:"refundAmount,omitempty"`
	RefundPercent int64                  `protobuf:"varint,4,opt,name=refundPercent,proto3" json:"refundPercent,omitempty"`
	RejectReason  string                 `protobuf:"bytes,5,opt,name=rejectReason,proto3" json:"rejectReason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewRefundOrderResp) Reset() {
	*x = PreviewRefundOrderResp{}
	mi := &file_order_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewRefundOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewRefundOrderResp) ProtoMessage() {}

func (x *PreviewRefundOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewRefundOrderResp.ProtoReflect.Descriptor instead.
func (*PreviewRefundOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{20}
}

func (x *PreviewRefundOrderResp) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

func (x *PreviewRefundOrderResp) GetAllowRefund() bool {
	if x != nil {
		return x.AllowRefund
	}
	return false
}

func (x *PreviewRefundOrderResp) GetRefundAmount() int64 {
	if x != nil {
		return x.RefundAmount
	}
	return 0
}

func (x *PreviewRefundOrderResp) GetRefundPercent() int64 {
	if x != nil {
		return x.RefundPercent
	}
	return 0
}

func (x *PreviewRefundOrderResp) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

type RefundOrderResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNumber   int64                  `protobuf:"varint,1,opt,name=orderNumber,proto3" json:"orderNumber,omitempty"`
	OrderStatus   int64                  `protobuf:"varint,2,opt,name=orderStatus,proto3" json:"orderStatus,omitempty"`
	RefundAmount  int64                  `protobuf:"varint,3,opt,name=refundAmount,proto3" json:"refundAmount,omitempty"`
	RefundPercent int64                  `protobuf:"varint,4,opt,name=refundPercent,proto3" json:"refundPercent,omitempty"`
	RefundBillNo  int64                  `protobuf:"varint,5,opt,name=refundBillNo,proto3" json:"refundBillNo,omitempty"`
	RefundTime    string                 `protobuf:"bytes,6,opt,name=refundTime,proto3" json:"refundTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefundOrderResp) Reset() {
	*x = RefundOrderResp{}
	mi := &file_order_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundOrderResp) ProtoMessage() {}

func (x *RefundOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundOrderResp.ProtoReflect.Descriptor instead.
func (*RefundOrderResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{21}
}

func (x *RefundOrderResp) GetOrderNumber() int64 {
	if x != nil {
		return x.OrderNumber
	}
	return 0
}

func (x *RefundOrderResp) GetOrderStatus() int64 {
	if x != nil {
		return x.OrderStatus
	}
	return 0
}

func (x *RefundOrderResp) GetRefundAmount() int64 {
	if x != nil {
		return x.RefundAmount
	}
	return 0
}

func (x *RefundOrderResp) GetRefundPercent() int64 {
	if x != nil {
		return x.RefundPercent
	}
	return 0
}

func (x *RefundOrderResp) GetRefundBillNo() int64 {
	if x != nil {
		return x.RefundBillNo
	}
	return 0
}

func (x *RefundOrderResp) GetRefundTime() string {
	if x != nil {
		return x.RefundTime
	}
	return ""
}

type CloseExpiredOrdersReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Limit          int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	LogicSlotStart int64                  `protobuf:"varint,2,opt,name=logicSlotStart,proto3" json:"logicSlotStart,omitempty"`
	LogicSlotCount int64                  `protobuf:"varint,3,opt,name=logicSlotCount,proto3" json:"logicSlotCount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CloseExpiredOrdersReq) Reset() {
	*x = CloseExpiredOrdersReq{}
	mi := &file_order_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseExpiredOrdersReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseExpiredOrdersReq) ProtoMessage() {}

func (x *CloseExpiredOrdersReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseExpiredOrdersReq.ProtoReflect.Descriptor instead.
func (*CloseExpiredOrdersReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{22}
}

func (x *CloseExpiredOrdersReq) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *CloseExpiredOrdersReq) GetLogicSlotStart() int64 {
	if x != nil {
		return x.LogicSlotStart
	}
	return 0
}

func (x *CloseExpiredOrdersReq) GetLogicSlotCount() int64 {
	if x != nil {
		return x.LogicSlotCount
	}
	return 0
}

type CloseExpiredOrdersResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClosedCount   int64                  `protobuf:"varint,1,opt,name=closedCount,proto3" json:"closedCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseExpiredOrdersResp) Reset() {
	*x = CloseExpiredOrdersResp{}
	mi := &file_order_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseExpiredOrdersResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseExpiredOrdersResp) ProtoMessage() {}

func (x *CloseExpiredOrdersResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseExpiredOrdersResp.ProtoReflect.Descriptor instead.
func (*CloseExpiredOrdersResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{23}
}

func (x *CloseExpiredOrdersResp) GetClosedCount() int64 {
	if x != nil {
		return x.ClosedCount
	}
	return 0
}

type CountActiveTicketsByUserProgramReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	ProgramId     int64                  `protobuf:"varint,2,opt,name=programId,proto3" json:"programId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountActiveTicketsByUserProgramReq) Reset() {
	*x = CountActiveTicketsByUserProgramReq{}
	mi := &file_order_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountActiveTicketsByUserProgramReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountActiveTicketsByUserProgramReq) ProtoMessage() {}

func (x *CountActiveTicketsByUserProgramReq) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountActiveTicketsByUserProgramReq.ProtoReflect.Descriptor instead.
func (*CountActiveTicketsByUserProgramReq) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{24}
}

func (x *CountActiveTicketsByUserProgramReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CountActiveTicketsByUserProgramReq) GetProgramId() int64 {
	if x != nil {
		return x.ProgramId
	}
	return 0
}

type CountActiveTicketsByUserProgramResp struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ActiveTicketCount int64                  `protobuf:"varint,1,opt,name=activeTicketCount,proto3" json:"activeTicketCount,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CountActiveTicketsByUserProgramResp) Reset() {
	*x = CountActiveTicketsByUserProgramResp{}
	mi := &file_order_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountActiveTicketsByUserProgramResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountActiveTicketsByUserProgramResp) ProtoMessage() {}

func (x *CountActiveTicketsByUserProgramResp) ProtoReflect() protoreflect.Message {
	mi := &file_order_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountActiveTicketsByUserProgramResp.ProtoReflect.Descriptor instead.
func (*CountActiveTicketsByUserProgramResp) Descriptor() ([]byte, []int) {
	return file_order_proto_rawDescGZIP(), []int{25}
}

func (x *CountActiveTicketsByUserProgramResp) GetActiveTicketCount() int64 {
	if x != nil {
		return x.ActiveTicketCount
	}
	return 0
}

var File_order_proto protoreflect.FileDescriptor

const file_order_proto_rawDesc = "" +
	"\n" +
	"\vorder.proto\x12\x05order\"$\n" +
	"\bBoolResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xec\x01\n" +
	"\x0eCreateOrderReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1c\n" +
	"\tprogramId\x18\x02 \x01(\x03R\tprogramId\x12*\n" +
	"\x10ticketCategoryId\x18\x03 \x01(\x03R\x10ticketCategoryId\x12$\n" +
	"\rticketUserIds\x18\x04 \x03(\x03R\rticketUserIds\x12*\n" +
	"\x10distributionMode\x18\x05 \x01(\tR\x10distributionMode\x12&\n" +
	"\x0etakeTicketMode\x18\x06 \x01(\tR\x0etakeTicketMode\"3\n" +
	"\x0fCreateOrderResp\x12 \n" +
	"\vorderNumber\x18\x01 \x01(\x03R\vorderNumber\"\x85\x01\n" +
	"\rListOrdersReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"pageNumber\x18\x02 \x01(\x03R\n" +
	"pageNumber\x12\x1a\n" +
	"\bpageSize\x18\x03 \x01(\x03R\bpageSize\x12 \n" +
	"\vorderStatus\x18\x04 \x01(\x03R\vorderStatus\"\xd3\x03\n" +
	"\rOrderListInfo\x12 \n" +
	"\vorderNumber\x18\x01 \x01(\x03R\vorderNumber\x12\x1c\n" +
	"\tprogramId\x18\x02 \x01(\x03R\tprogramId\x12\"\n" +
	"\fprogramTitle\x18\x03 \x01(\tR\fprogramTitle\x12.\n" +
	"\x12programItemPicture\x18\x04 \x01(\tR\x12programItemPicture\x12\"\n" +
	"\fprogramPlace\x18\x05 \x01(\tR\fprogramPlace\x12(\n" +
	"\x0fprogramShowTime\x18\x06 \x01(\tR\x0fprogramShowTime\x12 \n" +
	"\vticketCount\x18\a \x01(\x03R\vticketCount\x12\x1e\n" +
	"\n" +
	"orderPrice\x18\b \x01(\x03R\n" +
	"orderPrice\x12 \n" +
	"\vorderStatus\x18\t \x01(\x03R\vorderStatus\x12(\n" +
	"\x0forderExpireTime\x18\n" +
	" \x01(\tR\x0forderExpireTime\x12(\n" +
	"\x0fcreateOrderTime\x18\v \x01(\tR\x0fcreateOrderTime\x12(\n" +
	"\x0fcancelOrderTime\x18\f \x01(\tR\x0fcancelOrderTime\"\x8e\x01\n" +
	"\x0eListOrdersResp\x12\x18\n" +
	"\apageNum\x18\x01 \x01(\x03R\apageNum\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\x12\x1c\n" +
	"\ttotalSize\x18\x03 \x01(\x03R\ttotalSize\x12(\n" +
	"\x04list\x18\x04 \x03(\v2\x14.order.OrderListInfoR\x04list\"G\n" +
	"\vGetOrderReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12 \n" +
	"\vorderNumber\x18\x02 \x01(\x03R\vorderNumber\"R\n" +
	"\x16GetOrderServiceViewReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12 \n" +
	"\vorderNumber\x18\x02 \x01(\x03R\vorderNumber\"4\n" +
	"\x10GetOrderCacheReq\x12 \n" +
	"\vorderNumber\x18\x01 \x01(\x03R\vorderNumber\")\n" +
	"\x11GetOrderCacheResp\x12\x14\n" +
	"\x05cache\x18\x01 \x01(\tR\x05cache\"\xfc\x02\n" +
	"\x14OrderServiceViewResp\x12 \n" +
	"\vorderNumber\x18\x01 \x01(\x03R\vorderNumber\x12 \n" +
	"\vorderStatus\x18\x02 \x01(\x03R\vorderStatus\x12\x1c\n" +
	"\tpayStatus\x18\x03 \x01(\x03R\tpayStatus\x12\"\n" +
	"\fticketStatus\x18\x04 \x01(\x03R\fticketStatus\x12\"\n" +
	"\fprogramTitle\x18\x05 \x01(\tR\fprogramTitle\x12(\n" +
	"\x0fprogramShowTime\x18\x06 \x01(\tR\x0fprogramShowTime\x12 \n" +
	"\vticketCount\x18\a \x01(\x03R\vticketCount\x12\x1e\n" +
	"\n" +
	"orderPrice\x18\b \x01(\x03R\n" +
	"orderPrice\x12\x1c\n" +
	"\tcanRefund\x18\t \x01(\bR\tcanRefund\x120\n" +
	"\x13refundBlockedReason\x18\n" +
	" \x01(\tR\x13refundBlockedReason\"\xf5\x02\n" +
	"\x0fOrderTicketInfo\x12\"\n" +
	"\fticketUserId\x18\x01 \x01(\x03R\fticketUserId\x12&\n" +
	"\x0eticketUserName\x18\x02 \x01(\tR\x0eticketUserName\x12.\n" +
	"\x12ticketUserIdNumber\x18\x03 \x01(\tR\x12ticketUserIdNumber\x12*\n" +
	"\x10ticketCategoryId\x18\x04 \x01(\x03R\x10ticketCategoryId\x12.\n" +
	"\x12ticketCategoryName\x18\x05 \x01(\tR\x12ticketCategoryName\x12 \n" +
	"\vticketPrice\x18\x06 \x01(\x03R\vticketPrice\x12\x16\n" +
	"\x06seatId\x18\a \x01(\x03R\x06seatId\x12\x18\n" +
	"\aseatRow\x18\b \x01(\x03R\aseatRow\x12\x18\n" +
	"\aseatCol\x18\t \x01(\x03R\aseatCol\x12\x1c\n" +
	"\tseatPrice\x18\n" +
	" \x01(\x03R\tseatPrice\"\xeb\x05\n" +
	"\x0fOrderDetailInfo\x12 \n" +
	"\vorderNumber\x18\x01 \x01(\x03R\vorderNumber\x12\x1c\n" +
	"\tprogramId\x18\x02 \x01(\x03R\tprogramId\x12\"\n" +
	"\fprogramTitle\x18\x03 \x01(\tR\fprogramTitle\x12.\n" +
	"\x12programItemPicture\x18\x04 \x01(\tR\x12programItemPicture\x12\"\n" +
	"\fprogramPlace\x18\x05 \x01(\tR\fprogramPlace\x12(\n" +
	"\x0fprogramShowTime\x18\x06 \x01(\tR\x0fprogramShowTime\x128\n" +
	"\x17programPermitChooseSeat\x18\a \x01(\x03R\x17programPermitChooseSeat\x12\x16\n" +
	"\x06userId\x18\b \x01(\x03R\x06userId\x12*\n" +
	"\x10distributionMode\x18\t \x01(\tR\x10distributionMode\x12&\n" +
	"\x0etakeTicketMode\x18\n" +
	" \x01(\tR\x0etakeTicketMode\x12 \n" +
	"\vticketCount\x18\v \x01(\x03R\vticketCount\x12\x1e\n" +
	"\n" +
	"orderPrice\x18\f \x01(\x03R\n" +
	"orderPrice\x12 \n" +
	"\vorderStatus\x18\r \x01(\x03R\vorderStatus\x12 \n" +
	"\vfreezeToken\x18\x0e \x01(\tR\vfreezeToken\x12(\n" +
	"\x0forderExpireTime\x18\x0f \x01(\tR\x0forderExpireTime\x12(\n" +
	"\x0fcreateOrderTime\x18\x10 \x01(\tR\x0fcreateOrderTime\x12(\n" +
	"\x0fcancelOrderTime\x18\x11 \x01(\tR\x0fcancelOrderTime\x12L\n" +
	"\x15orderTicketInfoVoList\x18\x12 \x03(\v2\x16.order.OrderTicketInfoR\x15orderTicketInfoVoList\"J\n" +
	"\x0eCancelOrderReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12 \n" +
	"\vorderNumber\x18\x02 \x01(\x03R\vorderNumber\"{\n" +
	"\vPayOrderReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12 \n" +
	"\vorderNumber\x18\x02 \x01(\x03R\vorderNumber\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\"\xa8\x01\n" +
	"\fPayOrderResp\x12 \n" +
	"\vorderNumber\x18\x01 \x01(\x03R\vorderNumber\x12 \n" +
	"\vorderStatus\x18\x02 \x01(\x03R\vorderStatus\x12\x1c\n" +
	"\tpayBillNo\x18\x03 \x01(\x03R\tpayBillNo\x12\x1c\n" +
	"\tpayStatus\x18\x04 \x01(\x03R\tpayStatus\x12\x18\n" +
	"\apayTime\x18\x05 \x01(\tR\apayTime\"G\n" +
	"\vPayCheckReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12 \n" +
	"\vorderNumber\x18\x02 \x01(\x03R\vorderNumber\"\xa8\x01\n" +
	"\fPayCheckResp\x12 \n" +
	"\vorderNumber\x18\x01 \x01(\x03R\vorderNumber\x12 \n" +
	"\vorderStatus\x18\x02 \x01(\x03R\vorderStatus\x12\x1c\n" +
	"\tpayBillNo\x18\x03 \x01(\x03R\tpayBillNo\x12\x1c\n" +
	"\tpayStatus\x18\x04 \x01(\x03R\tpayStatus\x12\x18\n" +
	"\apayTime\x18\x05 \x01(\tR\apayTime\"b\n" +
	"\x0eRefundOrderReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12 \n" +
	"\vorderNumber\x18\x02 \x01(\x03R\vorderNumber\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"Q\n" +
	"\x15PreviewRefundOrderReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12 \n" +
	"\vorderNumber\x18\x02 \x01(\x03R\vorderNumber\"\xca\x01\n" +
	"\x16PreviewRefundOrderResp\x12 \n" +
	"\vorderNumber\x18\x01 \x01(\x03R\vorderNumber\x12 \n" +
	"\vallowRefund\x18\x02 \x01(\bR\vallowRefund\x12\"\n" +
	"\frefundAmount\x18\x03 \x01(\x03R\frefundAmount\x12$\n" +
	"\rrefundPercent\x18\x04 \x01(\x03R\rrefundPercent\x12\"\n" +
	"\frejectReason\x18\x05 \x01(\tR\frejectReason\"\xe3\x01\n" +
	"\x0fRefundOrderResp\x12 \n" +
	"\vorderNumber\x18\x01 \x01(\x03R\vorderNumber\x12 \n" +
	"\vorderStatus\x18\x02 \x01(\x03R\vorderStatus\x12\"\n" +
	"\frefundAmount\x18\x03 \x01(\x03R\frefundAmount\x12$\n" +
	"\rrefundPercent\x18\x04 \x01(\x03R\rrefundPercent\x12\"\n" +
	"\frefundBillNo\x18\x05 \x01(\x03R\frefundBillNo\x12\x1e\n" +
	"\n" +
	"refundTime\x18\x06 \x01(\tR\n" +
	"refundTime\"}\n" +
	"\x15CloseExpiredOrdersReq\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12&\n" +
	"\x0elogicSlotStart\x18\x02 \x01(\x03R\x0elogicSlotStart\x12&\n" +
	"\x0elogicSlotCount\x18\x03 \x01(\x03R\x0elogicSlotCount\":\n" +
	"\x16CloseExpiredOrdersResp\x12 \n" +
	"\vclosedCount\x18\x01 \x01(\x03R\vclosedCount\"Z\n" +
	"\"CountActiveTicketsByUserProgramReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1c\n" +
	"\tprogramId\x18\x02 \x01(\x03R\tprogramId\"S\n" +
	"#CountActiveTicketsByUserProgramResp\x12,\n" +
	"\x11activeTicketCount\x18\x01 \x01(\x03R\x11activeTicketCount2\xd1\x06\n" +
	"\bOrderRpc\x12<\n" +
	"\vCreateOrder\x12\x15.order.CreateOrderReq\x1a\x16.order.CreateOrderResp\x129\n" +
	"\n" +
	"ListOrders\x12\x14.order.ListOrdersReq\x1a\x15.order.ListOrdersResp\x126\n" +
	"\bGetOrder\x12\x12.order.GetOrderReq\x1a\x16.order.OrderDetailInfo\x12B\n" +
	"\rGetOrderCache\x12\x17.order.GetOrderCacheReq\x1a\x18.order.GetOrderCacheResp\x12Q\n" +
	"\x13GetOrderServiceView\x12\x1d.order.GetOrderServiceViewReq\x1a\x1b.order.OrderServiceViewResp\x125\n" +
	"\vCancelOrder\x12\x15.order.CancelOrderReq\x1a\x0f.order.BoolResp\x123\n" +
	"\bPayOrder\x12\x12.order.PayOrderReq\x1a\x13.order.PayOrderResp\x123\n" +
	"\bPayCheck\x12\x12.order.PayCheckReq\x1a\x13.order.PayCheckResp\x12Q\n" +
	"\x12PreviewRefundOrder\x12\x1c.order.PreviewRefundOrderReq\x1a\x1d.order.PreviewRefundOrderResp\x12<\n" +
	"\vRefundOrder\x12\x15.order.RefundOrderReq\x1a\x16.order.RefundOrderResp\x12Q\n" +
	"\x12CloseExpiredOrders\x12\x1c.order.CloseExpiredOrdersReq\x1a\x1d.order.CloseExpiredOrdersResp\x12x\n" +
	"\x1fCountActiveTicketsByUserProgram\x12).order.CountActiveTicketsByUserProgramReq\x1a*.order.CountActiveTicketsByUserProgramRespB\x06Z\x04./pbb\x06proto3"

var (
	file_order_proto_rawDescOnce sync.Once
	file_order_proto_rawDescData []byte
)

func file_order_proto_rawDescGZIP() []byte {
	file_order_proto_rawDescOnce.Do(func() {
		file_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)))
	})
	return file_order_proto_rawDescData
}

var file_order_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_order_proto_goTypes = []any{
	(*BoolResp)(nil),                            // 0: order.BoolResp
	(*CreateOrderReq)(nil),                      // 1: order.CreateOrderReq
	(*CreateOrderResp)(nil),                     // 2: order.CreateOrderResp
	(*ListOrdersReq)(nil),                       // 3: order.ListOrdersReq
	(*OrderListInfo)(nil),                       // 4: order.OrderListInfo
	(*ListOrdersResp)(nil),                      // 5: order.ListOrdersResp
	(*GetOrderReq)(nil),                         // 6: order.GetOrderReq
	(*GetOrderServiceViewReq)(nil),              // 7: order.GetOrderServiceViewReq
	(*GetOrderCacheReq)(nil),                    // 8: order.GetOrderCacheReq
	(*GetOrderCacheResp)(nil),                   // 9: order.GetOrderCacheResp
	(*OrderServiceViewResp)(nil),                // 10: order.OrderServiceViewResp
	(*OrderTicketInfo)(nil),                     // 11: order.OrderTicketInfo
	(*OrderDetailInfo)(nil),                     // 12: order.OrderDetailInfo
	(*CancelOrderReq)(nil),                      // 13: order.CancelOrderReq
	(*PayOrderReq)(nil),                         // 14: order.PayOrderReq
	(*PayOrderResp)(nil),                        // 15: order.PayOrderResp
	(*PayCheckReq)(nil),                         // 16: order.PayCheckReq
	(*PayCheckResp)(nil),                        // 17: order.PayCheckResp
	(*RefundOrderReq)(nil),                      // 18: order.RefundOrderReq
	(*PreviewRefundOrderReq)(nil),               // 19: order.PreviewRefundOrderReq
	(*PreviewRefundOrderResp)(nil),              // 20: order.PreviewRefundOrderResp
	(*RefundOrderResp)(nil),                     // 21: order.RefundOrderResp
	(*CloseExpiredOrdersReq)(nil),               // 22: order.CloseExpiredOrdersReq
	(*CloseExpiredOrdersResp)(nil),              // 23: order.CloseExpiredOrdersResp
	(*CountActiveTicketsByUserProgramReq)(nil),  // 24: order.CountActiveTicketsByUserProgramReq
	(*CountActiveTicketsByUserProgramResp)(nil), // 25: order.CountActiveTicketsByUserProgramResp
}
var file_order_proto_depIdxs = []int32{
	4,  // 0: order.ListOrdersResp.list:type_name -> order.OrderListInfo
	11, // 1: order.OrderDetailInfo.orderTicketInfoVoList:type_name -> order.OrderTicketInfo
	1,  // 2: order.OrderRpc.CreateOrder:input_type -> order.CreateOrderReq
	3,  // 3: order.OrderRpc.ListOrders:input_type -> order.ListOrdersReq
	6,  // 4: order.OrderRpc.GetOrder:input_type -> order.GetOrderReq
	8,  // 5: order.OrderRpc.GetOrderCache:input_type -> order.GetOrderCacheReq
	7,  // 6: order.OrderRpc.GetOrderServiceView:input_type -> order.GetOrderServiceViewReq
	13, // 7: order.OrderRpc.CancelOrder:input_type -> order.CancelOrderReq
	14, // 8: order.OrderRpc.PayOrder:input_type -> order.PayOrderReq
	16, // 9: order.OrderRpc.PayCheck:input_type -> order.PayCheckReq
	19, // 10: order.OrderRpc.PreviewRefundOrder:input_type -> order.PreviewRefundOrderReq
	18, // 11: order.OrderRpc.RefundOrder:input_type -> order.RefundOrderReq
	22, // 12: order.OrderRpc.CloseExpiredOrders:input_type -> order.CloseExpiredOrdersReq
	24, // 13: order.OrderRpc.CountActiveTicketsByUserProgram:input_type -> order.CountActiveTicketsByUserProgramReq
	2,  // 14: order.OrderRpc.CreateOrder:output_type -> order.CreateOrderResp
	5,  // 15: order.OrderRpc.ListOrders:output_type -> order.ListOrdersResp
	12, // 16: order.OrderRpc.GetOrder:output_type -> order.OrderDetailInfo
	9,  // 17: order.OrderRpc.GetOrderCache:output_type -> order.GetOrderCacheResp
	10, // 18: order.OrderRpc.GetOrderServiceView:output_type -> order.OrderServiceViewResp
	0,  // 19: order.OrderRpc.CancelOrder:output_type -> order.BoolResp
	15, // 20: order.OrderRpc.PayOrder:output_type -> order.PayOrderResp
	17, // 21: order.OrderRpc.PayCheck:output_type -> order.PayCheckResp
	20, // 22: order.OrderRpc.PreviewRefundOrder:output_type -> order.PreviewRefundOrderResp
	21, // 23: order.OrderRpc.RefundOrder:output_type -> order.RefundOrderResp
	23, // 24: order.OrderRpc.CloseExpiredOrders:output_type -> order.CloseExpiredOrdersResp
	25, // 25: order.OrderRpc.CountActiveTicketsByUserProgram:output_type -> order.CountActiveTicketsByUserProgramResp
	14, // [14:26] is the sub-list for method output_type
	2,  // [2:14] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_order_proto_init() }
func file_order_proto_init() {
	if File_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_proto_rawDesc), len(file_order_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_proto_goTypes,
		DependencyIndexes: file_order_proto_depIdxs,
		MessageInfos:      file_order_proto_msgTypes,
	}.Build()
	File_order_proto = out.File
	file_order_proto_goTypes = nil
	file_order_proto_depIdxs = nil
}
