// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package handler

import (
	"net/http"

	"damai-go/services/program-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/program/category/select/all",
				Handler: ListProgramCategoriesHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/program/detail",
				Handler: GetProgramDetailHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/program/home/list",
				Handler: ListHomeProgramsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/program/page",
				Handler: PageProgramsHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/ticket/category/select/list/by/program",
				Handler: ListTicketCategoriesByProgramHandler(serverCtx),
			},
		},
	)
}
