// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: order.proto

package orderrpc

import (
	"context"

	"livepass/services/order-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BoolResp                             = pb.BoolResp
	CancelOrderReq                       = pb.CancelOrderReq
	CloseExpiredOrderReq                 = pb.CloseExpiredOrderReq
	CloseExpiredOrdersReq                = pb.CloseExpiredOrdersReq
	CloseExpiredOrdersResp               = pb.CloseExpiredOrdersResp
	CountActiveTicketsByUserShowTimeReq  = pb.CountActiveTicketsByUserShowTimeReq
	CountActiveTicketsByUserShowTimeResp = pb.CountActiveTicketsByUserShowTimeResp
	CreateOrderReq                       = pb.CreateOrderReq
	CreateOrderResp                      = pb.CreateOrderResp
	CreatePurchaseTokenReq               = pb.CreatePurchaseTokenReq
	CreatePurchaseTokenResp              = pb.CreatePurchaseTokenResp
	GetOrderCacheReq                     = pb.GetOrderCacheReq
	GetOrderCacheResp                    = pb.GetOrderCacheResp
	GetOrderReq                          = pb.GetOrderReq
	GetOrderServiceViewReq               = pb.GetOrderServiceViewReq
	ListOrdersReq                        = pb.ListOrdersReq
	ListOrdersResp                       = pb.ListOrdersResp
	OrderDetailInfo                      = pb.OrderDetailInfo
	OrderListInfo                        = pb.OrderListInfo
	OrderServiceViewResp                 = pb.OrderServiceViewResp
	OrderTicketInfo                      = pb.OrderTicketInfo
	PayCheckReq                          = pb.PayCheckReq
	PayCheckResp                         = pb.PayCheckResp
	PayOrderReq                          = pb.PayOrderReq
	PayOrderResp                         = pb.PayOrderResp
	PerfCreateOrderResp                  = pb.PerfCreateOrderResp
	PollOrderProgressReq                 = pb.PollOrderProgressReq
	PollOrderProgressResp                = pb.PollOrderProgressResp
	PreviewRefundOrderReq                = pb.PreviewRefundOrderReq
	PreviewRefundOrderResp               = pb.PreviewRefundOrderResp
	PrimeRushRuntimeReq                  = pb.PrimeRushRuntimeReq
	RefundOrderReq                       = pb.RefundOrderReq
	RefundOrderResp                      = pb.RefundOrderResp

	OrderRpc interface {
		CreatePurchaseToken(ctx context.Context, in *CreatePurchaseTokenReq, opts ...grpc.CallOption) (*CreatePurchaseTokenResp, error)
		CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error)
		PerfCreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*PerfCreateOrderResp, error)
		PollOrderProgress(ctx context.Context, in *PollOrderProgressReq, opts ...grpc.CallOption) (*PollOrderProgressResp, error)
		ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*ListOrdersResp, error)
		GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*OrderDetailInfo, error)
		GetOrderCache(ctx context.Context, in *GetOrderCacheReq, opts ...grpc.CallOption) (*GetOrderCacheResp, error)
		GetOrderServiceView(ctx context.Context, in *GetOrderServiceViewReq, opts ...grpc.CallOption) (*OrderServiceViewResp, error)
		CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*BoolResp, error)
		PayOrder(ctx context.Context, in *PayOrderReq, opts ...grpc.CallOption) (*PayOrderResp, error)
		PayCheck(ctx context.Context, in *PayCheckReq, opts ...grpc.CallOption) (*PayCheckResp, error)
		PreviewRefundOrder(ctx context.Context, in *PreviewRefundOrderReq, opts ...grpc.CallOption) (*PreviewRefundOrderResp, error)
		RefundOrder(ctx context.Context, in *RefundOrderReq, opts ...grpc.CallOption) (*RefundOrderResp, error)
		CloseExpiredOrder(ctx context.Context, in *CloseExpiredOrderReq, opts ...grpc.CallOption) (*BoolResp, error)
		CloseExpiredOrders(ctx context.Context, in *CloseExpiredOrdersReq, opts ...grpc.CallOption) (*CloseExpiredOrdersResp, error)
		CountActiveTicketsByUserShowTime(ctx context.Context, in *CountActiveTicketsByUserShowTimeReq, opts ...grpc.CallOption) (*CountActiveTicketsByUserShowTimeResp, error)
		PrimeRushRuntime(ctx context.Context, in *PrimeRushRuntimeReq, opts ...grpc.CallOption) (*BoolResp, error)
	}

	defaultOrderRpc struct {
		cli zrpc.Client
	}
)

func NewOrderRpc(cli zrpc.Client) OrderRpc {
	return &defaultOrderRpc{
		cli: cli,
	}
}

func (m *defaultOrderRpc) CreatePurchaseToken(ctx context.Context, in *CreatePurchaseTokenReq, opts ...grpc.CallOption) (*CreatePurchaseTokenResp, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.CreatePurchaseToken(ctx, in, opts...)
}

func (m *defaultOrderRpc) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

func (m *defaultOrderRpc) PerfCreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*PerfCreateOrderResp, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.PerfCreateOrder(ctx, in, opts...)
}

func (m *defaultOrderRpc) PollOrderProgress(ctx context.Context, in *PollOrderProgressReq, opts ...grpc.CallOption) (*PollOrderProgressResp, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.PollOrderProgress(ctx, in, opts...)
}

func (m *defaultOrderRpc) ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*ListOrdersResp, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.ListOrders(ctx, in, opts...)
}

func (m *defaultOrderRpc) GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*OrderDetailInfo, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.GetOrder(ctx, in, opts...)
}

func (m *defaultOrderRpc) GetOrderCache(ctx context.Context, in *GetOrderCacheReq, opts ...grpc.CallOption) (*GetOrderCacheResp, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.GetOrderCache(ctx, in, opts...)
}

func (m *defaultOrderRpc) GetOrderServiceView(ctx context.Context, in *GetOrderServiceViewReq, opts ...grpc.CallOption) (*OrderServiceViewResp, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.GetOrderServiceView(ctx, in, opts...)
}

func (m *defaultOrderRpc) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*BoolResp, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.CancelOrder(ctx, in, opts...)
}

func (m *defaultOrderRpc) PayOrder(ctx context.Context, in *PayOrderReq, opts ...grpc.CallOption) (*PayOrderResp, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.PayOrder(ctx, in, opts...)
}

func (m *defaultOrderRpc) PayCheck(ctx context.Context, in *PayCheckReq, opts ...grpc.CallOption) (*PayCheckResp, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.PayCheck(ctx, in, opts...)
}

func (m *defaultOrderRpc) PreviewRefundOrder(ctx context.Context, in *PreviewRefundOrderReq, opts ...grpc.CallOption) (*PreviewRefundOrderResp, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.PreviewRefundOrder(ctx, in, opts...)
}

func (m *defaultOrderRpc) RefundOrder(ctx context.Context, in *RefundOrderReq, opts ...grpc.CallOption) (*RefundOrderResp, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.RefundOrder(ctx, in, opts...)
}

func (m *defaultOrderRpc) CloseExpiredOrder(ctx context.Context, in *CloseExpiredOrderReq, opts ...grpc.CallOption) (*BoolResp, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.CloseExpiredOrder(ctx, in, opts...)
}

func (m *defaultOrderRpc) CloseExpiredOrders(ctx context.Context, in *CloseExpiredOrdersReq, opts ...grpc.CallOption) (*CloseExpiredOrdersResp, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.CloseExpiredOrders(ctx, in, opts...)
}

func (m *defaultOrderRpc) CountActiveTicketsByUserShowTime(ctx context.Context, in *CountActiveTicketsByUserShowTimeReq, opts ...grpc.CallOption) (*CountActiveTicketsByUserShowTimeResp, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.CountActiveTicketsByUserShowTime(ctx, in, opts...)
}

func (m *defaultOrderRpc) PrimeRushRuntime(ctx context.Context, in *PrimeRushRuntimeReq, opts ...grpc.CallOption) (*BoolResp, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.PrimeRushRuntime(ctx, in, opts...)
}
