// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: order.proto

package orderrpc

import (
	"context"

	"damai-go/services/order-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BoolResp                            = pb.BoolResp
	CancelOrderReq                      = pb.CancelOrderReq
	CloseExpiredOrdersReq               = pb.CloseExpiredOrdersReq
	CloseExpiredOrdersResp              = pb.CloseExpiredOrdersResp
	CountActiveTicketsByUserProgramReq  = pb.CountActiveTicketsByUserProgramReq
	CountActiveTicketsByUserProgramResp = pb.CountActiveTicketsByUserProgramResp
	CreateOrderReq                      = pb.CreateOrderReq
	CreateOrderResp                     = pb.CreateOrderResp
	GetOrderReq                         = pb.GetOrderReq
	ListOrdersReq                       = pb.ListOrdersReq
	ListOrdersResp                      = pb.ListOrdersResp
	OrderDetailInfo                     = pb.OrderDetailInfo
	OrderListInfo                       = pb.OrderListInfo
	OrderTicketInfo                     = pb.OrderTicketInfo
	PayCheckReq                         = pb.PayCheckReq
	PayCheckResp                        = pb.PayCheckResp
	PayOrderReq                         = pb.PayOrderReq
	PayOrderResp                        = pb.PayOrderResp

	OrderRpc interface {
		CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error)
		ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*ListOrdersResp, error)
		GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*OrderDetailInfo, error)
		CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*BoolResp, error)
		PayOrder(ctx context.Context, in *PayOrderReq, opts ...grpc.CallOption) (*PayOrderResp, error)
		PayCheck(ctx context.Context, in *PayCheckReq, opts ...grpc.CallOption) (*PayCheckResp, error)
		CloseExpiredOrders(ctx context.Context, in *CloseExpiredOrdersReq, opts ...grpc.CallOption) (*CloseExpiredOrdersResp, error)
		CountActiveTicketsByUserProgram(ctx context.Context, in *CountActiveTicketsByUserProgramReq, opts ...grpc.CallOption) (*CountActiveTicketsByUserProgramResp, error)
	}

	defaultOrderRpc struct {
		cli zrpc.Client
	}
)

func NewOrderRpc(cli zrpc.Client) OrderRpc {
	return &defaultOrderRpc{
		cli: cli,
	}
}

func (m *defaultOrderRpc) CreateOrder(ctx context.Context, in *CreateOrderReq, opts ...grpc.CallOption) (*CreateOrderResp, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.CreateOrder(ctx, in, opts...)
}

func (m *defaultOrderRpc) ListOrders(ctx context.Context, in *ListOrdersReq, opts ...grpc.CallOption) (*ListOrdersResp, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.ListOrders(ctx, in, opts...)
}

func (m *defaultOrderRpc) GetOrder(ctx context.Context, in *GetOrderReq, opts ...grpc.CallOption) (*OrderDetailInfo, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.GetOrder(ctx, in, opts...)
}

func (m *defaultOrderRpc) CancelOrder(ctx context.Context, in *CancelOrderReq, opts ...grpc.CallOption) (*BoolResp, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.CancelOrder(ctx, in, opts...)
}

func (m *defaultOrderRpc) PayOrder(ctx context.Context, in *PayOrderReq, opts ...grpc.CallOption) (*PayOrderResp, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.PayOrder(ctx, in, opts...)
}

func (m *defaultOrderRpc) PayCheck(ctx context.Context, in *PayCheckReq, opts ...grpc.CallOption) (*PayCheckResp, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.PayCheck(ctx, in, opts...)
}

func (m *defaultOrderRpc) CloseExpiredOrders(ctx context.Context, in *CloseExpiredOrdersReq, opts ...grpc.CallOption) (*CloseExpiredOrdersResp, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.CloseExpiredOrders(ctx, in, opts...)
}

func (m *defaultOrderRpc) CountActiveTicketsByUserProgram(ctx context.Context, in *CountActiveTicketsByUserProgramReq, opts ...grpc.CallOption) (*CountActiveTicketsByUserProgramResp, error) {
	client := pb.NewOrderRpcClient(m.cli.Conn())
	return client.CountActiveTicketsByUserProgram(ctx, in, opts...)
}
