// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: order.proto

package server

import (
	"context"

	"damai-go/services/order-rpc/internal/logic"
	"damai-go/services/order-rpc/internal/svc"
	"damai-go/services/order-rpc/pb"
)

type OrderRpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedOrderRpcServer
}

func NewOrderRpcServer(svcCtx *svc.ServiceContext) *OrderRpcServer {
	return &OrderRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderRpcServer) CreatePurchaseToken(ctx context.Context, in *pb.CreatePurchaseTokenReq) (*pb.CreatePurchaseTokenResp, error) {
	l := logic.NewCreatePurchaseTokenLogic(ctx, s.svcCtx)
	return l.CreatePurchaseToken(in)
}

func (s *OrderRpcServer) CreateOrder(ctx context.Context, in *pb.CreateOrderReq) (*pb.CreateOrderResp, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

func (s *OrderRpcServer) PollOrderProgress(ctx context.Context, in *pb.PollOrderProgressReq) (*pb.PollOrderProgressResp, error) {
	l := logic.NewPollOrderProgressLogic(ctx, s.svcCtx)
	return l.PollOrderProgress(in)
}

func (s *OrderRpcServer) ListOrders(ctx context.Context, in *pb.ListOrdersReq) (*pb.ListOrdersResp, error) {
	l := logic.NewListOrdersLogic(ctx, s.svcCtx)
	return l.ListOrders(in)
}

func (s *OrderRpcServer) GetOrder(ctx context.Context, in *pb.GetOrderReq) (*pb.OrderDetailInfo, error) {
	l := logic.NewGetOrderLogic(ctx, s.svcCtx)
	return l.GetOrder(in)
}

func (s *OrderRpcServer) GetOrderCache(ctx context.Context, in *pb.GetOrderCacheReq) (*pb.GetOrderCacheResp, error) {
	l := logic.NewGetOrderCacheLogic(ctx, s.svcCtx)
	return l.GetOrderCache(in)
}

func (s *OrderRpcServer) GetOrderServiceView(ctx context.Context, in *pb.GetOrderServiceViewReq) (*pb.OrderServiceViewResp, error) {
	l := logic.NewGetOrderServiceViewLogic(ctx, s.svcCtx)
	return l.GetOrderServiceView(in)
}

func (s *OrderRpcServer) CancelOrder(ctx context.Context, in *pb.CancelOrderReq) (*pb.BoolResp, error) {
	l := logic.NewCancelOrderLogic(ctx, s.svcCtx)
	return l.CancelOrder(in)
}

func (s *OrderRpcServer) PayOrder(ctx context.Context, in *pb.PayOrderReq) (*pb.PayOrderResp, error) {
	l := logic.NewPayOrderLogic(ctx, s.svcCtx)
	return l.PayOrder(in)
}

func (s *OrderRpcServer) PayCheck(ctx context.Context, in *pb.PayCheckReq) (*pb.PayCheckResp, error) {
	l := logic.NewPayCheckLogic(ctx, s.svcCtx)
	return l.PayCheck(in)
}

func (s *OrderRpcServer) PreviewRefundOrder(ctx context.Context, in *pb.PreviewRefundOrderReq) (*pb.PreviewRefundOrderResp, error) {
	l := logic.NewPreviewRefundOrderLogic(ctx, s.svcCtx)
	return l.PreviewRefundOrder(in)
}

func (s *OrderRpcServer) RefundOrder(ctx context.Context, in *pb.RefundOrderReq) (*pb.RefundOrderResp, error) {
	l := logic.NewRefundOrderLogic(ctx, s.svcCtx)
	return l.RefundOrder(in)
}

func (s *OrderRpcServer) CloseExpiredOrder(ctx context.Context, in *pb.CloseExpiredOrderReq) (*pb.BoolResp, error) {
	l := logic.NewCloseExpiredOrderLogic(ctx, s.svcCtx)
	return l.CloseExpiredOrder(in)
}

func (s *OrderRpcServer) CloseExpiredOrders(ctx context.Context, in *pb.CloseExpiredOrdersReq) (*pb.CloseExpiredOrdersResp, error) {
	l := logic.NewCloseExpiredOrdersLogic(ctx, s.svcCtx)
	return l.CloseExpiredOrders(in)
}

func (s *OrderRpcServer) VerifyAttemptDue(ctx context.Context, in *pb.VerifyAttemptDueReq) (*pb.BoolResp, error) {
	l := logic.NewVerifyAttemptDueLogic(ctx, s.svcCtx)
	return l.VerifyAttemptDue(in)
}

func (s *OrderRpcServer) ReconcileRushAttempts(ctx context.Context, in *pb.ReconcileRushAttemptsReq) (*pb.ReconcileRushAttemptsResp, error) {
	l := logic.NewReconcileRushAttemptsLogic(ctx, s.svcCtx)
	return l.ReconcileRushAttempts(in)
}

func (s *OrderRpcServer) CountActiveTicketsByUserShowTime(ctx context.Context, in *pb.CountActiveTicketsByUserShowTimeReq) (*pb.CountActiveTicketsByUserShowTimeResp, error) {
	l := logic.NewCountActiveTicketsByUserShowTimeLogic(ctx, s.svcCtx)
	return l.CountActiveTicketsByUserShowTime(in)
}
