// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: order.proto

package server

import (
	"context"

	"damai-go/services/order-rpc/internal/logic"
	"damai-go/services/order-rpc/internal/svc"
	"damai-go/services/order-rpc/pb"
)

type OrderRpcServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedOrderRpcServer
}

func NewOrderRpcServer(svcCtx *svc.ServiceContext) *OrderRpcServer {
	return &OrderRpcServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderRpcServer) CreateOrder(ctx context.Context, in *pb.CreateOrderReq) (*pb.CreateOrderResp, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}

func (s *OrderRpcServer) ListOrders(ctx context.Context, in *pb.ListOrdersReq) (*pb.ListOrdersResp, error) {
	l := logic.NewListOrdersLogic(ctx, s.svcCtx)
	return l.ListOrders(in)
}

func (s *OrderRpcServer) GetOrder(ctx context.Context, in *pb.GetOrderReq) (*pb.OrderDetailInfo, error) {
	l := logic.NewGetOrderLogic(ctx, s.svcCtx)
	return l.GetOrder(in)
}

func (s *OrderRpcServer) CancelOrder(ctx context.Context, in *pb.CancelOrderReq) (*pb.BoolResp, error) {
	l := logic.NewCancelOrderLogic(ctx, s.svcCtx)
	return l.CancelOrder(in)
}

func (s *OrderRpcServer) CloseExpiredOrders(ctx context.Context, in *pb.CloseExpiredOrdersReq) (*pb.CloseExpiredOrdersResp, error) {
	l := logic.NewCloseExpiredOrdersLogic(ctx, s.svcCtx)
	return l.CloseExpiredOrders(in)
}

func (s *OrderRpcServer) CountActiveTicketsByUserProgram(ctx context.Context, in *pb.CountActiveTicketsByUserProgramReq) (*pb.CountActiveTicketsByUserProgramResp, error) {
	l := logic.NewCountActiveTicketsByUserProgramLogic(ctx, s.svcCtx)
	return l.CountActiveTicketsByUserProgram(in)
}
