// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	dProgramGroupFieldNames          = builder.RawFieldNames(&DProgramGroup{})
	dProgramGroupRows                = strings.Join(dProgramGroupFieldNames, ",")
	dProgramGroupRowsExpectAutoSet   = strings.Join(stringx.Remove(dProgramGroupFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	dProgramGroupRowsWithPlaceHolder = strings.Join(stringx.Remove(dProgramGroupFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	dProgramGroupModel interface {
		Insert(ctx context.Context, data *DProgramGroup) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*DProgramGroup, error)
		Update(ctx context.Context, data *DProgramGroup) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDProgramGroupModel struct {
		conn  sqlx.SqlConn
		table string
	}

	DProgramGroup struct {
		Id             int64     `db:"id"`               // primary key
		ProgramJson    string    `db:"program_json"`     // json list of simple program infos
		RecentShowTime time.Time `db:"recent_show_time"` // nearest show time
		CreateTime     time.Time `db:"create_time"`      // created at
		EditTime       time.Time `db:"edit_time"`        // updated at
		Status         int64     `db:"status"`           // 1 active, 0 deleted
	}
)

func newDProgramGroupModel(conn sqlx.SqlConn) *defaultDProgramGroupModel {
	return &defaultDProgramGroupModel{
		conn:  conn,
		table: "`d_program_group`",
	}
}

func (m *defaultDProgramGroupModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultDProgramGroupModel) FindOne(ctx context.Context, id int64) (*DProgramGroup, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dProgramGroupRows, m.table)
	var resp DProgramGroup
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDProgramGroupModel) Insert(ctx context.Context, data *DProgramGroup) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, dProgramGroupRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.ProgramJson, data.RecentShowTime, data.EditTime, data.Status)
	return ret, err
}

func (m *defaultDProgramGroupModel) Update(ctx context.Context, data *DProgramGroup) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, dProgramGroupRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.ProgramJson, data.RecentShowTime, data.EditTime, data.Status, data.Id)
	return err
}

func (m *defaultDProgramGroupModel) tableName() string {
	return m.table
}
