// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	dProgramFieldNames          = builder.RawFieldNames(&DProgram{})
	dProgramRows                = strings.Join(dProgramFieldNames, ",")
	dProgramRowsExpectAutoSet   = strings.Join(stringx.Remove(dProgramFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	dProgramRowsWithPlaceHolder = strings.Join(stringx.Remove(dProgramFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheDProgramIdPrefix = "cache:dProgram:id:"
)

type (
	dProgramModel interface {
		Insert(ctx context.Context, data *DProgram) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*DProgram, error)
		Update(ctx context.Context, data *DProgram) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDProgramModel struct {
		sqlc.CachedConn
		conn      sqlx.SqlConn
		table     string
		cached    bool
		cacheConf cache.CacheConf
		cacheOpts []cache.Option
	}

	DProgram struct {
		Id                              int64          `db:"id"`                                 // primary key
		ProgramGroupId                  int64          `db:"program_group_id"`                   // program group id
		Prime                           int64          `db:"prime"`                              // 1 primary program in group
		AreaId                          int64          `db:"area_id"`                            // area id
		ProgramCategoryId               int64          `db:"program_category_id"`                // category id
		ParentProgramCategoryId         int64          `db:"parent_program_category_id"`         // parent category id
		Title                           string         `db:"title"`                              // title
		Actor                           sql.NullString `db:"actor"`                              // actor
		Place                           sql.NullString `db:"place"`                              // place
		ItemPicture                     sql.NullString `db:"item_picture"`                       // cover image
		PreSell                         int64          `db:"pre_sell"`                           // 1 presell, 0 no
		PreSellInstruction              sql.NullString `db:"pre_sell_instruction"`               // presell instruction
		ImportantNotice                 sql.NullString `db:"important_notice"`                   // important notice
		Detail                          string         `db:"detail"`                             // detail
		PerOrderLimitPurchaseCount      int64          `db:"per_order_limit_purchase_count"`     // per order limit
		PerAccountLimitPurchaseCount    int64          `db:"per_account_limit_purchase_count"`   // per account limit
		RefundTicketRule                sql.NullString `db:"refund_ticket_rule"`                 // refund rule
		DeliveryInstruction             sql.NullString `db:"delivery_instruction"`               // delivery instruction
		EntryRule                       sql.NullString `db:"entry_rule"`                         // entry rule
		ChildPurchase                   sql.NullString `db:"child_purchase"`                     // child ticket policy
		InvoiceSpecification            sql.NullString `db:"invoice_specification"`              // invoice instruction
		RealTicketPurchaseRule          sql.NullString `db:"real_ticket_purchase_rule"`          // real name purchase rule
		AbnormalOrderDescription        sql.NullString `db:"abnormal_order_description"`         // abnormal order description
		KindReminder                    sql.NullString `db:"kind_reminder"`                      // kind reminder
		PerformanceDuration             sql.NullString `db:"performance_duration"`               // performance duration
		EntryTime                       sql.NullString `db:"entry_time"`                         // entry time
		MinPerformanceCount             sql.NullInt64  `db:"min_performance_count"`              // minimum performance count
		MainActor                       sql.NullString `db:"main_actor"`                         // main actor
		MinPerformanceDuration          sql.NullString `db:"min_performance_duration"`           // minimum performance duration
		ProhibitedItem                  sql.NullString `db:"prohibited_item"`                    // prohibited items
		DepositSpecification            sql.NullString `db:"deposit_specification"`              // deposit instruction
		TotalCount                      sql.NullInt64  `db:"total_count"`                        // initial sellable ticket count
		PermitRefund                    int64          `db:"permit_refund"`                      // 0 no,1 conditional,2 all
		RefundExplain                   sql.NullString `db:"refund_explain"`                     // refund explanation
		RefundRuleJson                  sql.NullString `db:"refund_rule_json"`                   // machine readable refund rule
		RelNameTicketEntrance           int64          `db:"rel_name_ticket_entrance"`           // real-name ticket entry
		RelNameTicketEntranceExplain    sql.NullString `db:"rel_name_ticket_entrance_explain"`   // real-name ticket entry explanation
		PermitChooseSeat                int64          `db:"permit_choose_seat"`                 // 1 allow choose seat
		ChooseSeatExplain               sql.NullString `db:"choose_seat_explain"`                // choose seat explanation
		ElectronicDeliveryTicket        int64          `db:"electronic_delivery_ticket"`         // 0 none,1 e-ticket,2 delivery
		ElectronicDeliveryTicketExplain sql.NullString `db:"electronic_delivery_ticket_explain"` // electronic delivery ticket explanation
		ElectronicInvoice               int64          `db:"electronic_invoice"`                 // 1 yes,0 no
		ElectronicInvoiceExplain        sql.NullString `db:"electronic_invoice_explain"`         // electronic invoice explanation
		HighHeat                        int64          `db:"high_heat"`                          // hot score switch
		ProgramStatus                   int64          `db:"program_status"`                     // 1 on shelf,0 off shelf
		IssueTime                       sql.NullTime   `db:"issue_time"`                         // issue time
		RushSaleOpenTime                sql.NullTime   `db:"rush_sale_open_time"`                // rush sale open time
		RushSaleEndTime                 sql.NullTime   `db:"rush_sale_end_time"`                 // rush sale end time
		InventoryPreheatStatus          int64          `db:"inventory_preheat_status"`           // 0 not preheated, 1 scheduled, 2 completed
		CreateTime                      time.Time      `db:"create_time"`                        // created at
		EditTime                        time.Time      `db:"edit_time"`                          // updated at
		Status                          int64          `db:"status"`                             // 1 active, 0 deleted
	}
)

func newDProgramModel(conn sqlx.SqlConn) *defaultDProgramModel {
	return &defaultDProgramModel{
		conn:  conn,
		table: "`d_program`",
	}
}

func newCachedDProgramModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultDProgramModel {
	return &defaultDProgramModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		conn:       conn,
		table:      "`d_program`",
		cached:     true,
		cacheConf:  c,
		cacheOpts:  append([]cache.Option(nil), opts...),
	}
}

func (m *defaultDProgramModel) withSession(session sqlx.Session) *defaultDProgramModel {
	conn := sqlx.NewSqlConnFromSession(session)
	if m.cached {
		return newCachedDProgramModel(conn, m.cacheConf, m.cacheOpts...)
	}

	return newDProgramModel(conn)
}

func (m *defaultDProgramModel) Delete(ctx context.Context, id int64) error {
	if !m.cached {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		_, err := m.conn.ExecCtx(ctx, query, id)
		return err
	}

	dProgramIdKey := fmt.Sprintf("%s%v", cacheDProgramIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, dProgramIdKey)
	return err
}

func (m *defaultDProgramModel) FindOne(ctx context.Context, id int64) (*DProgram, error) {
	var resp DProgram
	var err error

	if m.cached {
		dProgramIdKey := fmt.Sprintf("%s%v", cacheDProgramIdPrefix, id)
		err = m.QueryRowCtx(ctx, &resp, dProgramIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
			query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dProgramRows, m.table)
			return conn.QueryRowCtx(ctx, v, query, id)
		})
	} else {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dProgramRows, m.table)
		err = m.conn.QueryRowCtx(ctx, &resp, query, id)
	}

	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDProgramModel) Insert(ctx context.Context, data *DProgram) (sql.Result, error) {
	if !m.cached {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, dProgramRowsExpectAutoSet)
		return m.conn.ExecCtx(ctx, query, data.Id, data.ProgramGroupId, data.Prime, data.AreaId, data.ProgramCategoryId, data.ParentProgramCategoryId, data.Title, data.Actor, data.Place, data.ItemPicture, data.PreSell, data.PreSellInstruction, data.ImportantNotice, data.Detail, data.PerOrderLimitPurchaseCount, data.PerAccountLimitPurchaseCount, data.RefundTicketRule, data.DeliveryInstruction, data.EntryRule, data.ChildPurchase, data.InvoiceSpecification, data.RealTicketPurchaseRule, data.AbnormalOrderDescription, data.KindReminder, data.PerformanceDuration, data.EntryTime, data.MinPerformanceCount, data.MainActor, data.MinPerformanceDuration, data.ProhibitedItem, data.DepositSpecification, data.TotalCount, data.PermitRefund, data.RefundExplain, data.RefundRuleJson, data.RelNameTicketEntrance, data.RelNameTicketEntranceExplain, data.PermitChooseSeat, data.ChooseSeatExplain, data.ElectronicDeliveryTicket, data.ElectronicDeliveryTicketExplain, data.ElectronicInvoice, data.ElectronicInvoiceExplain, data.HighHeat, data.ProgramStatus, data.IssueTime, data.RushSaleOpenTime, data.RushSaleEndTime, data.InventoryPreheatStatus, data.EditTime, data.Status)
	}

	dProgramIdKey := fmt.Sprintf("%s%v", cacheDProgramIdPrefix, data.Id)
	return m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, dProgramRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.ProgramGroupId, data.Prime, data.AreaId, data.ProgramCategoryId, data.ParentProgramCategoryId, data.Title, data.Actor, data.Place, data.ItemPicture, data.PreSell, data.PreSellInstruction, data.ImportantNotice, data.Detail, data.PerOrderLimitPurchaseCount, data.PerAccountLimitPurchaseCount, data.RefundTicketRule, data.DeliveryInstruction, data.EntryRule, data.ChildPurchase, data.InvoiceSpecification, data.RealTicketPurchaseRule, data.AbnormalOrderDescription, data.KindReminder, data.PerformanceDuration, data.EntryTime, data.MinPerformanceCount, data.MainActor, data.MinPerformanceDuration, data.ProhibitedItem, data.DepositSpecification, data.TotalCount, data.PermitRefund, data.RefundExplain, data.RefundRuleJson, data.RelNameTicketEntrance, data.RelNameTicketEntranceExplain, data.PermitChooseSeat, data.ChooseSeatExplain, data.ElectronicDeliveryTicket, data.ElectronicDeliveryTicketExplain, data.ElectronicInvoice, data.ElectronicInvoiceExplain, data.HighHeat, data.ProgramStatus, data.IssueTime, data.RushSaleOpenTime, data.RushSaleEndTime, data.InventoryPreheatStatus, data.EditTime, data.Status)
	}, dProgramIdKey)
}

func (m *defaultDProgramModel) Update(ctx context.Context, data *DProgram) error {
	if !m.cached {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, dProgramRowsWithPlaceHolder)
		_, err := m.conn.ExecCtx(ctx, query, data.ProgramGroupId, data.Prime, data.AreaId, data.ProgramCategoryId, data.ParentProgramCategoryId, data.Title, data.Actor, data.Place, data.ItemPicture, data.PreSell, data.PreSellInstruction, data.ImportantNotice, data.Detail, data.PerOrderLimitPurchaseCount, data.PerAccountLimitPurchaseCount, data.RefundTicketRule, data.DeliveryInstruction, data.EntryRule, data.ChildPurchase, data.InvoiceSpecification, data.RealTicketPurchaseRule, data.AbnormalOrderDescription, data.KindReminder, data.PerformanceDuration, data.EntryTime, data.MinPerformanceCount, data.MainActor, data.MinPerformanceDuration, data.ProhibitedItem, data.DepositSpecification, data.TotalCount, data.PermitRefund, data.RefundExplain, data.RefundRuleJson, data.RelNameTicketEntrance, data.RelNameTicketEntranceExplain, data.PermitChooseSeat, data.ChooseSeatExplain, data.ElectronicDeliveryTicket, data.ElectronicDeliveryTicketExplain, data.ElectronicInvoice, data.ElectronicInvoiceExplain, data.HighHeat, data.ProgramStatus, data.IssueTime, data.RushSaleOpenTime, data.RushSaleEndTime, data.InventoryPreheatStatus, data.EditTime, data.Status, data.Id)
		return err
	}

	dProgramIdKey := fmt.Sprintf("%s%v", cacheDProgramIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (sql.Result, error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, dProgramRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.ProgramGroupId, data.Prime, data.AreaId, data.ProgramCategoryId, data.ParentProgramCategoryId, data.Title, data.Actor, data.Place, data.ItemPicture, data.PreSell, data.PreSellInstruction, data.ImportantNotice, data.Detail, data.PerOrderLimitPurchaseCount, data.PerAccountLimitPurchaseCount, data.RefundTicketRule, data.DeliveryInstruction, data.EntryRule, data.ChildPurchase, data.InvoiceSpecification, data.RealTicketPurchaseRule, data.AbnormalOrderDescription, data.KindReminder, data.PerformanceDuration, data.EntryTime, data.MinPerformanceCount, data.MainActor, data.MinPerformanceDuration, data.ProhibitedItem, data.DepositSpecification, data.TotalCount, data.PermitRefund, data.RefundExplain, data.RefundRuleJson, data.RelNameTicketEntrance, data.RelNameTicketEntranceExplain, data.PermitChooseSeat, data.ChooseSeatExplain, data.ElectronicDeliveryTicket, data.ElectronicDeliveryTicketExplain, data.ElectronicInvoice, data.ElectronicInvoiceExplain, data.HighHeat, data.ProgramStatus, data.IssueTime, data.RushSaleOpenTime, data.RushSaleEndTime, data.InventoryPreheatStatus, data.EditTime, data.Status, data.Id)
	}, dProgramIdKey)
	return err
}

func (m *defaultDProgramModel) tableName() string {
	return m.table
}
