// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: pay.proto

package payrpc

import (
	"context"

	"damai-go/services/pay-rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetPayBillReq  = pb.GetPayBillReq
	GetPayBillResp = pb.GetPayBillResp
	MockPayReq     = pb.MockPayReq
	MockPayResp    = pb.MockPayResp
	RefundReq      = pb.RefundReq
	RefundResp     = pb.RefundResp

	PayRpc interface {
		MockPay(ctx context.Context, in *MockPayReq, opts ...grpc.CallOption) (*MockPayResp, error)
		GetPayBill(ctx context.Context, in *GetPayBillReq, opts ...grpc.CallOption) (*GetPayBillResp, error)
		Refund(ctx context.Context, in *RefundReq, opts ...grpc.CallOption) (*RefundResp, error)
	}

	defaultPayRpc struct {
		cli zrpc.Client
	}
)

func NewPayRpc(cli zrpc.Client) PayRpc {
	return &defaultPayRpc{
		cli: cli,
	}
}

func (m *defaultPayRpc) MockPay(ctx context.Context, in *MockPayReq, opts ...grpc.CallOption) (*MockPayResp, error) {
	client := pb.NewPayRpcClient(m.cli.Conn())
	return client.MockPay(ctx, in, opts...)
}

func (m *defaultPayRpc) GetPayBill(ctx context.Context, in *GetPayBillReq, opts ...grpc.CallOption) (*GetPayBillResp, error) {
	client := pb.NewPayRpcClient(m.cli.Conn())
	return client.GetPayBill(ctx, in, opts...)
}

func (m *defaultPayRpc) Refund(ctx context.Context, in *RefundReq, opts ...grpc.CallOption) (*RefundResp, error) {
	client := pb.NewPayRpcClient(m.cli.Conn())
	return client.Refund(ctx, in, opts...)
}
