// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	dUserEmailFieldNames          = builder.RawFieldNames(&DUserEmail{})
	dUserEmailRows                = strings.Join(dUserEmailFieldNames, ",")
	dUserEmailRowsExpectAutoSet   = strings.Join(stringx.Remove(dUserEmailFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	dUserEmailRowsWithPlaceHolder = strings.Join(stringx.Remove(dUserEmailFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	dUserEmailModel interface {
		Insert(ctx context.Context, data *DUserEmail) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*DUserEmail, error)
		FindOneByEmail(ctx context.Context, email string) (*DUserEmail, error)
		Update(ctx context.Context, data *DUserEmail) error
		Delete(ctx context.Context, id int64) error
	}

	defaultDUserEmailModel struct {
		conn  sqlx.SqlConn
		table string
	}

	DUserEmail struct {
		Id          int64        `db:"id"`           // 主键id
		UserId      int64        `db:"user_id"`      // 用户id
		Email       string       `db:"email"`        // 邮箱
		EmailStatus int64        `db:"email_status"` // 是否邮箱认证 1:已验证 0:未验证
		CreateTime  time.Time    `db:"create_time"`  // 创建时间
		EditTime    sql.NullTime `db:"edit_time"`    // 编辑时间
		Status      int64        `db:"status"`       // 1:正常 0:删除
	}
)

func newDUserEmailModel(conn sqlx.SqlConn) *defaultDUserEmailModel {
	return &defaultDUserEmailModel{
		conn:  conn,
		table: "`d_user_email`",
	}
}

func (m *defaultDUserEmailModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultDUserEmailModel) FindOne(ctx context.Context, id int64) (*DUserEmail, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", dUserEmailRows, m.table)
	var resp DUserEmail
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDUserEmailModel) FindOneByEmail(ctx context.Context, email string) (*DUserEmail, error) {
	var resp DUserEmail
	query := fmt.Sprintf("select %s from %s where `email` = ? limit 1", dUserEmailRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, email)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultDUserEmailModel) Insert(ctx context.Context, data *DUserEmail) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, dUserEmailRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UserId, data.Email, data.EmailStatus, data.EditTime, data.Status)
	return ret, err
}

func (m *defaultDUserEmailModel) Update(ctx context.Context, newData *DUserEmail) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, dUserEmailRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.Email, newData.EmailStatus, newData.EditTime, newData.Status, newData.Id)
	return err
}

func (m *defaultDUserEmailModel) tableName() string {
	return m.table
}
